const registro2 =[
  {
    "factura": 1,
    "serie": 14,
    "exp": 2396,
    "Fe_registro": "09-14-20",
    "Domicilio": "Apdo.:679-9225 Nec C/",
    "Moneda": 4,
    "Ramo": "scelerisque, lorem ipsum",
    "Indole": "Nunc Risus Company",
    "Negocio": "Sem Ltd",
    "Cedente": "Eu Eros LLC",
    "AsegAfian": "Aliquam Fringilla Incorporated",
    "Suscriptor": "Eu Odio Industries",
    "vigdesde": "12-08-20",
    "vighasta": "11-17-21",
    "estado": "egestas.",
    "Nuevo": "true",
    "Usuario": "Xander",
    "Poliza": "Y8Z 4O5"
  },
  {
    "factura": 2,
    "serie": 14,
    "exp": 2356,
    "Fe_registro": "05-02-20",
    "Domicilio": "Apartado núm.: 498, 5320 Proin Avenida",
    "Moneda": 4,
    "Ramo": "pharetra ut, pharetra",
    "Indole": "Bibendum LLP",
    "Negocio": "Nascetur Industries",
    "Cedente": "Nibh Dolor Consulting",
    "AsegAfian": "Eu Inc.",
    "Suscriptor": "Ut Eros Non Incorporated",
    "vigdesde": "04-22-20",
    "vighasta": "04-22-22",
    "estado": "interdum",
    "Nuevo": "true",
    "Usuario": "Wallace",
    "Poliza": "T3J 0X8"
  },
  {
    "factura": 3,
    "serie": 10,
    "exp": 2285,
    "Fe_registro": "01-05-20",
    "Domicilio": "Apartado núm.: 416, 8491 Suspendisse Calle",
    "Moneda": 5,
    "Ramo": "ipsum. Suspendisse sagittis.",
    "Indole": "Eu Arcu Morbi Consulting",
    "Negocio": "Arcu Ltd",
    "Cedente": "Ultricies Ornare LLP",
    "AsegAfian": "Fringilla Est Corp.",
    "Suscriptor": "Nec Quam Curabitur Corporation",
    "vigdesde": "11-06-20",
    "vighasta": "03-12-22",
    "estado": "pede.",
    "Nuevo": "true",
    "Usuario": "Ian",
    "Poliza": "H2G 2S3"
  },
  {
    "factura": 4,
    "serie": 10,
    "exp": 2255,
    "Fe_registro": "08-24-21",
    "Domicilio": "Apartado núm.: 940, 6674 In Avenida",
    "Moneda": 7,
    "Ramo": "enim, gravida sit",
    "Indole": "Fermentum Arcu Vestibulum Inc.",
    "Negocio": "Blandit Corporation",
    "Cedente": "Nec Tempus Scelerisque Inc.",
    "AsegAfian": "Sed Sapien LLP",
    "Suscriptor": "Quis Arcu Consulting",
    "vigdesde": "04-26-20",
    "vighasta": "01-31-22",
    "estado": "ante",
    "Nuevo": "false",
    "Usuario": "Jonas",
    "Poliza": "P9O 7C9"
  },
  {
    "factura": 5,
    "serie": 12,
    "exp": 2200,
    "Fe_registro": "06-05-20",
    "Domicilio": "Apdo.:734-1125 Quam Avda.",
    "Moneda": 3,
    "Ramo": "Quisque fringilla",
    "Indole": "Vel Vulputate Eu Institute",
    "Negocio": "Amet Metus Incorporated",
    "Cedente": "Laoreet Libero Et Foundation",
    "AsegAfian": "Lobortis Limited",
    "Suscriptor": "Dictum Proin Eget Foundation",
    "vigdesde": "10-31-20",
    "vighasta": "09-27-21",
    "estado": "sociis",
    "Nuevo": "true",
    "Usuario": "Joel",
    "Poliza": "B4Q 0T4"
  },
  {
    "factura": 6,
    "serie": 16,
    "exp": 2265,
    "Fe_registro": "07-25-21",
    "Domicilio": "Apartado núm.: 643, 3296 Sed ",
    "Moneda": 1,
    "Ramo": "vehicula",
    "Indole": "Ut Molestie Ltd",
    "Negocio": "Eu Turpis Nulla Inc.",
    "Cedente": "Aliquet Odio Corp.",
    "AsegAfian": "Sagittis Semper Associates",
    "Suscriptor": "Laoreet Limited",
    "vigdesde": "01-22-20",
    "vighasta": "09-14-21",
    "estado": "Morbi",
    "Nuevo": "true",
    "Usuario": "Uriel",
    "Poliza": "P1I 0E1"
  },
  {
    "factura": 7,
    "serie": 12,
    "exp": 2346,
    "Fe_registro": "06-13-20",
    "Domicilio": "189-4466 Tristique Avenida",
    "Moneda": 1,
    "Ramo": "Cras dictum",
    "Indole": "Proin Nisl Sem Industries",
    "Negocio": "Cras Eu Tellus Limited",
    "Cedente": "Aenean Eget PC",
    "AsegAfian": "Enim LLP",
    "Suscriptor": "Diam Company",
    "vigdesde": "01-23-20",
    "vighasta": "10-26-21",
    "estado": "erat",
    "Nuevo": "false",
    "Usuario": "Addison",
    "Poliza": "Z0X 0U4"
  },
  {
    "factura": 8,
    "serie": 12,
    "exp": 2240,
    "Fe_registro": "11-26-21",
    "Domicilio": "Apdo.:433-5450 Risus. Avda.",
    "Moneda": 4,
    "Ramo": "Mauris",
    "Indole": "Purus Nullam Scelerisque Consulting",
    "Negocio": "Malesuada Consulting",
    "Cedente": "Malesuada Id Erat Corp.",
    "AsegAfian": "Rutrum Corporation",
    "Suscriptor": "Pharetra Nibh Aliquam Corporation",
    "vigdesde": "11-18-20",
    "vighasta": "11-24-22",
    "estado": "non",
    "Nuevo": "false",
    "Usuario": "Samson",
    "Poliza": "L9X 8J2"
  },
  {
    "factura": 9,
    "serie": 10,
    "exp": 2315,
    "Fe_registro": "09-09-21",
    "Domicilio": "901-2032 Nisi. C.",
    "Moneda": 2,
    "Ramo": "elit, dictum",
    "Indole": "Dui Cras LLC",
    "Negocio": "Quis Inc.",
    "Cedente": "Ornare Lectus Justo Inc.",
    "AsegAfian": "Nunc Sed Inc.",
    "Suscriptor": "Ornare Consulting",
    "vigdesde": "10-15-20",
    "vighasta": "11-28-22",
    "estado": "eros",
    "Nuevo": "false",
    "Usuario": "Jeremy",
    "Poliza": "S2Y 9R7"
  },
  {
    "factura": 10,
    "serie": 16,
    "exp": 2279,
    "Fe_registro": "01-18-21",
    "Domicilio": "716-6628 Adipiscing. C.",
    "Moneda": 7,
    "Ramo": "dolor. Donec",
    "Indole": "Mauris Sit Amet Consulting",
    "Negocio": "Eget Nisi Industries",
    "Cedente": "Mauris Ipsum Porta LLP",
    "AsegAfian": "Sed Nunc Est Ltd",
    "Suscriptor": "Vestibulum Mauris Magna Incorporated",
    "vigdesde": "10-21-20",
    "vighasta": "08-16-21",
    "estado": "tempus",
    "Nuevo": "false",
    "Usuario": "Neil",
    "Poliza": "C3D 4L0"
  },
  {
    "factura": 11,
    "serie": 19,
    "exp": 2221,
    "Fe_registro": "07-29-21",
    "Domicilio": "419-1413 Magna. C.",
    "Moneda": 4,
    "Ramo": "feugiat",
    "Indole": "Dui Semper Company",
    "Negocio": "Et Commodo At Limited",
    "Cedente": "Arcu Limited",
    "AsegAfian": "Fusce Feugiat Lorem Incorporated",
    "Suscriptor": "Neque Pellentesque Massa LLC",
    "vigdesde": "03-23-20",
    "vighasta": "09-27-22",
    "estado": "nisi",
    "Nuevo": "false",
    "Usuario": "Norman",
    "Poliza": "O1W 2O8"
  },
  {
    "factura": 12,
    "serie": 20,
    "exp": 2331,
    "Fe_registro": "02-01-20",
    "Domicilio": "Apdo.:816-7713 Ultrices C/",
    "Moneda": 6,
    "Ramo": "neque. In",
    "Indole": "Vivamus Sit Amet Incorporated",
    "Negocio": "In Magna Phasellus Corporation",
    "Cedente": "Mauris Quis Turpis Company",
    "AsegAfian": "Ullamcorper Consulting",
    "Suscriptor": "Lacus Vestibulum Lorem Incorporated",
    "vigdesde": "11-14-20",
    "vighasta": "12-01-22",
    "estado": "id,",
    "Nuevo": "true",
    "Usuario": "Ryan",
    "Poliza": "A4R 4D0"
  },
  {
    "factura": 13,
    "serie": 15,
    "exp": 2218,
    "Fe_registro": "06-16-21",
    "Domicilio": "Apartado núm.: 384, 8311 Semper Avenida",
    "Moneda": 4,
    "Ramo": "nunc sed",
    "Indole": "Elit Etiam Incorporated",
    "Negocio": "Maecenas Industries",
    "Cedente": "Tellus Justo Ltd",
    "AsegAfian": "Ac PC",
    "Suscriptor": "Neque Pellentesque Massa Inc.",
    "vigdesde": "03-08-20",
    "vighasta": "05-19-22",
    "estado": "Donec",
    "Nuevo": "false",
    "Usuario": "Kennedy",
    "Poliza": "K1G 9X9"
  },
  {
    "factura": 14,
    "serie": 17,
    "exp": 2274,
    "Fe_registro": "08-29-20",
    "Domicilio": "8039 Fringilla Calle",
    "Moneda": 7,
    "Ramo": "iaculis nec,",
    "Indole": "Ac LLC",
    "Negocio": "A Auctor Non Company",
    "Cedente": "Dapibus Limited",
    "AsegAfian": "Elementum LLC",
    "Suscriptor": "Ut Semper Consulting",
    "vigdesde": "08-22-20",
    "vighasta": "12-10-22",
    "estado": "Proin",
    "Nuevo": "false",
    "Usuario": "Chandler",
    "Poliza": "A0S 3Z9"
  },
  {
    "factura": 15,
    "serie": 13,
    "exp": 2303,
    "Fe_registro": "08-21-20",
    "Domicilio": "Apartado núm.: 727, 7296 Amet, C.",
    "Moneda": 7,
    "Ramo": "lobortis. Class",
    "Indole": "Tempor Augue Corp.",
    "Negocio": "Cursus Company",
    "Cedente": "Orci Lobortis Corporation",
    "AsegAfian": "Arcu Incorporated",
    "Suscriptor": "Quis Industries",
    "vigdesde": "03-11-20",
    "vighasta": "09-06-22",
    "estado": "blandit",
    "Nuevo": "true",
    "Usuario": "Conan",
    "Poliza": "H4G 1G6"
  },
  {
    "factura": 16,
    "serie": 10,
    "exp": 2309,
    "Fe_registro": "03-26-20",
    "Domicilio": "6320 Faucibus. Av.",
    "Moneda": 4,
    "Ramo": "in,",
    "Indole": "Nec Corp.",
    "Negocio": "Lectus Quis Massa Company",
    "Cedente": "In Sodales Industries",
    "AsegAfian": "Natoque Penatibus Et Corporation",
    "Suscriptor": "Ligula Aenean Euismod LLP",
    "vigdesde": "08-08-20",
    "vighasta": "01-09-21",
    "estado": "dolor",
    "Nuevo": "true",
    "Usuario": "Kyle",
    "Poliza": "L2J 3H8"
  },
  {
    "factura": 17,
    "serie": 13,
    "exp": 2338,
    "Fe_registro": "05-18-21",
    "Domicilio": "2518 Molestie Calle",
    "Moneda": 3,
    "Ramo": "risus a ultricies",
    "Indole": "Phasellus Institute",
    "Negocio": "Neque Vitae Inc.",
    "Cedente": "Amet Orci Ut Foundation",
    "AsegAfian": "Ornare Fusce Industries",
    "Suscriptor": "Dui Cum PC",
    "vigdesde": "11-17-20",
    "vighasta": "03-10-21",
    "estado": "mauris,",
    "Nuevo": "true",
    "Usuario": "Leo",
    "Poliza": "I4K 3D0"
  },
  {
    "factura": 18,
    "serie": 18,
    "exp": 2394,
    "Fe_registro": "05-08-20",
    "Domicilio": "486-1265 Justo. Carretera",
    "Moneda": 5,
    "Ramo": "vitae risus.",
    "Indole": "Lobortis Incorporated",
    "Negocio": "Etiam Corporation",
    "Cedente": "Egestas Blandit Nam Industries",
    "AsegAfian": "Bibendum LLC",
    "Suscriptor": "Auctor Velit Aliquam LLP",
    "vigdesde": "07-03-20",
    "vighasta": "07-11-22",
    "estado": "Aliquam",
    "Nuevo": "true",
    "Usuario": "Tobias",
    "Poliza": "E4J 4N5"
  },
  {
    "factura": 19,
    "serie": 20,
    "exp": 2284,
    "Fe_registro": "02-15-20",
    "Domicilio": "Apartado núm.: 916, 3660 Maecenas Calle",
    "Moneda": 4,
    "Ramo": "pede ac urna.",
    "Indole": "A Magna Limited",
    "Negocio": "Arcu Sed Eu Limited",
    "Cedente": "Rutrum Magna Cras Inc.",
    "AsegAfian": "Dolor Tempus Consulting",
    "Suscriptor": "Dolor Tempus Ltd",
    "vigdesde": "07-05-20",
    "vighasta": "01-06-22",
    "estado": "parturient",
    "Nuevo": "false",
    "Usuario": "Cody",
    "Poliza": "N2R 0N5"
  },
  {
    "factura": 20,
    "serie": 19,
    "exp": 2351,
    "Fe_registro": "12-06-21",
    "Domicilio": "5912 Semper Calle",
    "Moneda": 1,
    "Ramo": "scelerisque",
    "Indole": "Nunc Corporation",
    "Negocio": "Metus In LLP",
    "Cedente": "Consectetuer Cursus PC",
    "AsegAfian": "Massa Company",
    "Suscriptor": "Integer Consulting",
    "vigdesde": "07-11-20",
    "vighasta": "01-14-21",
    "estado": "sociis",
    "Nuevo": "true",
    "Usuario": "Boris",
    "Poliza": "U3F 9U3"
  },
  {
    "factura": 21,
    "serie": 18,
    "exp": 2391,
    "Fe_registro": "03-08-21",
    "Domicilio": "Apdo.:540-9009 Amet C/",
    "Moneda": 1,
    "Ramo": "eu, eleifend",
    "Indole": "Tincidunt Consulting",
    "Negocio": "Primis In Faucibus Industries",
    "Cedente": "Fusce Mollis Duis Ltd",
    "AsegAfian": "Nulla Corp.",
    "Suscriptor": "Amet Limited",
    "vigdesde": "02-01-20",
    "vighasta": "03-24-21",
    "estado": "quis,",
    "Nuevo": "true",
    "Usuario": "Armando",
    "Poliza": "V8F 1V0"
  },
  {
    "factura": 22,
    "serie": 10,
    "exp": 2305,
    "Fe_registro": "11-30-20",
    "Domicilio": "1057 Rhoncus. Calle",
    "Moneda": 5,
    "Ramo": "ac mi eleifend",
    "Indole": "Neque Venenatis Inc.",
    "Negocio": "Varius Nam Porttitor Incorporated",
    "Cedente": "Id Mollis Nec Incorporated",
    "AsegAfian": "Per Company",
    "Suscriptor": "Non Associates",
    "vigdesde": "11-26-20",
    "vighasta": "01-23-21",
    "estado": "nec",
    "Nuevo": "false",
    "Usuario": "Martin",
    "Poliza": "K3D 9A5"
  },
  {
    "factura": 23,
    "serie": 20,
    "exp": 2284,
    "Fe_registro": "05-02-21",
    "Domicilio": "Apartado núm.: 551, 8678 Arcu. ",
    "Moneda": 3,
    "Ramo": "Aliquam",
    "Indole": "Cras Vehicula Aliquet PC",
    "Negocio": "Eu Eros Nam Incorporated",
    "Cedente": "Odio Nam Interdum Associates",
    "AsegAfian": "Curae; Donec Company",
    "Suscriptor": "Enim Incorporated",
    "vigdesde": "05-07-20",
    "vighasta": "07-26-22",
    "estado": "malesuada",
    "Nuevo": "false",
    "Usuario": "Coby",
    "Poliza": "S8L 2M9"
  },
  {
    "factura": 24,
    "serie": 19,
    "exp": 2255,
    "Fe_registro": "04-20-20",
    "Domicilio": "200-9916 Magna Calle",
    "Moneda": 4,
    "Ramo": "nibh.",
    "Indole": "Orci Tincidunt Institute",
    "Negocio": "Purus Sapien Incorporated",
    "Cedente": "Et Malesuada Fames Limited",
    "AsegAfian": "Hendrerit LLC",
    "Suscriptor": "Duis Elementum Dui Institute",
    "vigdesde": "08-30-20",
    "vighasta": "07-13-21",
    "estado": "Ut",
    "Nuevo": "false",
    "Usuario": "Reece",
    "Poliza": "S4L 6J3"
  },
  {
    "factura": 25,
    "serie": 16,
    "exp": 2250,
    "Fe_registro": "06-27-20",
    "Domicilio": "3301 Quam. C.",
    "Moneda": 7,
    "Ramo": "dui. Fusce diam",
    "Indole": "Eros PC",
    "Negocio": "Ut Odio Vel Associates",
    "Cedente": "Dictum Sapien Aenean LLC",
    "AsegAfian": "Interdum Libero Inc.",
    "Suscriptor": "Diam Dictum Inc.",
    "vigdesde": "04-12-20",
    "vighasta": "04-15-21",
    "estado": "diam",
    "Nuevo": "false",
    "Usuario": "Abbot",
    "Poliza": "X3Y 4W6"
  },
  {
    "factura": 26,
    "serie": 15,
    "exp": 2392,
    "Fe_registro": "11-22-20",
    "Domicilio": "163-9715 In Ctra.",
    "Moneda": 2,
    "Ramo": "nulla. Integer urna.",
    "Indole": "Lacinia Institute",
    "Negocio": "Ut Ipsum Ac Industries",
    "Cedente": "Non Massa Foundation",
    "AsegAfian": "Ad Litora Consulting",
    "Suscriptor": "Amet Consulting",
    "vigdesde": "07-20-20",
    "vighasta": "07-05-22",
    "estado": "Donec",
    "Nuevo": "true",
    "Usuario": "Asher",
    "Poliza": "K4L 3R8"
  },
  {
    "factura": 27,
    "serie": 20,
    "exp": 2249,
    "Fe_registro": "09-09-20",
    "Domicilio": "Apartado núm.: 871, 5841 Ornare Avda.",
    "Moneda": 2,
    "Ramo": "ipsum",
    "Indole": "Ipsum Inc.",
    "Negocio": "Morbi Accumsan Corp.",
    "Cedente": "Sapien Cursus Consulting",
    "AsegAfian": "Enim Curabitur Company",
    "Suscriptor": "Curabitur Corp.",
    "vigdesde": "07-22-20",
    "vighasta": "01-29-22",
    "estado": "mauris",
    "Nuevo": "true",
    "Usuario": "Igor",
    "Poliza": "I3N 1P0"
  },
  {
    "factura": 28,
    "serie": 13,
    "exp": 2214,
    "Fe_registro": "03-22-20",
    "Domicilio": "Apdo.:531-1229 Donec ",
    "Moneda": 6,
    "Ramo": "cubilia",
    "Indole": "Rutrum Ltd",
    "Negocio": "Pede Nunc Sed Industries",
    "Cedente": "Curabitur Egestas Associates",
    "AsegAfian": "Vel PC",
    "Suscriptor": "Ornare Libero Company",
    "vigdesde": "05-08-20",
    "vighasta": "08-23-21",
    "estado": "a",
    "Nuevo": "false",
    "Usuario": "Emery",
    "Poliza": "N4N 7N1"
  },
  {
    "factura": 29,
    "serie": 18,
    "exp": 2281,
    "Fe_registro": "09-07-21",
    "Domicilio": "Apdo.:745-8358 Vulputate, Avda.",
    "Moneda": 5,
    "Ramo": "est",
    "Indole": "Dignissim Industries",
    "Negocio": "Aenean Egestas LLP",
    "Cedente": "Arcu Sed Institute",
    "AsegAfian": "Orci Consulting",
    "Suscriptor": "Arcu Associates",
    "vigdesde": "12-22-20",
    "vighasta": "06-16-22",
    "estado": "dui.",
    "Nuevo": "false",
    "Usuario": "Hedley",
    "Poliza": "P4F 5I6"
  },
  {
    "factura": 30,
    "serie": 19,
    "exp": 2210,
    "Fe_registro": "11-13-21",
    "Domicilio": "8811 In Calle",
    "Moneda": 7,
    "Ramo": "faucibus ut, nulla.",
    "Indole": "Justo Nec LLC",
    "Negocio": "Non Consulting",
    "Cedente": "Eget Ipsum Corp.",
    "AsegAfian": "Mauris PC",
    "Suscriptor": "Montes Nascetur Ridiculus Corporation",
    "vigdesde": "03-26-20",
    "vighasta": "09-17-22",
    "estado": "imperdiet",
    "Nuevo": "true",
    "Usuario": "Nicholas",
    "Poliza": "Z6F 6H3"
  },
  {
    "factura": 31,
    "serie": 18,
    "exp": 2248,
    "Fe_registro": "05-22-20",
    "Domicilio": "8956 Risus. Calle",
    "Moneda": 4,
    "Ramo": "cursus",
    "Indole": "Lacinia Corporation",
    "Negocio": "Integer Id Associates",
    "Cedente": "Felis Foundation",
    "AsegAfian": "Feugiat Institute",
    "Suscriptor": "Quisque Libero Lacus LLC",
    "vigdesde": "10-20-20",
    "vighasta": "07-22-21",
    "estado": "sed",
    "Nuevo": "false",
    "Usuario": "Barclay",
    "Poliza": "C4B 0D1"
  },
  {
    "factura": 32,
    "serie": 18,
    "exp": 2333,
    "Fe_registro": "04-04-20",
    "Domicilio": "522 Integer Avenida",
    "Moneda": 7,
    "Ramo": "fringilla purus",
    "Indole": "Dignissim Magna Foundation",
    "Negocio": "Fusce Feugiat Lorem Incorporated",
    "Cedente": "Nulla Semper LLC",
    "AsegAfian": "Eget Company",
    "Suscriptor": "Nulla Magna Foundation",
    "vigdesde": "01-11-20",
    "vighasta": "03-13-22",
    "estado": "vitae",
    "Nuevo": "true",
    "Usuario": "Kenyon",
    "Poliza": "E6M 0U4"
  },
  {
    "factura": 33,
    "serie": 16,
    "exp": 2374,
    "Fe_registro": "11-28-20",
    "Domicilio": "432-2638 Eu Avda.",
    "Moneda": 1,
    "Ramo": "euismod",
    "Indole": "Netus Et Corp.",
    "Negocio": "Sociis Natoque Penatibus LLC",
    "Cedente": "Accumsan Laoreet LLC",
    "AsegAfian": "Purus Gravida Institute",
    "Suscriptor": "Sed Associates",
    "vigdesde": "02-19-20",
    "vighasta": "11-15-22",
    "estado": "Donec",
    "Nuevo": "false",
    "Usuario": "Raja",
    "Poliza": "L6F 8Q2"
  },
  {
    "factura": 34,
    "serie": 11,
    "exp": 2225,
    "Fe_registro": "09-18-21",
    "Domicilio": "Apdo.:303-1926 Aenean Carretera",
    "Moneda": 3,
    "Ramo": "lacinia.",
    "Indole": "Sagittis Semper Nam Corp.",
    "Negocio": "Nonummy Ut Company",
    "Cedente": "Aenean Eget Metus Associates",
    "AsegAfian": "Nisi Cum Inc.",
    "Suscriptor": "Cum Inc.",
    "vigdesde": "09-09-20",
    "vighasta": "11-16-21",
    "estado": "leo.",
    "Nuevo": "true",
    "Usuario": "Barry",
    "Poliza": "A1W 2W6"
  },
  {
    "factura": 35,
    "serie": 14,
    "exp": 2280,
    "Fe_registro": "08-01-21",
    "Domicilio": "Apartado núm.: 462, 8660 Eget C.",
    "Moneda": 4,
    "Ramo": "Pellentesque ut ipsum",
    "Indole": "Nibh LLP",
    "Negocio": "Nibh Phasellus LLP",
    "Cedente": "Eu Corp.",
    "AsegAfian": "Eu Consulting",
    "Suscriptor": "Egestas Inc.",
    "vigdesde": "10-19-20",
    "vighasta": "02-28-22",
    "estado": "convallis",
    "Nuevo": "false",
    "Usuario": "Ignatius",
    "Poliza": "O3A 0H5"
  },
  {
    "factura": 36,
    "serie": 12,
    "exp": 2290,
    "Fe_registro": "06-16-21",
    "Domicilio": "Apartado núm.: 505, 8825 Risus C.",
    "Moneda": 6,
    "Ramo": "luctus vulputate, nisi",
    "Indole": "Quam Quis Inc.",
    "Negocio": "Augue Sed Limited",
    "Cedente": "Ac Urna Ut Foundation",
    "AsegAfian": "Eu Tellus Consulting",
    "Suscriptor": "Dolor Dolor Consulting",
    "vigdesde": "04-06-20",
    "vighasta": "08-12-22",
    "estado": "sollicitudin",
    "Nuevo": "true",
    "Usuario": "Hammett",
    "Poliza": "G1X 7J6"
  },
  {
    "factura": 37,
    "serie": 10,
    "exp": 2336,
    "Fe_registro": "01-07-21",
    "Domicilio": "Apartado núm.: 450, 6758 At, Avda.",
    "Moneda": 2,
    "Ramo": "urna. Nullam",
    "Indole": "Lorem Vitae Institute",
    "Negocio": "Vivamus Consulting",
    "Cedente": "Hendrerit Id Ante Consulting",
    "AsegAfian": "A LLC",
    "Suscriptor": "Sagittis Company",
    "vigdesde": "07-16-20",
    "vighasta": "06-29-22",
    "estado": "Aliquam",
    "Nuevo": "true",
    "Usuario": "Julian",
    "Poliza": "Y4L 6P4"
  },
  {
    "factura": 38,
    "serie": 17,
    "exp": 2308,
    "Fe_registro": "12-21-21",
    "Domicilio": "Apartado núm.: 357, 7635 Ipsum Carretera",
    "Moneda": 4,
    "Ramo": "elit, a feugiat",
    "Indole": "Etiam Incorporated",
    "Negocio": "Cras Lorem Lorem Inc.",
    "Cedente": "Egestas Ligula Ltd",
    "AsegAfian": "Consequat Purus Maecenas LLP",
    "Suscriptor": "Nec Metus Facilisis Company",
    "vigdesde": "09-01-20",
    "vighasta": "03-03-21",
    "estado": "Sed",
    "Nuevo": "true",
    "Usuario": "Zahir",
    "Poliza": "J2J 1L2"
  },
  {
    "factura": 39,
    "serie": 20,
    "exp": 2388,
    "Fe_registro": "08-08-20",
    "Domicilio": "Apdo.:678-1196 Fusce Av.",
    "Moneda": 6,
    "Ramo": "mattis.",
    "Indole": "Mauris Blandit Company",
    "Negocio": "Aliquam Eros Turpis Corp.",
    "Cedente": "Enim Etiam PC",
    "AsegAfian": "Pellentesque A Facilisis Limited",
    "Suscriptor": "Pretium Et Institute",
    "vigdesde": "07-08-20",
    "vighasta": "10-04-21",
    "estado": "eget",
    "Nuevo": "true",
    "Usuario": "Fletcher",
    "Poliza": "T1V 1M3"
  },
  {
    "factura": 40,
    "serie": 11,
    "exp": 2330,
    "Fe_registro": "11-29-20",
    "Domicilio": "Apdo.:879-2583 Consectetuer C.",
    "Moneda": 6,
    "Ramo": "ut",
    "Indole": "Vivamus Molestie Dapibus Corporation",
    "Negocio": "Mi Lorem Vehicula Corp.",
    "Cedente": "Semper Cursus Corporation",
    "AsegAfian": "Adipiscing Mauris Molestie Limited",
    "Suscriptor": "Egestas Duis LLC",
    "vigdesde": "10-28-20",
    "vighasta": "12-16-21",
    "estado": "vel",
    "Nuevo": "false",
    "Usuario": "Rooney",
    "Poliza": "J0U 1J8"
  },
  {
    "factura": 41,
    "serie": 15,
    "exp": 2385,
    "Fe_registro": "07-21-21",
    "Domicilio": "392-7145 Arcu. Calle",
    "Moneda": 4,
    "Ramo": "Etiam",
    "Indole": "Mattis Ltd",
    "Negocio": "Sed Est Nunc Foundation",
    "Cedente": "In Lorem Consulting",
    "AsegAfian": "Pede Nec Ltd",
    "Suscriptor": "Mauris Industries",
    "vigdesde": "05-27-20",
    "vighasta": "03-08-22",
    "estado": "Duis",
    "Nuevo": "false",
    "Usuario": "Sean",
    "Poliza": "T3Y 7V5"
  },
  {
    "factura": 42,
    "serie": 14,
    "exp": 2347,
    "Fe_registro": "01-01-21",
    "Domicilio": "Apdo.:488-9170 Risus. Ctra.",
    "Moneda": 3,
    "Ramo": "metus",
    "Indole": "Nullam Suscipit Inc.",
    "Negocio": "Eget Nisi Dictum Limited",
    "Cedente": "Consequat Purus Maecenas PC",
    "AsegAfian": "Aliquam Eu Accumsan LLP",
    "Suscriptor": "Quam Curabitur Vel Ltd",
    "vigdesde": "06-12-20",
    "vighasta": "10-09-22",
    "estado": "dis",
    "Nuevo": "false",
    "Usuario": "Eric",
    "Poliza": "U7T 1Y7"
  },
  {
    "factura": 43,
    "serie": 10,
    "exp": 2256,
    "Fe_registro": "11-18-21",
    "Domicilio": "Apartado núm.: 345, 1478 Nullam Av.",
    "Moneda": 2,
    "Ramo": "nec tellus. Nunc",
    "Indole": "Consequat Enim Corporation",
    "Negocio": "Non Corporation",
    "Cedente": "Mauris LLP",
    "AsegAfian": "Vitae Odio Inc.",
    "Suscriptor": "Vivamus Euismod LLP",
    "vigdesde": "04-18-20",
    "vighasta": "04-30-22",
    "estado": "nibh",
    "Nuevo": "false",
    "Usuario": "Cody",
    "Poliza": "C0N 9K3"
  },
  {
    "factura": 44,
    "serie": 18,
    "exp": 2391,
    "Fe_registro": "10-05-20",
    "Domicilio": "Apartado núm.: 237, 4662 Euismod Avenida",
    "Moneda": 6,
    "Ramo": "libero nec",
    "Indole": "Nunc Pulvinar Consulting",
    "Negocio": "Nulla Aliquet Industries",
    "Cedente": "Massa Suspendisse LLP",
    "AsegAfian": "Euismod Urna Limited",
    "Suscriptor": "Tempus Lorem Consulting",
    "vigdesde": "04-19-20",
    "vighasta": "05-19-21",
    "estado": "at,",
    "Nuevo": "true",
    "Usuario": "Rajah",
    "Poliza": "M4C 5W1"
  },
  {
    "factura": 45,
    "serie": 13,
    "exp": 2213,
    "Fe_registro": "11-13-21",
    "Domicilio": "3453 Aliquet. Av.",
    "Moneda": 2,
    "Ramo": "pede",
    "Indole": "Pellentesque A Facilisis Inc.",
    "Negocio": "Mollis Foundation",
    "Cedente": "Interdum LLP",
    "AsegAfian": "Orci Luctus Et Ltd",
    "Suscriptor": "Lacinia PC",
    "vigdesde": "10-10-20",
    "vighasta": "11-06-22",
    "estado": "non",
    "Nuevo": "true",
    "Usuario": "Erasmus",
    "Poliza": "N9Y 9A0"
  },
  {
    "factura": 46,
    "serie": 13,
    "exp": 2260,
    "Fe_registro": "12-10-21",
    "Domicilio": "1698 Nec, Avda.",
    "Moneda": 2,
    "Ramo": "egestas.",
    "Indole": "At Pretium Industries",
    "Negocio": "Arcu Company",
    "Cedente": "Ligula Tortor Corp.",
    "AsegAfian": "Gravida Nunc Sed LLP",
    "Suscriptor": "Nulla Associates",
    "vigdesde": "07-11-20",
    "vighasta": "09-27-22",
    "estado": "porttitor",
    "Nuevo": "true",
    "Usuario": "Ronan",
    "Poliza": "O4U 4V3"
  },
  {
    "factura": 47,
    "serie": 12,
    "exp": 2340,
    "Fe_registro": "06-15-20",
    "Domicilio": "3347 Nec, ",
    "Moneda": 7,
    "Ramo": "felis orci, adipiscing",
    "Indole": "Mi Inc.",
    "Negocio": "Rutrum Magna Corporation",
    "Cedente": "Tempus Eu Ligula Incorporated",
    "AsegAfian": "Amet Massa Foundation",
    "Suscriptor": "Risus Odio Company",
    "vigdesde": "09-03-20",
    "vighasta": "02-02-21",
    "estado": "quam.",
    "Nuevo": "true",
    "Usuario": "Troy",
    "Poliza": "Y8Y 0B2"
  },
  {
    "factura": 48,
    "serie": 12,
    "exp": 2240,
    "Fe_registro": "07-15-20",
    "Domicilio": "947-8382 Dapibus C/",
    "Moneda": 1,
    "Ramo": "Cras vehicula",
    "Indole": "Risus Nulla Industries",
    "Negocio": "Nascetur Ridiculus Corporation",
    "Cedente": "Feugiat Sed Nec Incorporated",
    "AsegAfian": "Molestie Inc.",
    "Suscriptor": "Laoreet Corporation",
    "vigdesde": "02-21-20",
    "vighasta": "11-21-22",
    "estado": "eget",
    "Nuevo": "true",
    "Usuario": "Anthony",
    "Poliza": "B8H 3V4"
  },
  {
    "factura": 49,
    "serie": 11,
    "exp": 2377,
    "Fe_registro": "05-20-21",
    "Domicilio": "Apartado núm.: 607, 4862 Nibh Calle",
    "Moneda": 4,
    "Ramo": "ipsum porta",
    "Indole": "Urna Nec Institute",
    "Negocio": "Egestas Fusce Aliquet Corp.",
    "Cedente": "Morbi Tristique Corporation",
    "AsegAfian": "Mauris Morbi Non Limited",
    "Suscriptor": "Faucibus Ut Nulla Ltd",
    "vigdesde": "02-24-20",
    "vighasta": "01-26-21",
    "estado": "egestas.",
    "Nuevo": "true",
    "Usuario": "Elton",
    "Poliza": "V2M 8M5"
  },
  {
    "factura": 50,
    "serie": 17,
    "exp": 2204,
    "Fe_registro": "07-25-21",
    "Domicilio": "690-3222 Malesuada Ctra.",
    "Moneda": 6,
    "Ramo": "Curabitur sed tortor.",
    "Indole": "Elit Fermentum Risus Corporation",
    "Negocio": "Id Enim Curabitur Corp.",
    "Cedente": "Quis Company",
    "AsegAfian": "Lorem Sit Amet Consulting",
    "Suscriptor": "Non Corp.",
    "vigdesde": "08-11-20",
    "vighasta": "10-28-21",
    "estado": "eros",
    "Nuevo": "true",
    "Usuario": "Moses",
    "Poliza": "H0O 1E3"
  },
  {
    "factura": 51,
    "serie": 14,
    "exp": 2352,
    "Fe_registro": "05-16-20",
    "Domicilio": "1175 Eget Avda.",
    "Moneda": 1,
    "Ramo": "placerat. Cras",
    "Indole": "Ligula Tortor PC",
    "Negocio": "Lacus Mauris Non LLC",
    "Cedente": "Sed Orci Lobortis Company",
    "AsegAfian": "Sit Corporation",
    "Suscriptor": "Scelerisque Corporation",
    "vigdesde": "12-24-20",
    "vighasta": "12-11-21",
    "estado": "a",
    "Nuevo": "false",
    "Usuario": "Charles",
    "Poliza": "A6J 8A5"
  },
  {
    "factura": 52,
    "serie": 20,
    "exp": 2378,
    "Fe_registro": "03-15-21",
    "Domicilio": "Apdo.:537-4430 Suspendisse ",
    "Moneda": 5,
    "Ramo": "lacinia.",
    "Indole": "Urna Inc.",
    "Negocio": "Tincidunt Adipiscing Industries",
    "Cedente": "Amet Metus Aliquam Limited",
    "AsegAfian": "Nullam Suscipit Associates",
    "Suscriptor": "Commodo Hendrerit Donec Limited",
    "vigdesde": "06-05-20",
    "vighasta": "03-11-21",
    "estado": "sociis",
    "Nuevo": "true",
    "Usuario": "Bernard",
    "Poliza": "F6K 7G9"
  },
  {
    "factura": 53,
    "serie": 16,
    "exp": 2208,
    "Fe_registro": "02-24-21",
    "Domicilio": "5261 Faucibus. ",
    "Moneda": 5,
    "Ramo": "orci tincidunt adipiscing.",
    "Indole": "Lectus Industries",
    "Negocio": "Sem LLC",
    "Cedente": "Risus Ltd",
    "AsegAfian": "Risus Donec Limited",
    "Suscriptor": "Volutpat Corp.",
    "vigdesde": "04-15-20",
    "vighasta": "08-25-22",
    "estado": "fermentum",
    "Nuevo": "false",
    "Usuario": "Quentin",
    "Poliza": "V6R 6M2"
  },
  {
    "factura": 54,
    "serie": 14,
    "exp": 2206,
    "Fe_registro": "07-26-21",
    "Domicilio": "130-1661 Sodales. Calle",
    "Moneda": 3,
    "Ramo": "et magnis dis",
    "Indole": "Est Industries",
    "Negocio": "Malesuada Malesuada Integer Foundation",
    "Cedente": "Lacinia Institute",
    "AsegAfian": "Erat Incorporated",
    "Suscriptor": "Nunc Limited",
    "vigdesde": "02-13-20",
    "vighasta": "11-12-21",
    "estado": "ante",
    "Nuevo": "false",
    "Usuario": "Damon",
    "Poliza": "U7Q 2U6"
  },
  {
    "factura": 55,
    "serie": 12,
    "exp": 2289,
    "Fe_registro": "05-21-21",
    "Domicilio": "5530 Vitae, ",
    "Moneda": 1,
    "Ramo": "neque. Sed eget",
    "Indole": "Non Luctus Foundation",
    "Negocio": "Nec Euismod In Ltd",
    "Cedente": "Quis Incorporated",
    "AsegAfian": "Quisque Ornare Foundation",
    "Suscriptor": "A Aliquet Consulting",
    "vigdesde": "03-17-20",
    "vighasta": "05-18-22",
    "estado": "sapien.",
    "Nuevo": "true",
    "Usuario": "Kamal",
    "Poliza": "M6S 6F8"
  },
  {
    "factura": 56,
    "serie": 11,
    "exp": 2242,
    "Fe_registro": "02-27-20",
    "Domicilio": "Apartado núm.: 720, 809 Velit Carretera",
    "Moneda": 2,
    "Ramo": "mi",
    "Indole": "Dictum Eu Eleifend Consulting",
    "Negocio": "Faucibus Id Libero Limited",
    "Cedente": "Quam Vel Sapien Incorporated",
    "AsegAfian": "Purus Mauris A LLC",
    "Suscriptor": "Imperdiet Nec Leo Associates",
    "vigdesde": "01-19-20",
    "vighasta": "07-25-22",
    "estado": "Vivamus",
    "Nuevo": "false",
    "Usuario": "Hakeem",
    "Poliza": "V5U 3U3"
  },
  {
    "factura": 57,
    "serie": 12,
    "exp": 2270,
    "Fe_registro": "02-05-20",
    "Domicilio": "Apartado núm.: 194, 8515 Aenean Av.",
    "Moneda": 5,
    "Ramo": "Nam porttitor",
    "Indole": "Vestibulum Foundation",
    "Negocio": "Dictum Institute",
    "Cedente": "Integer In Magna Limited",
    "AsegAfian": "Erat Eget Tincidunt LLC",
    "Suscriptor": "Nec Company",
    "vigdesde": "07-24-20",
    "vighasta": "07-27-21",
    "estado": "aliquet",
    "Nuevo": "true",
    "Usuario": "Jack",
    "Poliza": "X2A 0Q6"
  },
  {
    "factura": 58,
    "serie": 19,
    "exp": 2353,
    "Fe_registro": "05-26-21",
    "Domicilio": "334-6487 Dictum. ",
    "Moneda": 3,
    "Ramo": "et netus et",
    "Indole": "Lectus Cum LLP",
    "Negocio": "Eu Incorporated",
    "Cedente": "Hendrerit Consulting",
    "AsegAfian": "Lorem Ipsum Corporation",
    "Suscriptor": "Duis Sit LLC",
    "vigdesde": "10-26-20",
    "vighasta": "06-26-21",
    "estado": "arcu",
    "Nuevo": "true",
    "Usuario": "Alan",
    "Poliza": "G1Q 7T3"
  },
  {
    "factura": 59,
    "serie": 17,
    "exp": 2307,
    "Fe_registro": "10-15-20",
    "Domicilio": "Apartado núm.: 760, 8614 Leo. ",
    "Moneda": 1,
    "Ramo": "diam. Duis mi",
    "Indole": "Augue Ut Lacus Ltd",
    "Negocio": "A Consulting",
    "Cedente": "Nibh Sit Amet Consulting",
    "AsegAfian": "Aliquam Inc.",
    "Suscriptor": "Tempus Lorem Limited",
    "vigdesde": "10-06-20",
    "vighasta": "10-27-21",
    "estado": "Duis",
    "Nuevo": "false",
    "Usuario": "Kermit",
    "Poliza": "W4J 6O7"
  },
  {
    "factura": 60,
    "serie": 18,
    "exp": 2207,
    "Fe_registro": "05-23-21",
    "Domicilio": "381-5819 Mollis. Avenida",
    "Moneda": 2,
    "Ramo": "libero",
    "Indole": "Ante Maecenas Mi Foundation",
    "Negocio": "Egestas Incorporated",
    "Cedente": "Magna Suspendisse PC",
    "AsegAfian": "Id Enim Corp.",
    "Suscriptor": "Fermentum Foundation",
    "vigdesde": "02-25-20",
    "vighasta": "10-20-21",
    "estado": "egestas",
    "Nuevo": "false",
    "Usuario": "Ezra",
    "Poliza": "W4Z 9N3"
  },
  {
    "factura": 61,
    "serie": 18,
    "exp": 2257,
    "Fe_registro": "11-12-21",
    "Domicilio": "4203 Dignissim C/",
    "Moneda": 6,
    "Ramo": "non,",
    "Indole": "Erat Etiam PC",
    "Negocio": "Purus Nullam Scelerisque Corporation",
    "Cedente": "Lorem Ut LLP",
    "AsegAfian": "Porttitor Scelerisque Neque Consulting",
    "Suscriptor": "Ad Institute",
    "vigdesde": "02-03-20",
    "vighasta": "07-20-22",
    "estado": "ligula",
    "Nuevo": "false",
    "Usuario": "Drew",
    "Poliza": "A9B 7F6"
  },
  {
    "factura": 62,
    "serie": 10,
    "exp": 2359,
    "Fe_registro": "06-29-20",
    "Domicilio": "134-6349 Justo Av.",
    "Moneda": 6,
    "Ramo": "vel lectus.",
    "Indole": "Enim Ltd",
    "Negocio": "Montes Nascetur Ridiculus Associates",
    "Cedente": "Sed Incorporated",
    "AsegAfian": "In Corporation",
    "Suscriptor": "Parturient Corporation",
    "vigdesde": "09-05-20",
    "vighasta": "10-19-22",
    "estado": "auctor",
    "Nuevo": "false",
    "Usuario": "Jonas",
    "Poliza": "C4A 1D0"
  },
  {
    "factura": 63,
    "serie": 19,
    "exp": 2327,
    "Fe_registro": "12-13-20",
    "Domicilio": "Apartado núm.: 454, 4865 Fermentum Avenida",
    "Moneda": 4,
    "Ramo": "dictum. Proin",
    "Indole": "Porttitor Eros Ltd",
    "Negocio": "Duis Gravida Corporation",
    "Cedente": "Morbi Non Corporation",
    "AsegAfian": "Ridiculus Mus Associates",
    "Suscriptor": "Nam Ac Nulla LLC",
    "vigdesde": "10-28-20",
    "vighasta": "10-16-21",
    "estado": "cubilia",
    "Nuevo": "true",
    "Usuario": "Mark",
    "Poliza": "N5S 2V9"
  },
  {
    "factura": 64,
    "serie": 16,
    "exp": 2242,
    "Fe_registro": "10-15-20",
    "Domicilio": "Apartado núm.: 532, 1537 Eu, ",
    "Moneda": 5,
    "Ramo": "placerat",
    "Indole": "Interdum LLP",
    "Negocio": "Nisi Cum Sociis Ltd",
    "Cedente": "Lorem Inc.",
    "AsegAfian": "Fusce Industries",
    "Suscriptor": "Vitae Risus Duis Ltd",
    "vigdesde": "07-02-20",
    "vighasta": "10-19-21",
    "estado": "lacinia",
    "Nuevo": "true",
    "Usuario": "Hedley",
    "Poliza": "W2F 6V7"
  },
  {
    "factura": 65,
    "serie": 18,
    "exp": 2299,
    "Fe_registro": "04-25-20",
    "Domicilio": "8981 Parturient Ctra.",
    "Moneda": 3,
    "Ramo": "Sed neque. Sed",
    "Indole": "Dignissim Tempor Incorporated",
    "Negocio": "Phasellus Vitae Ltd",
    "Cedente": "In PC",
    "AsegAfian": "Metus Vivamus LLP",
    "Suscriptor": "Auctor Associates",
    "vigdesde": "10-04-20",
    "vighasta": "10-28-21",
    "estado": "lorem",
    "Nuevo": "true",
    "Usuario": "Tyler",
    "Poliza": "J1E 8O5"
  },
  {
    "factura": 66,
    "serie": 18,
    "exp": 2354,
    "Fe_registro": "09-30-20",
    "Domicilio": "365-9648 Tincidunt C.",
    "Moneda": 3,
    "Ramo": "velit.",
    "Indole": "Nullam PC",
    "Negocio": "Gravida Associates",
    "Cedente": "Congue Turpis Foundation",
    "AsegAfian": "Enim Consequat Purus Consulting",
    "Suscriptor": "Gravida Foundation",
    "vigdesde": "01-15-20",
    "vighasta": "05-20-22",
    "estado": "Cum",
    "Nuevo": "false",
    "Usuario": "Aladdin",
    "Poliza": "V2Y 4P3"
  },
  {
    "factura": 67,
    "serie": 12,
    "exp": 2343,
    "Fe_registro": "09-05-21",
    "Domicilio": "Apdo.:799-8919 Fusce Avda.",
    "Moneda": 3,
    "Ramo": "lacus. Etiam",
    "Indole": "Convallis Ante Lectus Ltd",
    "Negocio": "Lectus Rutrum Urna Company",
    "Cedente": "Duis Sit Inc.",
    "AsegAfian": "Nulla Facilisi Sed Institute",
    "Suscriptor": "Convallis Est LLP",
    "vigdesde": "07-11-20",
    "vighasta": "11-05-22",
    "estado": "Nunc",
    "Nuevo": "true",
    "Usuario": "Dorian",
    "Poliza": "U8I 9T3"
  },
  {
    "factura": 68,
    "serie": 16,
    "exp": 2300,
    "Fe_registro": "02-25-20",
    "Domicilio": "Apdo.:394-2887 Sit C.",
    "Moneda": 7,
    "Ramo": "mi.",
    "Indole": "Pellentesque A Facilisis Company",
    "Negocio": "Nisl Ltd",
    "Cedente": "Duis Company",
    "AsegAfian": "Maecenas Foundation",
    "Suscriptor": "Egestas Rhoncus Proin PC",
    "vigdesde": "11-03-20",
    "vighasta": "11-21-21",
    "estado": "convallis,",
    "Nuevo": "false",
    "Usuario": "Phillip",
    "Poliza": "B0L 8P3"
  },
  {
    "factura": 69,
    "serie": 11,
    "exp": 2212,
    "Fe_registro": "08-02-20",
    "Domicilio": "Apartado núm.: 664, 4263 In C.",
    "Moneda": 3,
    "Ramo": "nibh.",
    "Indole": "Leo Vivamus Associates",
    "Negocio": "At Limited",
    "Cedente": "Ut Inc.",
    "AsegAfian": "Ultrices Foundation",
    "Suscriptor": "Non Magna Nam Inc.",
    "vigdesde": "09-03-20",
    "vighasta": "07-08-21",
    "estado": "molestie",
    "Nuevo": "false",
    "Usuario": "Colorado",
    "Poliza": "T5J 1U6"
  },
  {
    "factura": 70,
    "serie": 19,
    "exp": 2324,
    "Fe_registro": "10-05-21",
    "Domicilio": "907-4919 Nec, Ctra.",
    "Moneda": 2,
    "Ramo": "mauris.",
    "Indole": "Convallis Company",
    "Negocio": "Dui Semper PC",
    "Cedente": "Tellus Aenean Egestas Consulting",
    "AsegAfian": "Elit Pharetra Industries",
    "Suscriptor": "Quam Foundation",
    "vigdesde": "06-25-20",
    "vighasta": "02-23-22",
    "estado": "lacinia.",
    "Nuevo": "false",
    "Usuario": "Ulysses",
    "Poliza": "Z6F 3I1"
  },
  {
    "factura": 71,
    "serie": 20,
    "exp": 2245,
    "Fe_registro": "09-30-20",
    "Domicilio": "Apartado núm.: 598, 1380 At, Carretera",
    "Moneda": 7,
    "Ramo": "fringilla euismod",
    "Indole": "Nulla Vulputate Dui Corp.",
    "Negocio": "Nulla Semper Consulting",
    "Cedente": "Neque LLP",
    "AsegAfian": "Nulla Tincidunt Neque LLC",
    "Suscriptor": "Erat Vivamus Nisi Incorporated",
    "vigdesde": "09-01-20",
    "vighasta": "05-02-21",
    "estado": "In",
    "Nuevo": "true",
    "Usuario": "Colt",
    "Poliza": "Y8P 5E9"
  },
  {
    "factura": 72,
    "serie": 15,
    "exp": 2241,
    "Fe_registro": "02-18-20",
    "Domicilio": "307-887 Ridiculus Avda.",
    "Moneda": 4,
    "Ramo": "Pellentesque",
    "Indole": "Nec Eleifend LLC",
    "Negocio": "Sollicitudin Commodo Ipsum Consulting",
    "Cedente": "Vel Mauris Integer Ltd",
    "AsegAfian": "Mauris Eu PC",
    "Suscriptor": "Luctus Vulputate Nisi Company",
    "vigdesde": "03-09-20",
    "vighasta": "06-20-21",
    "estado": "aliquet",
    "Nuevo": "false",
    "Usuario": "Blake",
    "Poliza": "Q4D 3W4"
  },
  {
    "factura": 73,
    "serie": 12,
    "exp": 2277,
    "Fe_registro": "09-07-21",
    "Domicilio": "1355 Dictum Avenida",
    "Moneda": 2,
    "Ramo": "erat",
    "Indole": "Adipiscing Elit Aliquam Associates",
    "Negocio": "A Enim Inc.",
    "Cedente": "Magnis Dis Parturient Incorporated",
    "AsegAfian": "Nulla PC",
    "Suscriptor": "Sit Amet Faucibus Corp.",
    "vigdesde": "03-16-20",
    "vighasta": "08-21-22",
    "estado": "ac",
    "Nuevo": "true",
    "Usuario": "Luke",
    "Poliza": "V6Q 4F2"
  },
  {
    "factura": 74,
    "serie": 11,
    "exp": 2228,
    "Fe_registro": "08-06-21",
    "Domicilio": "Apdo.:848-217 Facilisi. ",
    "Moneda": 5,
    "Ramo": "nibh",
    "Indole": "Aliquam Corp.",
    "Negocio": "Sem Ut Dolor Limited",
    "Cedente": "Cubilia Curae; Phasellus LLC",
    "AsegAfian": "Eu Tempor Erat Incorporated",
    "Suscriptor": "Risus Morbi Company",
    "vigdesde": "07-17-20",
    "vighasta": "08-13-21",
    "estado": "sodales",
    "Nuevo": "false",
    "Usuario": "Kareem",
    "Poliza": "G1S 2K8"
  },
  {
    "factura": 75,
    "serie": 20,
    "exp": 2290,
    "Fe_registro": "02-04-20",
    "Domicilio": "Apdo.:778-467 Suscipit Calle",
    "Moneda": 6,
    "Ramo": "rutrum magna. Cras",
    "Indole": "Amet Lorem PC",
    "Negocio": "Dolor Fusce Limited",
    "Cedente": "Pede Ac Urna Institute",
    "AsegAfian": "Dolor Quam Institute",
    "Suscriptor": "Aliquam Consulting",
    "vigdesde": "02-13-20",
    "vighasta": "10-26-21",
    "estado": "magna,",
    "Nuevo": "false",
    "Usuario": "Gage",
    "Poliza": "R0U 0F9"
  },
  {
    "factura": 76,
    "serie": 17,
    "exp": 2202,
    "Fe_registro": "01-23-20",
    "Domicilio": "3254 Ullamcorper, Avda.",
    "Moneda": 6,
    "Ramo": "mauris,",
    "Indole": "Mauris Ut Mi Foundation",
    "Negocio": "Dictum Eu Placerat Limited",
    "Cedente": "Sapien Ltd",
    "AsegAfian": "Vitae Semper Egestas Company",
    "Suscriptor": "Ante Corp.",
    "vigdesde": "10-27-20",
    "vighasta": "04-09-22",
    "estado": "conubia",
    "Nuevo": "false",
    "Usuario": "Troy",
    "Poliza": "P6V 3X9"
  },
  {
    "factura": 77,
    "serie": 13,
    "exp": 2217,
    "Fe_registro": "01-10-21",
    "Domicilio": "Apdo.:330-1162 Pellentesque. C/",
    "Moneda": 6,
    "Ramo": "Fusce",
    "Indole": "Gravida Institute",
    "Negocio": "Pede Blandit Industries",
    "Cedente": "Suspendisse Tristique LLC",
    "AsegAfian": "Nam Inc.",
    "Suscriptor": "Sed Eu Eros Corp.",
    "vigdesde": "10-29-20",
    "vighasta": "03-23-21",
    "estado": "mi",
    "Nuevo": "true",
    "Usuario": "Warren",
    "Poliza": "Q5T 4N0"
  },
  {
    "factura": 78,
    "serie": 11,
    "exp": 2243,
    "Fe_registro": "05-13-20",
    "Domicilio": "5644 Tempus, ",
    "Moneda": 2,
    "Ramo": "quam vel",
    "Indole": "Vel Mauris Industries",
    "Negocio": "Turpis Aliquam LLP",
    "Cedente": "Nunc Sit Inc.",
    "AsegAfian": "Erat Nonummy PC",
    "Suscriptor": "Integer Urna Foundation",
    "vigdesde": "01-07-20",
    "vighasta": "03-15-21",
    "estado": "euismod",
    "Nuevo": "false",
    "Usuario": "Thane",
    "Poliza": "Y3L 8J4"
  },
  {
    "factura": 79,
    "serie": 18,
    "exp": 2302,
    "Fe_registro": "02-26-21",
    "Domicilio": "564-1654 Dolor. Calle",
    "Moneda": 4,
    "Ramo": "cubilia Curae;",
    "Indole": "Blandit Congue In Foundation",
    "Negocio": "Enim Nunc Ut Ltd",
    "Cedente": "Duis Ac LLP",
    "AsegAfian": "A Sollicitudin Associates",
    "Suscriptor": "Vel LLC",
    "vigdesde": "08-05-20",
    "vighasta": "08-13-21",
    "estado": "a",
    "Nuevo": "false",
    "Usuario": "Conan",
    "Poliza": "A5U 0S3"
  },
  {
    "factura": 80,
    "serie": 11,
    "exp": 2258,
    "Fe_registro": "05-31-20",
    "Domicilio": "Apdo.:342-6279 Mauris C.",
    "Moneda": 7,
    "Ramo": "vel quam dignissim",
    "Indole": "Nunc Mauris Sapien Consulting",
    "Negocio": "Integer Vitae PC",
    "Cedente": "Duis A Industries",
    "AsegAfian": "Ac Metus LLP",
    "Suscriptor": "Lectus Industries",
    "vigdesde": "02-22-20",
    "vighasta": "06-12-22",
    "estado": "venenatis",
    "Nuevo": "false",
    "Usuario": "Rafael",
    "Poliza": "Q9E 5V5"
  },
  {
    "factura": 81,
    "serie": 15,
    "exp": 2251,
    "Fe_registro": "05-21-20",
    "Domicilio": "2919 Bibendum C/",
    "Moneda": 3,
    "Ramo": "enim",
    "Indole": "Libero Incorporated",
    "Negocio": "Enim Industries",
    "Cedente": "Sed Eget Institute",
    "AsegAfian": "Maecenas Corp.",
    "Suscriptor": "Pede Nunc Sed Corp.",
    "vigdesde": "07-24-20",
    "vighasta": "08-17-21",
    "estado": "ante.",
    "Nuevo": "true",
    "Usuario": "Orson",
    "Poliza": "X1W 3O4"
  },
  {
    "factura": 82,
    "serie": 20,
    "exp": 2317,
    "Fe_registro": "04-03-21",
    "Domicilio": "Apartado núm.: 636, 4837 Nunc Ctra.",
    "Moneda": 1,
    "Ramo": "Mauris molestie",
    "Indole": "Lectus Nullam Suscipit Associates",
    "Negocio": "Eu Institute",
    "Cedente": "Sodales Nisi PC",
    "AsegAfian": "Semper Dui Corporation",
    "Suscriptor": "A Company",
    "vigdesde": "01-03-20",
    "vighasta": "09-24-22",
    "estado": "ornare,",
    "Nuevo": "false",
    "Usuario": "Reece",
    "Poliza": "E0G 6J4"
  },
  {
    "factura": 83,
    "serie": 15,
    "exp": 2361,
    "Fe_registro": "06-21-21",
    "Domicilio": "Apdo.:422-1985 Gravida. Avenida",
    "Moneda": 6,
    "Ramo": "id, mollis nec,",
    "Indole": "Sem LLC",
    "Negocio": "Elementum At Egestas Inc.",
    "Cedente": "Elementum Corporation",
    "AsegAfian": "Est Congue A Corporation",
    "Suscriptor": "Mauris Vestibulum LLP",
    "vigdesde": "01-18-20",
    "vighasta": "07-22-21",
    "estado": "Nunc",
    "Nuevo": "false",
    "Usuario": "Dolan",
    "Poliza": "X1M 8L2"
  },
  {
    "factura": 84,
    "serie": 19,
    "exp": 2250,
    "Fe_registro": "06-29-20",
    "Domicilio": "4905 Elementum, Ctra.",
    "Moneda": 5,
    "Ramo": "sit amet",
    "Indole": "Nec Diam Duis Ltd",
    "Negocio": "Tincidunt Nibh Industries",
    "Cedente": "Feugiat Non Lobortis Industries",
    "AsegAfian": "Odio Corporation",
    "Suscriptor": "Nec Luctus Felis PC",
    "vigdesde": "12-11-20",
    "vighasta": "01-27-22",
    "estado": "risus.",
    "Nuevo": "false",
    "Usuario": "Prescott",
    "Poliza": "P3M 4J9"
  },
  {
    "factura": 85,
    "serie": 14,
    "exp": 2243,
    "Fe_registro": "05-23-20",
    "Domicilio": "Apdo.:479-840 Nec C.",
    "Moneda": 5,
    "Ramo": "mollis nec,",
    "Indole": "Massa Industries",
    "Negocio": "Quam Elementum At LLC",
    "Cedente": "Nulla Limited",
    "AsegAfian": "Enim Incorporated",
    "Suscriptor": "Dapibus LLP",
    "vigdesde": "12-26-20",
    "vighasta": "12-23-22",
    "estado": "pharetra",
    "Nuevo": "true",
    "Usuario": "Bert",
    "Poliza": "E8O 1T7"
  },
  {
    "factura": 86,
    "serie": 11,
    "exp": 2391,
    "Fe_registro": "07-08-21",
    "Domicilio": "483-5998 Metus. C.",
    "Moneda": 4,
    "Ramo": "risus. Duis a",
    "Indole": "Posuere Vulputate Lacus LLP",
    "Negocio": "Libero Proin LLC",
    "Cedente": "Vitae Orci Phasellus Limited",
    "AsegAfian": "Arcu Imperdiet Ullamcorper LLP",
    "Suscriptor": "Vulputate Risus Corp.",
    "vigdesde": "02-24-20",
    "vighasta": "04-19-22",
    "estado": "vel,",
    "Nuevo": "true",
    "Usuario": "Dane",
    "Poliza": "W5O 7Y0"
  },
  {
    "factura": 87,
    "serie": 11,
    "exp": 2215,
    "Fe_registro": "05-05-21",
    "Domicilio": "9490 Orci C.",
    "Moneda": 6,
    "Ramo": "lacinia mattis. Integer",
    "Indole": "Pellentesque Inc.",
    "Negocio": "Semper Et Lacinia Industries",
    "Cedente": "Ornare Placerat Incorporated",
    "AsegAfian": "Eget LLP",
    "Suscriptor": "Dui Quis LLP",
    "vigdesde": "07-06-20",
    "vighasta": "12-11-22",
    "estado": "nulla",
    "Nuevo": "true",
    "Usuario": "Brady",
    "Poliza": "O5T 7Y3"
  },
  {
    "factura": 88,
    "serie": 20,
    "exp": 2260,
    "Fe_registro": "04-29-21",
    "Domicilio": "1401 Gravida. ",
    "Moneda": 6,
    "Ramo": "ipsum leo elementum",
    "Indole": "Augue Sed Ltd",
    "Negocio": "Cum Company",
    "Cedente": "Mollis Lectus Ltd",
    "AsegAfian": "Lacus Vestibulum Lorem Company",
    "Suscriptor": "Risus Limited",
    "vigdesde": "02-25-20",
    "vighasta": "04-06-21",
    "estado": "eu",
    "Nuevo": "true",
    "Usuario": "Dennis",
    "Poliza": "V6I 3I7"
  },
  {
    "factura": 89,
    "serie": 10,
    "exp": 2241,
    "Fe_registro": "02-02-21",
    "Domicilio": "Apdo.:990-1369 Vivamus ",
    "Moneda": 6,
    "Ramo": "posuere",
    "Indole": "Dictum Mi Ac Ltd",
    "Negocio": "Eleifend Incorporated",
    "Cedente": "Sagittis Semper Corp.",
    "AsegAfian": "Morbi Foundation",
    "Suscriptor": "Sed Tortor Integer Foundation",
    "vigdesde": "02-07-20",
    "vighasta": "09-27-22",
    "estado": "enim.",
    "Nuevo": "false",
    "Usuario": "Ignatius",
    "Poliza": "K9N 4V8"
  },
  {
    "factura": 90,
    "serie": 10,
    "exp": 2256,
    "Fe_registro": "08-17-21",
    "Domicilio": "7993 Curabitur Avda.",
    "Moneda": 3,
    "Ramo": "adipiscing",
    "Indole": "Leo Vivamus Nibh Corp.",
    "Negocio": "Nisl Maecenas Malesuada Corporation",
    "Cedente": "Varius Nam Porttitor PC",
    "AsegAfian": "Blandit Enim Foundation",
    "Suscriptor": "Dui Consulting",
    "vigdesde": "12-30-20",
    "vighasta": "06-12-21",
    "estado": "a,",
    "Nuevo": "true",
    "Usuario": "Kevin",
    "Poliza": "X9Z 8T6"
  },
  {
    "factura": 91,
    "serie": 19,
    "exp": 2306,
    "Fe_registro": "03-22-20",
    "Domicilio": "391-413 Arcu ",
    "Moneda": 2,
    "Ramo": "quam",
    "Indole": "Tellus Foundation",
    "Negocio": "Nulla Eu Neque Limited",
    "Cedente": "Luctus Incorporated",
    "AsegAfian": "Phasellus At Foundation",
    "Suscriptor": "Arcu Inc.",
    "vigdesde": "07-10-20",
    "vighasta": "11-21-21",
    "estado": "tempor",
    "Nuevo": "false",
    "Usuario": "Amir",
    "Poliza": "R6Z 2W5"
  },
  {
    "factura": 92,
    "serie": 17,
    "exp": 2245,
    "Fe_registro": "11-17-21",
    "Domicilio": "4742 Erat Avenida",
    "Moneda": 3,
    "Ramo": "semper. Nam tempor",
    "Indole": "Natoque Penatibus Et Institute",
    "Negocio": "Sociis LLP",
    "Cedente": "Fermentum Ltd",
    "AsegAfian": "Donec Tempus Lorem Industries",
    "Suscriptor": "Morbi Consulting",
    "vigdesde": "07-22-20",
    "vighasta": "11-12-21",
    "estado": "lacinia",
    "Nuevo": "false",
    "Usuario": "Darius",
    "Poliza": "E1C 5I6"
  },
  {
    "factura": 93,
    "serie": 18,
    "exp": 2370,
    "Fe_registro": "05-23-20",
    "Domicilio": "Apdo.:788-6753 Gravida C.",
    "Moneda": 3,
    "Ramo": "et nunc. Quisque",
    "Indole": "At Limited",
    "Negocio": "Dui Semper Et PC",
    "Cedente": "Faucibus Orci Company",
    "AsegAfian": "At Arcu Industries",
    "Suscriptor": "Primis In Ltd",
    "vigdesde": "05-04-20",
    "vighasta": "12-14-21",
    "estado": "porttitor",
    "Nuevo": "false",
    "Usuario": "Christopher",
    "Poliza": "P8C 1K1"
  },
  {
    "factura": 94,
    "serie": 20,
    "exp": 2209,
    "Fe_registro": "06-13-21",
    "Domicilio": "4217 Ornare. Avda.",
    "Moneda": 6,
    "Ramo": "lectus quis",
    "Indole": "Dignissim Maecenas Corp.",
    "Negocio": "At Corp.",
    "Cedente": "Eu Neque Pellentesque Institute",
    "AsegAfian": "Nulla At Consulting",
    "Suscriptor": "Vel Lectus LLC",
    "vigdesde": "01-17-20",
    "vighasta": "12-28-21",
    "estado": "dictum",
    "Nuevo": "false",
    "Usuario": "Lamar",
    "Poliza": "M7S 1A5"
  },
  {
    "factura": 95,
    "serie": 13,
    "exp": 2327,
    "Fe_registro": "07-19-21",
    "Domicilio": "204-1198 Proin ",
    "Moneda": 6,
    "Ramo": "eu elit.",
    "Indole": "Dapibus Gravida Limited",
    "Negocio": "Cursus Ltd",
    "Cedente": "Odio Phasellus At Incorporated",
    "AsegAfian": "Sem Semper Erat Ltd",
    "Suscriptor": "Purus In Molestie Institute",
    "vigdesde": "08-30-20",
    "vighasta": "05-27-22",
    "estado": "tempus",
    "Nuevo": "false",
    "Usuario": "Dalton",
    "Poliza": "W7H 0J9"
  },
  {
    "factura": 96,
    "serie": 15,
    "exp": 2204,
    "Fe_registro": "01-07-21",
    "Domicilio": "Apdo.:683-9674 Eu, C.",
    "Moneda": 4,
    "Ramo": "ipsum. Curabitur consequat,",
    "Indole": "Ultrices Sit Amet Inc.",
    "Negocio": "Non Corporation",
    "Cedente": "Iaculis Quis Pede Limited",
    "AsegAfian": "Blandit Viverra Corporation",
    "Suscriptor": "Curabitur LLC",
    "vigdesde": "03-05-20",
    "vighasta": "02-19-21",
    "estado": "tempor",
    "Nuevo": "false",
    "Usuario": "Kermit",
    "Poliza": "Z2Y 2R4"
  },
  {
    "factura": 97,
    "serie": 12,
    "exp": 2219,
    "Fe_registro": "07-14-21",
    "Domicilio": "5104 Ligula. Ctra.",
    "Moneda": 4,
    "Ramo": "nonummy ac, feugiat",
    "Indole": "Non Bibendum Ltd",
    "Negocio": "Morbi Metus Ltd",
    "Cedente": "Vivamus Euismod Urna Limited",
    "AsegAfian": "Adipiscing Lacus Ut Inc.",
    "Suscriptor": "A Arcu Consulting",
    "vigdesde": "05-25-20",
    "vighasta": "12-06-22",
    "estado": "vitae",
    "Nuevo": "false",
    "Usuario": "Brady",
    "Poliza": "Z5F 6O8"
  },
  {
    "factura": 98,
    "serie": 20,
    "exp": 2352,
    "Fe_registro": "11-24-20",
    "Domicilio": "Apartado núm.: 781, 4702 Euismod C.",
    "Moneda": 6,
    "Ramo": "montes, nascetur ridiculus",
    "Indole": "Sagittis Nullam Vitae Foundation",
    "Negocio": "Nulla Donec Non Inc.",
    "Cedente": "Molestie Associates",
    "AsegAfian": "Nam Porttitor Scelerisque LLP",
    "Suscriptor": "Et LLP",
    "vigdesde": "01-07-20",
    "vighasta": "12-24-22",
    "estado": "dapibus",
    "Nuevo": "true",
    "Usuario": "Eaton",
    "Poliza": "O0U 9A7"
  },
  {
    "factura": 99,
    "serie": 19,
    "exp": 2321,
    "Fe_registro": "03-29-20",
    "Domicilio": "618 Luctus Ctra.",
    "Moneda": 2,
    "Ramo": "Morbi quis",
    "Indole": "Cursus Foundation",
    "Negocio": "Lorem Ipsum Sodales Consulting",
    "Cedente": "Parturient Montes Nascetur Company",
    "AsegAfian": "Eget Volutpat Ornare Foundation",
    "Suscriptor": "Facilisis Company",
    "vigdesde": "01-27-20",
    "vighasta": "11-08-22",
    "estado": "cursus",
    "Nuevo": "true",
    "Usuario": "Rahim",
    "Poliza": "E6L 6P1"
  },
  {
    "factura": 100,
    "serie": 16,
    "exp": 2297,
    "Fe_registro": "12-20-21",
    "Domicilio": "Apdo.:982-8259 Nibh ",
    "Moneda": 7,
    "Ramo": "Sed pharetra,",
    "Indole": "Cras Ltd",
    "Negocio": "Aliquam Gravida Mauris Ltd",
    "Cedente": "Et Incorporated",
    "AsegAfian": "In LLP",
    "Suscriptor": "Id Mollis Nec Corp.",
    "vigdesde": "01-30-20",
    "vighasta": "05-28-21",
    "estado": "nec",
    "Nuevo": "false",
    "Usuario": "Denton",
    "Poliza": "A6N 1L3"
  }
]

export default registro2;