const registro3 =[
  {
    factura: 1,
    serie: 19,
    exp: 2210,
    Fe_registro: "05-12-21",
    Domicilio: "Apdo.:412-7080 Sed Avda.",
    Moneda: 7,
    Ramo: "at augue id",
    Indole: "Quam Elementum At Institute",
    Negocio: "Non Bibendum Corporation",
    Cedente: "Aliquam Adipiscing Lacus LLC",
    AsegAfian: "Nisl Industries",
    Suscriptor: "Nullam Lobortis Quam Institute",
    vigdesde: "11-26-20",
    vighasta: "06-26-21",
    estado: "cursus",
    Nuevo: "false",
    Usuario: "Castor",
    Poliza: "O8Z 8Q5",
  },
  {
    factura: 2,
    serie: 11,
    exp: 2344,
    Fe_registro: "03-04-21",
    Domicilio: "Apartado núm.: 847, 9490 Pellentesque. C.",
    Moneda: 6,
    Ramo: "nibh",
    Indole: "Aliquam Ornare Institute",
    Negocio: "Metus Vivamus Euismod Corp.",
    Cedente: "Phasellus Incorporated",
    AsegAfian: "Vel Sapien LLP",
    Suscriptor: "Dolor Ltd",
    vigdesde: "10-26-20",
    vighasta: "03-24-21",
    estado: "Morbi",
    Nuevo: "true",
    Usuario: "Finn",
    Poliza: "J5C 5V3",
  },
  {
    factura: 3,
    serie: 15,
    exp: 2370,
    Fe_registro: "02-12-20",
    Domicilio: "Apdo.:655-9999 Mollis Avenida",
    Moneda: 4,
    Ramo: "id magna et",
    Indole: "Convallis Institute",
    Negocio: "Vel Mauris Integer Industries",
    Cedente: "Est Limited",
    AsegAfian: "Mi Felis Adipiscing Inc.",
    Suscriptor: "Erat Nonummy Industries",
    vigdesde: "07-21-20",
    vighasta: "11-11-22",
    estado: "diam.",
    Nuevo: "true",
    Usuario: "Denton",
    Poliza: "B9M 3E2",
  },
  {
    factura: 4,
    serie: 12,
    exp: 2218,
    Fe_registro: "06-27-20",
    Domicilio: "642-9423 Nullam Ctra.",
    Moneda: 7,
    Ramo: "a, arcu. Sed",
    Indole: "Id Foundation",
    Negocio: "Gravida Sagittis PC",
    Cedente: "Nec Euismod Incorporated",
    AsegAfian: "Tristique Industries",
    Suscriptor: "Nec Ante Blandit LLC",
    vigdesde: "08-05-20",
    vighasta: "04-04-21",
    estado: "Morbi",
    Nuevo: "false",
    Usuario: "Stuart",
    Poliza: "O6R 2K2",
  },
  {
    factura: 5,
    serie: 19,
    exp: 2288,
    Fe_registro: "07-07-21",
    Domicilio: "Apartado núm.: 656, 9301 Curabitur ",
    Moneda: 3,
    Ramo: "in consectetuer ipsum",
    Indole: "Quam Dignissim Limited",
    Negocio: "Vulputate Corp.",
    Cedente: "Elit Company",
    AsegAfian: "Tortor Integer Aliquam Inc.",
    Suscriptor: "Pharetra Limited",
    vigdesde: "03-07-20",
    vighasta: "02-11-21",
    estado: "lectus",
    Nuevo: "true",
    Usuario: "Rafael",
    Poliza: "Z6N 8L6",
  },
  {
    factura: 6,
    serie: 14,
    exp: 2327,
    Fe_registro: "06-12-20",
    Domicilio: "Apdo.:124-1859 Sagittis. C.",
    Moneda: 4,
    Ramo: "neque non",
    Indole: "Arcu Morbi Sit Ltd",
    Negocio: "Turpis LLC",
    Cedente: "Euismod Mauris Ltd",
    AsegAfian: "Rhoncus Id Industries",
    Suscriptor: "Eu Dolor LLC",
    vigdesde: "07-22-20",
    vighasta: "08-31-21",
    estado: "risus",
    Nuevo: "false",
    Usuario: "Damian",
    Poliza: "A1N 2R6",
  },
  {
    factura: 7,
    serie: 20,
    exp: 2255,
    Fe_registro: "03-03-21",
    Domicilio: "3964 Euismod Avda.",
    Moneda: 2,
    Ramo: "eleifend",
    Indole: "Ut Mi Incorporated",
    Negocio: "Mauris Suspendisse Company",
    Cedente: "Sed Institute",
    AsegAfian: "Vitae Corporation",
    Suscriptor: "Neque Et Nunc Ltd",
    vigdesde: "10-16-20",
    vighasta: "07-09-21",
    estado: "elit",
    Nuevo: "true",
    Usuario: "Nathan",
    Poliza: "F8V 7T0",
  },
  {
    factura: 8,
    serie: 16,
    exp: 2200,
    Fe_registro: "09-14-21",
    Domicilio: "Apdo.:160-8582 Nunc Calle",
    Moneda: 7,
    Ramo: "metus",
    Indole: "Luctus Lobortis LLC",
    Negocio: "Lectus Nullam PC",
    Cedente: "Nunc Consulting",
    AsegAfian: "Dui Semper Limited",
    Suscriptor: "Sit Amet Lorem Institute",
    vigdesde: "06-30-20",
    vighasta: "06-22-22",
    estado: "ante",
    Nuevo: "false",
    Usuario: "Phillip",
    Poliza: "A0J 7F8",
  },
  {
    factura: 9,
    serie: 18,
    exp: 2373,
    Fe_registro: "02-28-21",
    Domicilio: "Apartado núm.: 987, 4449 Consequat Avda.",
    Moneda: 4,
    Ramo: "Nullam vitae",
    Indole: "Libero At Limited",
    Negocio: "Egestas Fusce Associates",
    Cedente: "Lobortis Risus In Consulting",
    AsegAfian: "Risus Morbi Metus Company",
    Suscriptor: "Consectetuer Cursus Inc.",
    vigdesde: "11-18-20",
    vighasta: "12-28-21",
    estado: "mi",
    Nuevo: "true",
    Usuario: "Gareth",
    Poliza: "H6M 0X8",
  },
  {
    factura: 10,
    serie: 14,
    exp: 2351,
    Fe_registro: "02-03-20",
    Domicilio: "4017 Dictum Calle",
    Moneda: 5,
    Ramo: "lacinia vitae,",
    Indole: "Gravida Associates",
    Negocio: "Aliquam Tincidunt Corp.",
    Cedente: "Amet Massa Quisque Limited",
    AsegAfian: "Fusce Ltd",
    Suscriptor: "Malesuada Id Corporation",
    vigdesde: "10-07-20",
    vighasta: "04-27-21",
    estado: "dictum",
    Nuevo: "false",
    Usuario: "Hedley",
    Poliza: "P0P 8S3",
  },
  {
    factura: 11,
    serie: 10,
    exp: 2248,
    Fe_registro: "08-28-21",
    Domicilio: "Apartado núm.: 848, 2603 Facilisi. Carretera",
    Moneda: 4,
    Ramo: "non, sollicitudin a,",
    Indole: "Morbi Tristique Incorporated",
    Negocio: "Arcu Associates",
    Cedente: "Dui Cras Pellentesque Incorporated",
    AsegAfian: "Magna Corp.",
    Suscriptor: "Sodales PC",
    vigdesde: "01-11-20",
    vighasta: "12-02-21",
    estado: "eu",
    Nuevo: "false",
    Usuario: "Rajah",
    Poliza: "D4Q 9X3",
  },
  {
    factura: 12,
    serie: 10,
    exp: 2213,
    Fe_registro: "12-30-20",
    Domicilio: "Apartado núm.: 720, 4236 Magna. Ctra.",
    Moneda: 2,
    Ramo: "Nullam ut",
    Indole: "Vel LLP",
    Negocio: "Natoque Penatibus Limited",
    Cedente: "Dictum Phasellus Incorporated",
    AsegAfian: "Tellus Aenean Egestas LLC",
    Suscriptor: "Aenean Eget Metus Limited",
    vigdesde: "08-01-20",
    vighasta: "05-24-22",
    estado: "enim",
    Nuevo: "true",
    Usuario: "Lawrence",
    Poliza: "C4K 4G5",
  },
  {
    factura: 13,
    serie: 12,
    exp: 2349,
    Fe_registro: "12-16-21",
    Domicilio: "Apdo.:167-3465 Phasellus Carretera",
    Moneda: 7,
    Ramo: "id",
    Indole: "Nascetur Ridiculus Corporation",
    Negocio: "Nulla Foundation",
    Cedente: "Nam Ac Institute",
    AsegAfian: "Praesent Eu Dui Corporation",
    Suscriptor: "Vehicula Risus Nulla LLC",
    vigdesde: "09-05-20",
    vighasta: "12-13-22",
    estado: "sed,",
    Nuevo: "true",
    Usuario: "Bruno",
    Poliza: "A1V 1G7",
  },
  {
    factura: 14,
    serie: 15,
    exp: 2236,
    Fe_registro: "12-03-21",
    Domicilio: "Apartado núm.: 967, 229 Turpis Avenida",
    Moneda: 1,
    Ramo: "arcu. Sed eu",
    Indole: "Sapien Nunc Pulvinar Corporation",
    Negocio: "Adipiscing Elit LLP",
    Cedente: "Id Foundation",
    AsegAfian: "Facilisis Suspendisse PC",
    Suscriptor: "Lorem Inc.",
    vigdesde: "01-24-20",
    vighasta: "06-15-21",
    estado: "id,",
    Nuevo: "false",
    Usuario: "Yuli",
    Poliza: "Y0X 0L8",
  },
  {
    factura: 15,
    serie: 20,
    exp: 2217,
    Fe_registro: "09-28-21",
    Domicilio: "Apdo.:653-1710 Mattis Ctra.",
    Moneda: 6,
    Ramo: "posuere cubilia",
    Indole: "Egestas Aliquam Nec Corp.",
    Negocio: "Eu LLP",
    Cedente: "Ipsum Corporation",
    AsegAfian: "Sem Molestie Sodales Institute",
    Suscriptor: "Vitae Odio LLC",
    vigdesde: "11-18-20",
    vighasta: "09-24-22",
    estado: "dis",
    Nuevo: "false",
    Usuario: "Jerome",
    Poliza: "E6Y 2D5",
  },
  {
    factura: 16,
    serie: 13,
    exp: 2397,
    Fe_registro: "02-13-20",
    Domicilio: "Apartado núm.: 547, 3567 Risus Avenida",
    Moneda: 7,
    Ramo: "urna. Vivamus molestie",
    Indole: "Tincidunt Dui Augue Institute",
    Negocio: "Dignissim Maecenas Industries",
    Cedente: "In Condimentum Donec Consulting",
    AsegAfian: "Risus Quisque Associates",
    Suscriptor: "Cursus Vestibulum Mauris LLC",
    vigdesde: "01-25-20",
    vighasta: "11-17-21",
    estado: "sit",
    Nuevo: "false",
    Usuario: "Rafael",
    Poliza: "I4T 6N3",
  },
  {
    factura: 17,
    serie: 19,
    exp: 2381,
    Fe_registro: "10-12-21",
    Domicilio: "Apartado núm.: 284, 5853 Donec ",
    Moneda: 5,
    Ramo: "Duis",
    Indole: "Laoreet PC",
    Negocio: "Ut Sagittis LLP",
    Cedente: "Velit Sed Malesuada Institute",
    AsegAfian: "In PC",
    Suscriptor: "Varius Company",
    vigdesde: "03-01-20",
    vighasta: "11-24-21",
    estado: "Phasellus",
    Nuevo: "false",
    Usuario: "Harlan",
    Poliza: "J7A 8N0",
  },
  {
    factura: 18,
    serie: 16,
    exp: 2205,
    Fe_registro: "04-03-20",
    Domicilio: "4885 Commodo Carretera",
    Moneda: 4,
    Ramo: "non",
    Indole: "Fusce Corporation",
    Negocio: "Nulla Inc.",
    Cedente: "Lobortis Industries",
    AsegAfian: "Orci PC",
    Suscriptor: "Etiam Institute",
    vigdesde: "05-13-20",
    vighasta: "11-12-22",
    estado: "eu",
    Nuevo: "false",
    Usuario: "Arden",
    Poliza: "Z8B 4I6",
  },
  {
    factura: 19,
    serie: 13,
    exp: 2303,
    Fe_registro: "11-27-20",
    Domicilio: "274-9348 Fringilla ",
    Moneda: 6,
    Ramo: "Nullam",
    Indole: "Suspendisse Tristique Incorporated",
    Negocio: "Egestas Lacinia Institute",
    Cedente: "Nullam PC",
    AsegAfian: "Enim Mi Associates",
    Suscriptor: "Risus Quis Incorporated",
    vigdesde: "09-13-20",
    vighasta: "10-03-22",
    estado: "porttitor",
    Nuevo: "false",
    Usuario: "Josiah",
    Poliza: "S0U 8L6",
  },
  {
    factura: 20,
    serie: 15,
    exp: 2397,
    Fe_registro: "05-22-21",
    Domicilio: "Apdo.:880-4331 Purus Avenida",
    Moneda: 6,
    Ramo: "adipiscing elit. Etiam",
    Indole: "Eu Corp.",
    Negocio: "Nec Inc.",
    Cedente: "Tempor Institute",
    AsegAfian: "Integer Aliquam Ltd",
    Suscriptor: "Est Mauris Rhoncus PC",
    vigdesde: "08-02-20",
    vighasta: "02-07-21",
    estado: "amet",
    Nuevo: "true",
    Usuario: "Garrison",
    Poliza: "I2P 4G0",
  },
  {
    factura: 21,
    serie: 17,
    exp: 2364,
    Fe_registro: "09-24-21",
    Domicilio: "Apartado núm.: 225, 1808 In ",
    Moneda: 5,
    Ramo: "eleifend, nunc",
    Indole: "Sem Ut Cursus Institute",
    Negocio: "Natoque Penatibus Incorporated",
    Cedente: "Malesuada Malesuada Ltd",
    AsegAfian: "Nec Institute",
    Suscriptor: "Vitae Erat Vel PC",
    vigdesde: "03-24-20",
    vighasta: "06-11-22",
    estado: "id",
    Nuevo: "true",
    Usuario: "Edward",
    Poliza: "L9D 3C1",
  },
  {
    factura: 22,
    serie: 13,
    exp: 2220,
    Fe_registro: "03-24-21",
    Domicilio: "Apartado núm.: 701, 418 Proin Av.",
    Moneda: 2,
    Ramo: "augue. Sed",
    Indole: "Fermentum Inc.",
    Negocio: "Risus Corp.",
    Cedente: "Gravida Corp.",
    AsegAfian: "Molestie Sed Id Inc.",
    Suscriptor: "Velit Inc.",
    vigdesde: "12-21-20",
    vighasta: "01-27-22",
    estado: "odio",
    Nuevo: "true",
    Usuario: "Fulton",
    Poliza: "P5W 9I6",
  },
  {
    factura: 23,
    serie: 15,
    exp: 2398,
    Fe_registro: "05-11-21",
    Domicilio: "Apdo.:792-9476 Sed Avda.",
    Moneda: 7,
    Ramo: "convallis erat,",
    Indole: "Nec Tempus Scelerisque Inc.",
    Negocio: "Orci Industries",
    Cedente: "Ac Orci Inc.",
    AsegAfian: "Tincidunt Corporation",
    Suscriptor: "Mi Felis Corp.",
    vigdesde: "08-24-20",
    vighasta: "11-21-21",
    estado: "pede",
    Nuevo: "true",
    Usuario: "Sean",
    Poliza: "F7M 0D4",
  },
  {
    factura: 24,
    serie: 12,
    exp: 2322,
    Fe_registro: "02-15-21",
    Domicilio: "1930 Suspendisse ",
    Moneda: 6,
    Ramo: "egestas",
    Indole: "Nibh Aliquam Ornare Associates",
    Negocio: "Justo Praesent Industries",
    Cedente: "Curabitur Massa Foundation",
    AsegAfian: "Turpis LLC",
    Suscriptor: "Nulla Semper Corporation",
    vigdesde: "04-04-20",
    vighasta: "01-05-21",
    estado: "eleifend",
    Nuevo: "false",
    Usuario: "Bruno",
    Poliza: "R3J 0S4",
  },
  {
    factura: 25,
    serie: 13,
    exp: 2366,
    Fe_registro: "07-26-20",
    Domicilio: "Apdo.:533-9471 Non Carretera",
    Moneda: 6,
    Ramo: "neque sed",
    Indole: "Egestas Blandit Institute",
    Negocio: "Non Cursus Foundation",
    Cedente: "Nisi Mauris LLP",
    AsegAfian: "In Tincidunt Congue Ltd",
    Suscriptor: "Donec Tincidunt Corporation",
    vigdesde: "03-30-20",
    vighasta: "12-08-22",
    estado: "vel",
    Nuevo: "true",
    Usuario: "Ezekiel",
    Poliza: "W1X 6X8",
  },
  {
    factura: 26,
    serie: 13,
    exp: 2203,
    Fe_registro: "03-27-21",
    Domicilio: "876-9993 Aliquet C.",
    Moneda: 3,
    Ramo: "rhoncus.",
    Indole: "Sem Institute",
    Negocio: "Enim Etiam Gravida Incorporated",
    Cedente: "Elementum Company",
    AsegAfian: "Duis At Lacus Corp.",
    Suscriptor: "Vitae Ltd",
    vigdesde: "07-09-20",
    vighasta: "06-26-22",
    estado: "vel",
    Nuevo: "true",
    Usuario: "Eric",
    Poliza: "H9R 1M7",
  },
  {
    factura: 27,
    serie: 18,
    exp: 2279,
    Fe_registro: "04-10-21",
    Domicilio: "Apdo.:352-9558 Est Ctra.",
    Moneda: 1,
    Ramo: "Etiam",
    Indole: "Quam Elementum At Company",
    Negocio: "Urna Corp.",
    Cedente: "Sed LLP",
    AsegAfian: "Nec Incorporated",
    Suscriptor: "Eget LLC",
    vigdesde: "04-08-20",
    vighasta: "05-13-21",
    estado: "nec",
    Nuevo: "false",
    Usuario: "Hoyt",
    Poliza: "N8A 3S9",
  },
  {
    factura: 28,
    serie: 17,
    exp: 2293,
    Fe_registro: "07-27-21",
    Domicilio: "Apartado núm.: 463, 6707 Quam C.",
    Moneda: 6,
    Ramo: "et,",
    Indole: "Rutrum Non Hendrerit Limited",
    Negocio: "Ligula Consectetuer Corporation",
    Cedente: "Ac Institute",
    AsegAfian: "Consectetuer Rhoncus Nullam Ltd",
    Suscriptor: "Sagittis Lobortis Mauris Associates",
    vigdesde: "10-11-20",
    vighasta: "12-24-21",
    estado: "tincidunt",
    Nuevo: "true",
    Usuario: "Nigel",
    Poliza: "P5Y 6O5",
  },
  {
    factura: 29,
    serie: 19,
    exp: 2230,
    Fe_registro: "03-18-20",
    Domicilio: "Apdo.:102-8065 Pellentesque, Avenida",
    Moneda: 1,
    Ramo: "risus. Nulla",
    Indole: "Nisi Corp.",
    Negocio: "Nascetur Ridiculus Ltd",
    Cedente: "Integer Tincidunt Aliquam Limited",
    AsegAfian: "Scelerisque Neque Nullam Associates",
    Suscriptor: "Dis Parturient Inc.",
    vigdesde: "01-12-20",
    vighasta: "01-14-22",
    estado: "ac",
    Nuevo: "true",
    Usuario: "Nissim",
    Poliza: "U4Y 5O4",
  },
  {
    factura: 30,
    serie: 20,
    exp: 2223,
    Fe_registro: "02-03-21",
    Domicilio: "563-2657 Est. C/",
    Moneda: 3,
    Ramo: "ornare egestas ligula.",
    Indole: "Amet Associates",
    Negocio: "Magna Tellus LLP",
    Cedente: "Aliquam Gravida Associates",
    AsegAfian: "Ultrices Posuere Cubilia Associates",
    Suscriptor: "Porttitor Industries",
    vigdesde: "01-14-20",
    vighasta: "08-23-22",
    estado: "massa",
    Nuevo: "false",
    Usuario: "Kamal",
    Poliza: "F3Q 5B0",
  },
  {
    factura: 31,
    serie: 17,
    exp: 2225,
    Fe_registro: "06-05-21",
    Domicilio: "375-7703 Dolor Avda.",
    Moneda: 1,
    Ramo: "est ac mattis",
    Indole: "Ridiculus Mus Corp.",
    Negocio: "Mauris Industries",
    Cedente: "Inceptos Hymenaeos Foundation",
    AsegAfian: "Tempor Associates",
    Suscriptor: "Parturient Associates",
    vigdesde: "10-27-20",
    vighasta: "09-29-21",
    estado: "nonummy",
    Nuevo: "true",
    Usuario: "Garrison",
    Poliza: "B9G 0B0",
  },
  {
    factura: 32,
    serie: 10,
    exp: 2231,
    Fe_registro: "08-03-21",
    Domicilio: "721-1494 Metus C.",
    Moneda: 5,
    Ramo: "varius et, euismod",
    Indole: "Fermentum Vel Corporation",
    Negocio: "Egestas Aliquam Fringilla Foundation",
    Cedente: "Ac Orci Ut PC",
    AsegAfian: "Pulvinar Arcu LLP",
    Suscriptor: "Mauris Id Inc.",
    vigdesde: "01-08-20",
    vighasta: "10-11-21",
    estado: "diam",
    Nuevo: "false",
    Usuario: "Hoyt",
    Poliza: "S8D 6B6",
  },
  {
    factura: 33,
    serie: 10,
    exp: 2306,
    Fe_registro: "12-14-21",
    Domicilio: "Apdo.:310-8673 Imperdiet Avenida",
    Moneda: 7,
    Ramo: "sollicitudin commodo",
    Indole: "At Incorporated",
    Negocio: "Congue Institute",
    Cedente: "Rutrum Urna Nec Ltd",
    AsegAfian: "Lorem Ipsum Dolor Incorporated",
    Suscriptor: "Eu Metus Associates",
    vigdesde: "09-09-20",
    vighasta: "02-25-22",
    estado: "natoque",
    Nuevo: "false",
    Usuario: "Kenyon",
    Poliza: "L5Q 9D3",
  },
  {
    factura: 34,
    serie: 10,
    exp: 2367,
    Fe_registro: "04-29-21",
    Domicilio: "Apartado núm.: 252, 568 Posuere Avda.",
    Moneda: 4,
    Ramo: "Donec elementum,",
    Indole: "Enim Nisl Elementum Corp.",
    Negocio: "Sed Industries",
    Cedente: "Feugiat Metus LLC",
    AsegAfian: "Nec Ante Foundation",
    Suscriptor: "Vivamus Sit Consulting",
    vigdesde: "12-30-20",
    vighasta: "03-06-22",
    estado: "placerat",
    Nuevo: "true",
    Usuario: "Benedict",
    Poliza: "R5M 4N5",
  },
  {
    factura: 35,
    serie: 10,
    exp: 2344,
    Fe_registro: "09-29-21",
    Domicilio: "6880 Sed Carretera",
    Moneda: 2,
    Ramo: "Proin",
    Indole: "Mauris Corporation",
    Negocio: "Ligula Aenean Gravida Corp.",
    Cedente: "Urna Nullam Lobortis Company",
    AsegAfian: "Libero Morbi Accumsan Foundation",
    Suscriptor: "Orci Lacus LLP",
    vigdesde: "07-13-20",
    vighasta: "05-25-21",
    estado: "id",
    Nuevo: "false",
    Usuario: "Jack",
    Poliza: "X1A 9N1",
  },
  {
    factura: 36,
    serie: 16,
    exp: 2204,
    Fe_registro: "04-07-20",
    Domicilio: "4943 Luctus Avenida",
    Moneda: 3,
    Ramo: "dictum placerat, augue.",
    Indole: "Tincidunt Congue Foundation",
    Negocio: "Tellus Eu Company",
    Cedente: "Orci Sem Consulting",
    AsegAfian: "Enim LLC",
    Suscriptor: "Ac Mattis Ornare Institute",
    vigdesde: "11-25-20",
    vighasta: "04-27-22",
    estado: "sed,",
    Nuevo: "true",
    Usuario: "Magee",
    Poliza: "N8D 4R0",
  },
  {
    factura: 37,
    serie: 11,
    exp: 2253,
    Fe_registro: "06-29-20",
    Domicilio: "3022 Tempor, Carretera",
    Moneda: 1,
    Ramo: "est",
    Indole: "Proin LLC",
    Negocio: "Eu LLP",
    Cedente: "Molestie In Tempus Institute",
    AsegAfian: "Duis Dignissim Ltd",
    Suscriptor: "Enim Ltd",
    vigdesde: "04-26-20",
    vighasta: "09-25-21",
    estado: "cursus",
    Nuevo: "false",
    Usuario: "Levi",
    Poliza: "H5I 2S2",
  },
  {
    factura: 38,
    serie: 16,
    exp: 2358,
    Fe_registro: "01-18-21",
    Domicilio: "891-1940 Ut C.",
    Moneda: 2,
    Ramo: "Vivamus nibh dolor,",
    Indole: "Non Bibendum Associates",
    Negocio: "Elit Foundation",
    Cedente: "Neque Nullam Incorporated",
    AsegAfian: "Purus Corp.",
    Suscriptor: "Consequat Lectus Sit PC",
    vigdesde: "12-15-20",
    vighasta: "11-12-21",
    estado: "Ut",
    Nuevo: "false",
    Usuario: "Orlando",
    Poliza: "Z1S 5Z1",
  },
  {
    factura: 39,
    serie: 17,
    exp: 2389,
    Fe_registro: "11-27-21",
    Domicilio: "6565 Nibh. Avenida",
    Moneda: 5,
    Ramo: "semper auctor.",
    Indole: "Pharetra Sed Hendrerit Inc.",
    Negocio: "Quisque Ornare LLP",
    Cedente: "Neque Tellus Ltd",
    AsegAfian: "Pellentesque Sed LLP",
    Suscriptor: "Habitant Morbi Inc.",
    vigdesde: "04-25-20",
    vighasta: "08-05-21",
    estado: "egestas",
    Nuevo: "false",
    Usuario: "Asher",
    Poliza: "C8R 6V0",
  },
  {
    factura: 40,
    serie: 14,
    exp: 2357,
    Fe_registro: "11-04-21",
    Domicilio: "3188 Quam. C.",
    Moneda: 6,
    Ramo: "Cras vehicula",
    Indole: "Consectetuer Adipiscing Elit Corp.",
    Negocio: "Mauris Eu PC",
    Cedente: "Aliquam Arcu Associates",
    AsegAfian: "Tristique Senectus Et Limited",
    Suscriptor: "Penatibus Foundation",
    vigdesde: "02-01-20",
    vighasta: "05-07-21",
    estado: "ridiculus",
    Nuevo: "false",
    Usuario: "Amal",
    Poliza: "B3P 5T9",
  },
  {
    factura: 41,
    serie: 17,
    exp: 2237,
    Fe_registro: "03-02-20",
    Domicilio: "5225 Dui, Carretera",
    Moneda: 3,
    Ramo: "eget mollis lectus",
    Indole: "Hendrerit Consectetuer Cursus Company",
    Negocio: "Laoreet PC",
    Cedente: "Nulla Eget Metus LLC",
    AsegAfian: "Ridiculus LLP",
    Suscriptor: "Donec Fringilla PC",
    vigdesde: "08-12-20",
    vighasta: "06-29-21",
    estado: "et",
    Nuevo: "false",
    Usuario: "Lee",
    Poliza: "A9N 4G8",
  },
  {
    factura: 42,
    serie: 17,
    exp: 2348,
    Fe_registro: "06-29-21",
    Domicilio: "9136 Magnis C/",
    Moneda: 6,
    Ramo: "Cum sociis natoque",
    Indole: "Purus Sapien Industries",
    Negocio: "Pede Ultrices LLP",
    Cedente: "Egestas Foundation",
    AsegAfian: "Suspendisse Non Leo Foundation",
    Suscriptor: "Sed Corporation",
    vigdesde: "09-13-20",
    vighasta: "04-12-21",
    estado: "scelerisque",
    Nuevo: "true",
    Usuario: "Brendan",
    Poliza: "C5K 6Q8",
  },
  {
    factura: 43,
    serie: 16,
    exp: 2228,
    Fe_registro: "07-31-20",
    Domicilio: "Apartado núm.: 618, 7728 Arcu. C.",
    Moneda: 5,
    Ramo: "Nam ac nulla.",
    Indole: "Gravida Sit Amet Inc.",
    Negocio: "Dolor Donec Fringilla Foundation",
    Cedente: "Eleifend Non LLC",
    AsegAfian: "Egestas Incorporated",
    Suscriptor: "Mauris Magna Duis Associates",
    vigdesde: "05-14-20",
    vighasta: "11-16-22",
    estado: "ipsum",
    Nuevo: "true",
    Usuario: "Raymond",
    Poliza: "J1O 9J2",
  },
  {
    factura: 44,
    serie: 17,
    exp: 2305,
    Fe_registro: "02-12-21",
    Domicilio: "881 Duis Avda.",
    Moneda: 7,
    Ramo: "a ultricies",
    Indole: "Magna Praesent Corporation",
    Negocio: "Quisque Inc.",
    Cedente: "Eu Consulting",
    AsegAfian: "Augue LLP",
    Suscriptor: "Arcu Ac Orci Consulting",
    vigdesde: "06-16-20",
    vighasta: "01-27-21",
    estado: "et",
    Nuevo: "false",
    Usuario: "Herman",
    Poliza: "H7Y 9H6",
  },
  {
    factura: 45,
    serie: 16,
    exp: 2399,
    Fe_registro: "01-16-21",
    Domicilio: "4755 Lacus. Avenida",
    Moneda: 7,
    Ramo: "metus",
    Indole: "Sem Ltd",
    Negocio: "Ligula Aenean Corporation",
    Cedente: "Magna Nam Ligula Institute",
    AsegAfian: "In Nec Consulting",
    Suscriptor: "Enim Suspendisse Aliquet Company",
    vigdesde: "04-03-20",
    vighasta: "05-06-21",
    estado: "ante.",
    Nuevo: "false",
    Usuario: "Brody",
    Poliza: "P3L 4J6",
  },
  {
    factura: 46,
    serie: 12,
    exp: 2292,
    Fe_registro: "11-13-20",
    Domicilio: "Apartado núm.: 441, 7313 Sit Calle",
    Moneda: 2,
    Ramo: "pede. Nunc sed",
    Indole: "Metus LLP",
    Negocio: "Ante Limited",
    Cedente: "A Ultricies Adipiscing Foundation",
    AsegAfian: "Commodo Ipsum Suspendisse Industries",
    Suscriptor: "Odio Sagittis Corporation",
    vigdesde: "04-16-20",
    vighasta: "06-19-21",
    estado: "at,",
    Nuevo: "false",
    Usuario: "Xavier",
    Poliza: "W7G 8D1",
  },
  {
    factura: 47,
    serie: 20,
    exp: 2302,
    Fe_registro: "07-17-21",
    Domicilio: "Apartado núm.: 469, 845 Nunc Av.",
    Moneda: 4,
    Ramo: "ridiculus mus. Aenean",
    Indole: "Sed Dolor Limited",
    Negocio: "Erat LLC",
    Cedente: "Magna LLC",
    AsegAfian: "Et Rutrum Industries",
    Suscriptor: "Mi Consulting",
    vigdesde: "06-21-20",
    vighasta: "07-07-21",
    estado: "Nulla",
    Nuevo: "true",
    Usuario: "Jermaine",
    Poliza: "L1M 8C5",
  },
  {
    factura: 48,
    serie: 16,
    exp: 2212,
    Fe_registro: "09-14-21",
    Domicilio: "8290 Lobortis C.",
    Moneda: 1,
    Ramo: "felis orci,",
    Indole: "Et Ultrices Consulting",
    Negocio: "Amet Risus Donec Industries",
    Cedente: "Libero Ltd",
    AsegAfian: "Nulla Donec Non Consulting",
    Suscriptor: "Tellus Suspendisse Company",
    vigdesde: "01-10-20",
    vighasta: "04-28-21",
    estado: "mauris,",
    Nuevo: "false",
    Usuario: "Lev",
    Poliza: "E9N 2N0",
  },
  {
    factura: 49,
    serie: 11,
    exp: 2238,
    Fe_registro: "06-18-21",
    Domicilio: "Apartado núm.: 334, 2124 Vel, Ctra.",
    Moneda: 6,
    Ramo: "aliquet",
    Indole: "Lectus Cum Sociis Associates",
    Negocio: "Nisl PC",
    Cedente: "Turpis Nec Mauris Incorporated",
    AsegAfian: "Turpis Vitae Industries",
    Suscriptor: "Eget Massa Suspendisse Corporation",
    vigdesde: "06-08-20",
    vighasta: "01-07-22",
    estado: "Duis",
    Nuevo: "true",
    Usuario: "Ahmed",
    Poliza: "C8T 9R2",
  },
  {
    factura: 50,
    serie: 10,
    exp: 2351,
    Fe_registro: "01-23-20",
    Domicilio: "Apdo.:318-8006 Sociis Ctra.",
    Moneda: 4,
    Ramo: "venenatis lacus.",
    Indole: "Adipiscing Lacus Ut Incorporated",
    Negocio: "Orci Ut Sagittis Limited",
    Cedente: "Orci LLP",
    AsegAfian: "Tellus Sem Institute",
    Suscriptor: "Consectetuer Adipiscing Elit Ltd",
    vigdesde: "12-21-20",
    vighasta: "03-07-21",
    estado: "turpis",
    Nuevo: "true",
    Usuario: "Adrian",
    Poliza: "K4Y 0C7",
  },
  {
    factura: 51,
    serie: 10,
    exp: 2221,
    Fe_registro: "03-23-21",
    Domicilio: "889-7422 Dolor C/",
    Moneda: 6,
    Ramo: "elit, pretium et,",
    Indole: "Sagittis Duis Gravida PC",
    Negocio: "Massa Mauris Vestibulum Institute",
    Cedente: "Fermentum Risus Company",
    AsegAfian: "Eu Inc.",
    Suscriptor: "Adipiscing Lobortis Risus Ltd",
    vigdesde: "12-12-20",
    vighasta: "05-06-21",
    estado: "consectetuer",
    Nuevo: "false",
    Usuario: "Addison",
    Poliza: "M0I 6B1",
  },
  {
    factura: 52,
    serie: 19,
    exp: 2331,
    Fe_registro: "01-09-21",
    Domicilio: "Apartado núm.: 757, 8611 Non, C.",
    Moneda: 5,
    Ramo: "dui. Fusce aliquam,",
    Indole: "Facilisis Corporation",
    Negocio: "Ante Maecenas LLC",
    Cedente: "Sem Company",
    AsegAfian: "Aliquet Industries",
    Suscriptor: "Nullam Nisl Maecenas Industries",
    vigdesde: "10-26-20",
    vighasta: "03-11-21",
    estado: "nulla",
    Nuevo: "true",
    Usuario: "Laith",
    Poliza: "N3C 8J7",
  },
  {
    factura: 53,
    serie: 20,
    exp: 2382,
    Fe_registro: "10-09-21",
    Domicilio: "305-6028 Lobortis Carretera",
    Moneda: 1,
    Ramo: "et pede.",
    Indole: "Fusce Inc.",
    Negocio: "Imperdiet Erat Nonummy Corporation",
    Cedente: "Nec Company",
    AsegAfian: "Et Magnis Limited",
    Suscriptor: "Velit Cras Foundation",
    vigdesde: "02-15-20",
    vighasta: "03-09-22",
    estado: "Nunc",
    Nuevo: "false",
    Usuario: "Jonah",
    Poliza: "A3P 2R7",
  },
  {
    factura: 54,
    serie: 19,
    exp: 2336,
    Fe_registro: "03-24-21",
    Domicilio: "Apartado núm.: 465, 2043 Mi. Ctra.",
    Moneda: 7,
    Ramo: "urna et arcu",
    Indole: "Ante Vivamus Industries",
    Negocio: "Convallis LLC",
    Cedente: "Nibh Aliquam Consulting",
    AsegAfian: "Mi Corporation",
    Suscriptor: "Pede Nec Inc.",
    vigdesde: "12-23-20",
    vighasta: "03-13-21",
    estado: "augue",
    Nuevo: "false",
    Usuario: "Cameron",
    Poliza: "X5M 9L2",
  },
  {
    factura: 55,
    serie: 12,
    exp: 2314,
    Fe_registro: "04-27-20",
    Domicilio: "1473 Odio. Avda.",
    Moneda: 7,
    Ramo: "tortor. Integer aliquam",
    Indole: "Morbi Quis Urna Industries",
    Negocio: "Tellus Phasellus Associates",
    Cedente: "Phasellus Institute",
    AsegAfian: "A PC",
    Suscriptor: "Lorem Donec Elementum Consulting",
    vigdesde: "04-28-20",
    vighasta: "01-18-22",
    estado: "vitae,",
    Nuevo: "false",
    Usuario: "Dalton",
    Poliza: "J0D 6J2",
  },
  {
    factura: 56,
    serie: 15,
    exp: 2281,
    Fe_registro: "10-22-21",
    Domicilio: "945-9493 Dolor C.",
    Moneda: 3,
    Ramo: "in",
    Indole: "Orci PC",
    Negocio: "Molestie Dapibus Ligula PC",
    Cedente: "Commodo Inc.",
    AsegAfian: "Consectetuer Corp.",
    Suscriptor: "Vel Est Incorporated",
    vigdesde: "08-13-20",
    vighasta: "04-13-22",
    estado: "mauris",
    Nuevo: "true",
    Usuario: "Curran",
    Poliza: "L4A 5S3",
  },
  {
    factura: 57,
    serie: 12,
    exp: 2370,
    Fe_registro: "01-17-21",
    Domicilio: "244-3680 Non, Ctra.",
    Moneda: 7,
    Ramo: "Phasellus dapibus",
    Indole: "Morbi Tristique Limited",
    Negocio: "Sed Neque Sed Industries",
    Cedente: "Dis Inc.",
    AsegAfian: "Lectus Convallis Est LLC",
    Suscriptor: "A Tortor Nunc Corp.",
    vigdesde: "01-13-20",
    vighasta: "12-11-21",
    estado: "Nullam",
    Nuevo: "true",
    Usuario: "Keith",
    Poliza: "I0N 2B3",
  },
  {
    factura: 58,
    serie: 19,
    exp: 2400,
    Fe_registro: "07-01-21",
    Domicilio: "682-9654 Nullam C.",
    Moneda: 2,
    Ramo: "senectus et netus",
    Indole: "Eu Inc.",
    Negocio: "Duis Sit Ltd",
    Cedente: "Elit Aliquam Limited",
    AsegAfian: "Lorem PC",
    Suscriptor: "Nec Ltd",
    vigdesde: "04-20-20",
    vighasta: "12-23-21",
    estado: "enim",
    Nuevo: "true",
    Usuario: "Herman",
    Poliza: "W4A 8Y5",
  },
  {
    factura: 59,
    serie: 12,
    exp: 2359,
    Fe_registro: "03-31-21",
    Domicilio: "Apdo.:181-9228 Suspendisse Avda.",
    Moneda: 1,
    Ramo: "elit, a",
    Indole: "Phasellus Fermentum Foundation",
    Negocio: "Mi Tempor Lorem Associates",
    Cedente: "Varius Orci Consulting",
    AsegAfian: "Cras Inc.",
    Suscriptor: "At Iaculis Corp.",
    vigdesde: "03-10-20",
    vighasta: "04-24-21",
    estado: "quis,",
    Nuevo: "false",
    Usuario: "Charles",
    Poliza: "J7J 9Y4",
  },
  {
    factura: 60,
    serie: 12,
    exp: 2390,
    Fe_registro: "03-04-21",
    Domicilio: "Apartado núm.: 163, 3325 Neque Avda.",
    Moneda: 2,
    Ramo: "litora torquent per",
    Indole: "Velit Pellentesque Ultricies Company",
    Negocio: "Ultricies Dignissim Limited",
    Cedente: "Ante Company",
    AsegAfian: "Interdum Ligula Eu Inc.",
    Suscriptor: "Feugiat Nec Associates",
    vigdesde: "09-19-20",
    vighasta: "01-05-21",
    estado: "augue",
    Nuevo: "true",
    Usuario: "Hakeem",
    Poliza: "G2B 2R1",
  },
  {
    factura: 61,
    serie: 13,
    exp: 2360,
    Fe_registro: "08-26-20",
    Domicilio: "5480 Donec Avenida",
    Moneda: 6,
    Ramo: "tempus, lorem fringilla",
    Indole: "Sed Neque Foundation",
    Negocio: "Accumsan Ltd",
    Cedente: "Nibh Quisque Nonummy Associates",
    AsegAfian: "Porttitor Scelerisque Foundation",
    Suscriptor: "Tellus Industries",
    vigdesde: "03-02-20",
    vighasta: "10-20-21",
    estado: "malesuada",
    Nuevo: "true",
    Usuario: "Plato",
    Poliza: "V3H 8C0",
  },
  {
    factura: 62,
    serie: 19,
    exp: 2348,
    Fe_registro: "11-06-20",
    Domicilio: "Apdo.:695-8943 Nec Carretera",
    Moneda: 5,
    Ramo: "malesuada ut,",
    Indole: "Etiam LLP",
    Negocio: "Commodo Tincidunt Nibh Corp.",
    Cedente: "Ligula Nullam LLC",
    AsegAfian: "Sed Eu Consulting",
    Suscriptor: "Velit Foundation",
    vigdesde: "04-15-20",
    vighasta: "08-18-22",
    estado: "nulla.",
    Nuevo: "false",
    Usuario: "Salvador",
    Poliza: "N0D 2D8",
  },
  {
    factura: 63,
    serie: 17,
    exp: 2317,
    Fe_registro: "03-12-21",
    Domicilio: "Apartado núm.: 435, 2621 Nunc Ctra.",
    Moneda: 6,
    Ramo: "ante dictum cursus.",
    Indole: "Nam Nulla Corporation",
    Negocio: "Consectetuer Limited",
    Cedente: "Porttitor Interdum Corp.",
    AsegAfian: "Ligula Donec Foundation",
    Suscriptor: "Cras Sed Leo Foundation",
    vigdesde: "03-23-20",
    vighasta: "05-16-21",
    estado: "facilisis",
    Nuevo: "true",
    Usuario: "Kasper",
    Poliza: "B4L 0G3",
  },
  {
    factura: 64,
    serie: 18,
    exp: 2213,
    Fe_registro: "10-07-20",
    Domicilio: "398-5614 Duis Avenida",
    Moneda: 2,
    Ramo: "Donec at arcu.",
    Indole: "Nulla Eu Neque Ltd",
    Negocio: "Purus Sapien LLP",
    Cedente: "Sed Dolor Company",
    AsegAfian: "Enim Diam Vel PC",
    Suscriptor: "Metus Vivamus Euismod Inc.",
    vigdesde: "09-07-20",
    vighasta: "01-03-21",
    estado: "mi,",
    Nuevo: "false",
    Usuario: "Bruce",
    Poliza: "H1O 1G1",
  },
  {
    factura: 65,
    serie: 14,
    exp: 2358,
    Fe_registro: "08-20-20",
    Domicilio: "Apartado núm.: 267, 6865 Et Av.",
    Moneda: 5,
    Ramo: "euismod mauris",
    Indole: "Fusce Aliquet PC",
    Negocio: "Pellentesque Habitant Institute",
    Cedente: "Pretium Aliquet Company",
    AsegAfian: "Cras Dolor Dolor PC",
    Suscriptor: "Ut Eros Non Corporation",
    vigdesde: "08-01-20",
    vighasta: "12-18-22",
    estado: "purus",
    Nuevo: "true",
    Usuario: "Solomon",
    Poliza: "A7N 3C3",
  },
  {
    factura: 66,
    serie: 20,
    exp: 2322,
    Fe_registro: "06-02-20",
    Domicilio: "Apdo.:190-916 Volutpat. ",
    Moneda: 3,
    Ramo: "amet,",
    Indole: "Velit Company",
    Negocio: "Et Risus Quisque LLP",
    Cedente: "Dui Fusce Aliquam Inc.",
    AsegAfian: "Nisl Sem Consequat Industries",
    Suscriptor: "Scelerisque Consulting",
    vigdesde: "12-12-20",
    vighasta: "12-26-22",
    estado: "feugiat",
    Nuevo: "true",
    Usuario: "Vance",
    Poliza: "Z6Q 8P1",
  },
  {
    factura: 67,
    serie: 18,
    exp: 2312,
    Fe_registro: "11-27-21",
    Domicilio: "Apartado núm.: 719, 6188 A Avenida",
    Moneda: 7,
    Ramo: "ullamcorper. Duis cursus,",
    Indole: "Nisl Elementum Purus Institute",
    Negocio: "Risus LLP",
    Cedente: "Purus Industries",
    AsegAfian: "Eget Lacus LLP",
    Suscriptor: "Purus Ac Tellus Associates",
    vigdesde: "09-18-20",
    vighasta: "12-12-22",
    estado: "eu,",
    Nuevo: "true",
    Usuario: "Colton",
    Poliza: "S8C 6Q8",
  },
  {
    factura: 68,
    serie: 10,
    exp: 2286,
    Fe_registro: "09-17-21",
    Domicilio: "Apdo.:909-2013 Ultrices Carretera",
    Moneda: 2,
    Ramo: "arcu. Morbi",
    Indole: "Morbi LLC",
    Negocio: "Tempus Mauris Associates",
    Cedente: "Varius Et Corp.",
    AsegAfian: "Fermentum Vel Mauris Company",
    Suscriptor: "Egestas Sed Institute",
    vigdesde: "03-22-20",
    vighasta: "05-21-21",
    estado: "convallis",
    Nuevo: "false",
    Usuario: "Barry",
    Poliza: "A7W 5C2",
  },
  {
    factura: 69,
    serie: 12,
    exp: 2272,
    Fe_registro: "10-02-20",
    Domicilio: "Apartado núm.: 109, 8865 Mauris C/",
    Moneda: 4,
    Ramo: "pede",
    Indole: "Tincidunt Company",
    Negocio: "Pede Nunc LLC",
    Cedente: "Pharetra Nibh Limited",
    AsegAfian: "Velit LLP",
    Suscriptor: "Nibh Foundation",
    vigdesde: "12-19-20",
    vighasta: "02-18-21",
    estado: "quis",
    Nuevo: "true",
    Usuario: "Aaron",
    Poliza: "R3K 5G5",
  },
  {
    factura: 70,
    serie: 18,
    exp: 2336,
    Fe_registro: "07-13-21",
    Domicilio: "Apdo.:684-4293 Viverra. Avda.",
    Moneda: 4,
    Ramo: "sem.",
    Indole: "Euismod Mauris Eu Corp.",
    Negocio: "Suspendisse Tristique Neque LLC",
    Cedente: "Aenean Massa Integer Consulting",
    AsegAfian: "Dignissim Maecenas Ornare Associates",
    Suscriptor: "Sodales Mauris Inc.",
    vigdesde: "12-29-20",
    vighasta: "11-03-21",
    estado: "non",
    Nuevo: "false",
    Usuario: "Samson",
    Poliza: "R1H 2T2",
  },
  {
    factura: 71,
    serie: 18,
    exp: 2285,
    Fe_registro: "05-24-21",
    Domicilio: "924-9482 Malesuada Avenida",
    Moneda: 1,
    Ramo: "elit",
    Indole: "Dui Ltd",
    Negocio: "Maecenas Inc.",
    Cedente: "Leo PC",
    AsegAfian: "Sem Associates",
    Suscriptor: "Magna Lorem Corp.",
    vigdesde: "03-01-20",
    vighasta: "03-22-22",
    estado: "nibh",
    Nuevo: "true",
    Usuario: "Hiram",
    Poliza: "A5N 3V5",
  },
  {
    factura: 72,
    serie: 16,
    exp: 2215,
    Fe_registro: "09-07-20",
    Domicilio: "Apdo.:474-9196 Nisi. C/",
    Moneda: 7,
    Ramo: "et",
    Indole: "Nec Eleifend Corp.",
    Negocio: "Vulputate Posuere Company",
    Cedente: "Arcu Vestibulum Corporation",
    AsegAfian: "Eu Consulting",
    Suscriptor: "Ornare Fusce Mollis Limited",
    vigdesde: "06-05-20",
    vighasta: "02-10-22",
    estado: "fringilla",
    Nuevo: "false",
    Usuario: "Xanthus",
    Poliza: "J1D 5P1",
  },
  {
    factura: 73,
    serie: 12,
    exp: 2228,
    Fe_registro: "02-27-21",
    Domicilio: "528-2097 Libero C/",
    Moneda: 2,
    Ramo: "Duis",
    Indole: "Curabitur Egestas Industries",
    Negocio: "Dolor Sit Ltd",
    Cedente: "Praesent Luctus Curabitur Inc.",
    AsegAfian: "Nec Corp.",
    Suscriptor: "Fermentum Inc.",
    vigdesde: "08-10-20",
    vighasta: "10-08-21",
    estado: "tempor",
    Nuevo: "false",
    Usuario: "Mason",
    Poliza: "P8O 1M4",
  },
  {
    factura: 74,
    serie: 18,
    exp: 2264,
    Fe_registro: "11-19-21",
    Domicilio: "435 Eget Carretera",
    Moneda: 6,
    Ramo: "nunc nulla",
    Indole: "Lorem Lorem Luctus Incorporated",
    Negocio: "Eu Odio Incorporated",
    Cedente: "Fringilla Industries",
    AsegAfian: "Blandit At Nisi Associates",
    Suscriptor: "Ultrices Sit Amet LLC",
    vigdesde: "03-07-20",
    vighasta: "07-30-21",
    estado: "nonummy",
    Nuevo: "true",
    Usuario: "Akeem",
    Poliza: "M6Y 5X9",
  },
  {
    factura: 75,
    serie: 11,
    exp: 2281,
    Fe_registro: "04-22-21",
    Domicilio: "195 Per Calle",
    Moneda: 3,
    Ramo: "Vivamus non lorem",
    Indole: "Semper Dui Lectus Incorporated",
    Negocio: "Enim Corp.",
    Cedente: "Aliquet LLP",
    AsegAfian: "A Malesuada Id LLP",
    Suscriptor: "Leo Cras Industries",
    vigdesde: "01-07-20",
    vighasta: "10-22-22",
    estado: "enim",
    Nuevo: "false",
    Usuario: "Hamish",
    Poliza: "G8H 2T5",
  },
  {
    factura: 76,
    serie: 19,
    exp: 2332,
    Fe_registro: "11-12-20",
    Domicilio: "1340 Donec C/",
    Moneda: 5,
    Ramo: "dolor quam, elementum",
    Indole: "In Condimentum Donec Incorporated",
    Negocio: "Velit Quisque Varius Ltd",
    Cedente: "Vel Arcu Associates",
    AsegAfian: "Mauris Sagittis Placerat Ltd",
    Suscriptor: "Rutrum Lorem Limited",
    vigdesde: "09-14-20",
    vighasta: "06-09-22",
    estado: "eget",
    Nuevo: "true",
    Usuario: "Jerry",
    Poliza: "R3P 0X9",
  },
  {
    factura: 77,
    serie: 15,
    exp: 2284,
    Fe_registro: "06-05-20",
    Domicilio: "Apdo.:519-2287 Maecenas Avda.",
    Moneda: 5,
    Ramo: "malesuada",
    Indole: "Pretium Aliquet LLC",
    Negocio: "Non Institute",
    Cedente: "Morbi Accumsan Institute",
    AsegAfian: "Nunc Quisque Ltd",
    Suscriptor: "Metus Ltd",
    vigdesde: "01-05-20",
    vighasta: "08-27-21",
    estado: "sem",
    Nuevo: "false",
    Usuario: "Carson",
    Poliza: "X6M 6N8",
  },
  {
    factura: 78,
    serie: 11,
    exp: 2230,
    Fe_registro: "07-23-20",
    Domicilio: "2002 Lacus Carretera",
    Moneda: 5,
    Ramo: "lacinia vitae, sodales",
    Indole: "A Odio Semper Foundation",
    Negocio: "Montes Nascetur Ridiculus LLP",
    Cedente: "Interdum Curabitur Dictum Company",
    AsegAfian: "Nulla At Sem Ltd",
    Suscriptor: "Magna Foundation",
    vigdesde: "09-15-20",
    vighasta: "01-21-22",
    estado: "Cras",
    Nuevo: "false",
    Usuario: "Preston",
    Poliza: "Y0X 3O2",
  },
  {
    factura: 79,
    serie: 18,
    exp: 2290,
    Fe_registro: "06-25-20",
    Domicilio: "Apdo.:747-2029 Ipsum ",
    Moneda: 7,
    Ramo: "ut nisi a",
    Indole: "Duis Volutpat Nunc Consulting",
    Negocio: "Nonummy Ut Company",
    Cedente: "Cum Sociis Foundation",
    AsegAfian: "Risus Inc.",
    Suscriptor: "Vitae Erat Vivamus Industries",
    vigdesde: "10-09-20",
    vighasta: "01-05-22",
    estado: "Integer",
    Nuevo: "true",
    Usuario: "Nigel",
    Poliza: "T7M 3O8",
  },
  {
    factura: 80,
    serie: 14,
    exp: 2380,
    Fe_registro: "03-23-21",
    Domicilio: "Apartado núm.: 616, 6366 Conubia Avda.",
    Moneda: 1,
    Ramo: "elit erat",
    Indole: "Quis Pede Suspendisse Institute",
    Negocio: "Magna Et Industries",
    Cedente: "Non Dapibus Rutrum Corporation",
    AsegAfian: "At Libero Morbi Consulting",
    Suscriptor: "Sed Nec Metus LLC",
    vigdesde: "12-12-20",
    vighasta: "10-19-21",
    estado: "Sed",
    Nuevo: "false",
    Usuario: "Zahir",
    Poliza: "G6G 9M4",
  },
  {
    factura: 81,
    serie: 20,
    exp: 2239,
    Fe_registro: "01-13-20",
    Domicilio: "779-1980 Nullam Ctra.",
    Moneda: 4,
    Ramo: "eu turpis. Nulla",
    Indole: "Amet Lorem Semper Institute",
    Negocio: "Amet Consectetuer Adipiscing Foundation",
    Cedente: "At Velit Pellentesque Incorporated",
    AsegAfian: "Augue Id Ante Foundation",
    Suscriptor: "Maecenas Industries",
    vigdesde: "04-29-20",
    vighasta: "03-25-21",
    estado: "in",
    Nuevo: "false",
    Usuario: "Callum",
    Poliza: "M5Q 7Z3",
  },
  {
    factura: 82,
    serie: 10,
    exp: 2308,
    Fe_registro: "03-06-21",
    Domicilio: "Apartado núm.: 869, 2070 Mauris C.",
    Moneda: 2,
    Ramo: "ipsum",
    Indole: "Ultrices Sit Amet Consulting",
    Negocio: "Est Ac Facilisis LLP",
    Cedente: "Vitae Erat Vel Foundation",
    AsegAfian: "Cursus Integer Mollis Foundation",
    Suscriptor: "Urna Convallis Erat Corp.",
    vigdesde: "07-03-20",
    vighasta: "04-26-22",
    estado: "amet,",
    Nuevo: "false",
    Usuario: "Ali",
    Poliza: "Z9G 7C8",
  },
  {
    factura: 83,
    serie: 17,
    exp: 2276,
    Fe_registro: "08-19-21",
    Domicilio: "2758 Aliquam Calle",
    Moneda: 1,
    Ramo: "non enim",
    Indole: "Proin Institute",
    Negocio: "Consectetuer Adipiscing Limited",
    Cedente: "Est LLP",
    AsegAfian: "Purus Sapien Limited",
    Suscriptor: "Pede Industries",
    vigdesde: "08-31-20",
    vighasta: "09-10-22",
    estado: "tempor",
    Nuevo: "false",
    Usuario: "Bruce",
    Poliza: "A1J 5X9",
  },
  {
    factura: 84,
    serie: 15,
    exp: 2350,
    Fe_registro: "12-29-21",
    Domicilio: "Apartado núm.: 275, 4985 Viverra. Av.",
    Moneda: 7,
    Ramo: "eu enim.",
    Indole: "Mus Proin Associates",
    Negocio: "Lobortis LLP",
    Cedente: "Cursus Et PC",
    AsegAfian: "Laoreet Libero Industries",
    Suscriptor: "Feugiat Sed Incorporated",
    vigdesde: "11-09-20",
    vighasta: "01-12-22",
    estado: "sem",
    Nuevo: "false",
    Usuario: "Lucius",
    Poliza: "H6A 4X3",
  },
  {
    factura: 85,
    serie: 20,
    exp: 2396,
    Fe_registro: "08-13-21",
    Domicilio: "839-3981 Porttitor C.",
    Moneda: 3,
    Ramo: "et, euismod",
    Indole: "Lorem Eu Metus Corp.",
    Negocio: "Eu Arcu Morbi Ltd",
    Cedente: "Nibh Associates",
    AsegAfian: "Fringilla Purus Mauris Corporation",
    Suscriptor: "Ullamcorper Duis Cursus Incorporated",
    vigdesde: "09-20-20",
    vighasta: "03-12-21",
    estado: "Praesent",
    Nuevo: "true",
    Usuario: "David",
    Poliza: "T6B 8A4",
  },
  {
    factura: 86,
    serie: 10,
    exp: 2340,
    Fe_registro: "11-16-21",
    Domicilio: "Apdo.:836-3460 Nunc Carretera",
    Moneda: 7,
    Ramo: "non enim",
    Indole: "Integer Vitae LLC",
    Negocio: "Consequat Purus LLC",
    Cedente: "At Augue Id Ltd",
    AsegAfian: "Ipsum Phasellus Ltd",
    Suscriptor: "Risus PC",
    vigdesde: "02-24-20",
    vighasta: "11-27-21",
    estado: "Vivamus",
    Nuevo: "false",
    Usuario: "Macaulay",
    Poliza: "A7I 3J2",
  },
  {
    factura: 87,
    serie: 18,
    exp: 2252,
    Fe_registro: "11-11-20",
    Domicilio: "Apartado núm.: 150, 6784 Porttitor Ctra.",
    Moneda: 2,
    Ramo: "lectus.",
    Indole: "Lorem Ipsum Company",
    Negocio: "Parturient Montes Corporation",
    Cedente: "Enim Consequat Inc.",
    AsegAfian: "Aliquam Iaculis Ltd",
    Suscriptor: "Auctor Corporation",
    vigdesde: "12-15-20",
    vighasta: "07-28-22",
    estado: "sed",
    Nuevo: "false",
    Usuario: "Kadeem",
    Poliza: "W3A 4U8",
  },
  {
    factura: 88,
    serie: 12,
    exp: 2245,
    Fe_registro: "05-17-21",
    Domicilio: "5138 A, Avenida",
    Moneda: 5,
    Ramo: "Donec est",
    Indole: "Ornare Sagittis Felis Corporation",
    Negocio: "Erat Foundation",
    Cedente: "Est Mollis Consulting",
    AsegAfian: "Sed Corp.",
    Suscriptor: "Odio Etiam Industries",
    vigdesde: "07-01-20",
    vighasta: "02-02-21",
    estado: "eleifend.",
    Nuevo: "false",
    Usuario: "Chaney",
    Poliza: "C0K 7R8",
  },
  {
    factura: 89,
    serie: 13,
    exp: 2366,
    Fe_registro: "02-07-21",
    Domicilio: "1942 Dictum C/",
    Moneda: 6,
    Ramo: "dictum",
    Indole: "In Tincidunt LLP",
    Negocio: "Mattis Industries",
    Cedente: "Praesent Eu Associates",
    AsegAfian: "Donec Consectetuer Mauris PC",
    Suscriptor: "Etiam Imperdiet Inc.",
    vigdesde: "03-02-20",
    vighasta: "03-16-21",
    estado: "nisi",
    Nuevo: "true",
    Usuario: "Kermit",
    Poliza: "R8B 8W9",
  },
  {
    factura: 90,
    serie: 16,
    exp: 2328,
    Fe_registro: "08-14-21",
    Domicilio: "199-856 Ac Avenida",
    Moneda: 1,
    Ramo: "mauris erat eget",
    Indole: "Nulla Corp.",
    Negocio: "Nascetur Ridiculus Limited",
    Cedente: "Aliquam PC",
    AsegAfian: "Tincidunt Institute",
    Suscriptor: "Duis Sit Corporation",
    vigdesde: "01-16-20",
    vighasta: "04-09-21",
    estado: "tristique",
    Nuevo: "true",
    Usuario: "Francis",
    Poliza: "J0X 2Q3",
  },
  {
    factura: 91,
    serie: 12,
    exp: 2381,
    Fe_registro: "12-16-21",
    Domicilio: "Apdo.:435-5341 Nunc Av.",
    Moneda: 1,
    Ramo: "laoreet, libero",
    Indole: "Et Ultrices Consulting",
    Negocio: "Primis In Industries",
    Cedente: "Egestas Corporation",
    AsegAfian: "Pede Blandit Foundation",
    Suscriptor: "A Ltd",
    vigdesde: "06-06-20",
    vighasta: "12-16-22",
    estado: "fermentum",
    Nuevo: "true",
    Usuario: "Vincent",
    Poliza: "I4T 3G2",
  },
  {
    factura: 92,
    serie: 14,
    exp: 2318,
    Fe_registro: "03-14-21",
    Domicilio: "Apartado núm.: 845, 420 Purus Av.",
    Moneda: 5,
    Ramo: "mi",
    Indole: "In Corp.",
    Negocio: "Nunc Id Enim Industries",
    Cedente: "Duis Gravida Corp.",
    AsegAfian: "Et LLP",
    Suscriptor: "Neque Nullam LLC",
    vigdesde: "12-24-20",
    vighasta: "01-01-22",
    estado: "elit.",
    Nuevo: "false",
    Usuario: "Baker",
    Poliza: "B2B 7M0",
  },
  {
    factura: 93,
    serie: 11,
    exp: 2234,
    Fe_registro: "05-16-20",
    Domicilio: "7717 Nascetur Carretera",
    Moneda: 1,
    Ramo: "congue, elit sed",
    Indole: "Phasellus Corporation",
    Negocio: "Maecenas Malesuada Fringilla Company",
    Cedente: "Vivamus Sit Amet PC",
    AsegAfian: "Ornare Libero At Ltd",
    Suscriptor: "Class Aptent Taciti Ltd",
    vigdesde: "05-10-20",
    vighasta: "01-22-22",
    estado: "semper",
    Nuevo: "false",
    Usuario: "Tyler",
    Poliza: "G0R 9C9",
  },
  {
    factura: 94,
    serie: 10,
    exp: 2204,
    Fe_registro: "05-17-20",
    Domicilio: "Apartado núm.: 774, 7097 Maecenas Av.",
    Moneda: 3,
    Ramo: "pede",
    Indole: "Sed Nunc Institute",
    Negocio: "Nonummy Ac Ltd",
    Cedente: "Ac Company",
    AsegAfian: "Odio Nam Interdum Foundation",
    Suscriptor: "Turpis Associates",
    vigdesde: "01-09-20",
    vighasta: "07-20-22",
    estado: "placerat,",
    Nuevo: "false",
    Usuario: "Andrew",
    Poliza: "X3F 8M9",
  },
  {
    factura: 95,
    serie: 17,
    exp: 2354,
    Fe_registro: "01-08-21",
    Domicilio: "860-3993 Lorem ",
    Moneda: 2,
    Ramo: "augue id",
    Indole: "Lectus Associates",
    Negocio: "Sed Malesuada Limited",
    Cedente: "Curae; Company",
    AsegAfian: "A Dui Corporation",
    Suscriptor: "Aliquam Gravida Corp.",
    vigdesde: "09-30-20",
    vighasta: "08-05-22",
    estado: "enim",
    Nuevo: "false",
    Usuario: "Neil",
    Poliza: "P7G 6C6",
  },
  {
    factura: 96,
    serie: 20,
    exp: 2249,
    Fe_registro: "11-14-21",
    Domicilio: "Apartado núm.: 475, 9482 Dolor Avda.",
    Moneda: 6,
    Ramo: "ut, pellentesque",
    Indole: "In Tempus Foundation",
    Negocio: "Tincidunt Congue Turpis Associates",
    Cedente: "Ac Nulla In Company",
    AsegAfian: "Aenean Foundation",
    Suscriptor: "Enim Mi Tempor Consulting",
    vigdesde: "05-13-20",
    vighasta: "11-05-22",
    estado: "tellus",
    Nuevo: "true",
    Usuario: "Patrick",
    Poliza: "V4C 0L0",
  },
  {
    factura: 97,
    serie: 17,
    exp: 2317,
    Fe_registro: "11-20-21",
    Domicilio: "6604 Vel Calle",
    Moneda: 1,
    Ramo: "pede blandit congue.",
    Indole: "Aliquet Vel Associates",
    Negocio: "Sed Inc.",
    Cedente: "Sit Amet Company",
    AsegAfian: "Placerat Institute",
    Suscriptor: "Purus Corp.",
    vigdesde: "05-10-20",
    vighasta: "07-02-21",
    estado: "et",
    Nuevo: "false",
    Usuario: "Barrett",
    Poliza: "Q7R 2H5",
  },
  {
    factura: 98,
    serie: 14,
    exp: 2333,
    Fe_registro: "04-03-20",
    Domicilio: "549-8948 Orci, ",
    Moneda: 6,
    Ramo: "Aenean eget",
    Indole: "Cursus Et Eros Limited",
    Negocio: "Amet Corp.",
    Cedente: "Laoreet Lectus Corp.",
    AsegAfian: "Sociis Natoque Penatibus LLP",
    Suscriptor: "Duis Dignissim Tempor Corporation",
    vigdesde: "10-11-20",
    vighasta: "09-15-21",
    estado: "felis",
    Nuevo: "false",
    Usuario: "Cooper",
    Poliza: "F9Z 6S9",
  },
  {
    factura: 99,
    serie: 13,
    exp: 2296,
    Fe_registro: "03-19-21",
    Domicilio: "Apdo.:168-873 Malesuada Avda.",
    Moneda: 4,
    Ramo: "dolor vitae",
    Indole: "Massa Quisque Inc.",
    Negocio: "Lorem Ltd",
    Cedente: "Lacinia Consulting",
    AsegAfian: "Non Sollicitudin A Associates",
    Suscriptor: "Integer Sem Elit Institute",
    vigdesde: "04-01-20",
    vighasta: "10-18-22",
    estado: "tincidunt,",
    Nuevo: "false",
    Usuario: "Caleb",
    Poliza: "G4U 5I5",
  },
  {
    factura: 100,
    serie: 11,
    exp: 2304,
    Fe_registro: "09-13-21",
    Domicilio: "567-616 Metus Avenida",
    Moneda: 1,
    Ramo: "nec",
    Indole: "Vehicula Et Company",
    Negocio: "Commodo At Consulting",
    Cedente: "Enim Sit Amet Industries",
    AsegAfian: "Dictum Phasellus Associates",
    Suscriptor: "Enim Etiam LLP",
    vigdesde: "11-23-20",
    vighasta: "09-25-21",
    estado: "taciti",
    Nuevo: "true",
    Usuario: "Francis",
    Poliza: "F1A 5B1",
  },
];

export default registro3;