const registro4 =[
  {
    "factura": 1,
    "serie": 16,
    "exp": 2314,
    "Fe_registro": "11-08-20",
    "Domicilio": "Apartado núm.: 251, 7688 Mi C/",
    "Moneda": 3,
    "Ramo": "In",
    "Indole": "Aenean Corporation",
    "Negocio": "Morbi Tristique Corp.",
    "Cedente": "Lobortis Limited",
    "AsegAfian": "Accumsan Corporation",
    "Suscriptor": "Ante Foundation",
    "vigdesde": "05-14-20",
    "vighasta": "03-24-21",
    "estado": "interdum.",
    "Nuevo": "true",
    "Usuario": "Nissim",
    "Poliza": "G1S 2A5"
  },
  {
    "factura": 2,
    "serie": 12,
    "exp": 2292,
    "Fe_registro": "12-19-20",
    "Domicilio": "414-7501 Risus Ctra.",
    "Moneda": 6,
    "Ramo": "tellus",
    "Indole": "Posuere Ltd",
    "Negocio": "Auctor Odio A Corp.",
    "Cedente": "Turpis Egestas Company",
    "AsegAfian": "Blandit Enim Inc.",
    "Suscriptor": "Tempor Inc.",
    "vigdesde": "01-08-20",
    "vighasta": "06-17-21",
    "estado": "lobortis,",
    "Nuevo": "false",
    "Usuario": "Clark",
    "Poliza": "F2Q 6D5"
  },
  {
    "factura": 3,
    "serie": 20,
    "exp": 2225,
    "Fe_registro": "06-14-21",
    "Domicilio": "Apartado núm.: 508, 419 Nec Calle",
    "Moneda": 7,
    "Ramo": "tempor augue",
    "Indole": "Vehicula LLC",
    "Negocio": "Primis Consulting",
    "Cedente": "Sed Turpis Nec Consulting",
    "AsegAfian": "Cursus Integer Foundation",
    "Suscriptor": "Arcu Associates",
    "vigdesde": "07-06-20",
    "vighasta": "07-29-21",
    "estado": "luctus",
    "Nuevo": "true",
    "Usuario": "Jerry",
    "Poliza": "B3P 5J6"
  },
  {
    "factura": 4,
    "serie": 12,
    "exp": 2399,
    "Fe_registro": "09-07-20",
    "Domicilio": "124-2202 Nascetur ",
    "Moneda": 4,
    "Ramo": "commodo",
    "Indole": "Donec Dignissim Magna Company",
    "Negocio": "Congue Institute",
    "Cedente": "Cras Vulputate PC",
    "AsegAfian": "In Cursus Industries",
    "Suscriptor": "A Feugiat Consulting",
    "vigdesde": "11-02-20",
    "vighasta": "02-21-22",
    "estado": "quis,",
    "Nuevo": "true",
    "Usuario": "Kevin",
    "Poliza": "F6A 9Z8"
  },
  {
    "factura": 5,
    "serie": 15,
    "exp": 2389,
    "Fe_registro": "09-24-20",
    "Domicilio": "Apartado núm.: 581, 646 Dis C/",
    "Moneda": 6,
    "Ramo": "ullamcorper",
    "Indole": "Dui In Sodales Associates",
    "Negocio": "Risus Donec Egestas Industries",
    "Cedente": "Auctor Vitae Aliquet Consulting",
    "AsegAfian": "Donec Nibh PC",
    "Suscriptor": "Cum PC",
    "vigdesde": "03-09-20",
    "vighasta": "10-10-21",
    "estado": "egestas",
    "Nuevo": "true",
    "Usuario": "Aidan",
    "Poliza": "G7D 2F8"
  },
  {
    "factura": 6,
    "serie": 17,
    "exp": 2400,
    "Fe_registro": "09-06-21",
    "Domicilio": "3962 Praesent Avenida",
    "Moneda": 2,
    "Ramo": "aliquet odio.",
    "Indole": "Amet LLC",
    "Negocio": "Integer Sem Inc.",
    "Cedente": "Faucibus Morbi Industries",
    "AsegAfian": "Proin Eget Limited",
    "Suscriptor": "Nulla At Sem Company",
    "vigdesde": "03-15-20",
    "vighasta": "01-18-22",
    "estado": "Maecenas",
    "Nuevo": "false",
    "Usuario": "Zachery",
    "Poliza": "L1P 7U7"
  },
  {
    "factura": 7,
    "serie": 11,
    "exp": 2367,
    "Fe_registro": "04-30-21",
    "Domicilio": "806-6689 Est C.",
    "Moneda": 2,
    "Ramo": "sagittis",
    "Indole": "Neque Corp.",
    "Negocio": "Molestie Tortor LLC",
    "Cedente": "Sem Ut Cursus Inc.",
    "AsegAfian": "Ut Mi Ltd",
    "Suscriptor": "Tellus LLC",
    "vigdesde": "10-18-20",
    "vighasta": "07-13-22",
    "estado": "vitae,",
    "Nuevo": "true",
    "Usuario": "Drew",
    "Poliza": "Y2Q 1W3"
  },
  {
    "factura": 8,
    "serie": 13,
    "exp": 2356,
    "Fe_registro": "12-30-21",
    "Domicilio": "613-2367 Vivamus C/",
    "Moneda": 5,
    "Ramo": "Etiam bibendum fermentum",
    "Indole": "Phasellus Dolor Elit Limited",
    "Negocio": "Mauris Non Dui Incorporated",
    "Cedente": "Eleifend Vitae Limited",
    "AsegAfian": "Egestas Institute",
    "Suscriptor": "Natoque Penatibus Limited",
    "vigdesde": "04-06-20",
    "vighasta": "07-27-21",
    "estado": "massa",
    "Nuevo": "false",
    "Usuario": "Nolan",
    "Poliza": "N7Q 3G3"
  },
  {
    "factura": 9,
    "serie": 16,
    "exp": 2391,
    "Fe_registro": "11-15-20",
    "Domicilio": "640-3644 Laoreet Avenida",
    "Moneda": 2,
    "Ramo": "diam. Pellentesque habitant",
    "Indole": "Rutrum Eu Ultrices LLP",
    "Negocio": "Ac Turpis Egestas Industries",
    "Cedente": "Odio Sagittis Semper PC",
    "AsegAfian": "Sagittis Lobortis PC",
    "Suscriptor": "Non Vestibulum Nec Company",
    "vigdesde": "08-17-20",
    "vighasta": "05-11-22",
    "estado": "vehicula.",
    "Nuevo": "true",
    "Usuario": "Reuben",
    "Poliza": "J7Y 1J9"
  },
  {
    "factura": 10,
    "serie": 16,
    "exp": 2374,
    "Fe_registro": "04-08-20",
    "Domicilio": "915-7285 Faucibus C/",
    "Moneda": 3,
    "Ramo": "dolor.",
    "Indole": "Luctus Consulting",
    "Negocio": "Phasellus LLP",
    "Cedente": "Hymenaeos Consulting",
    "AsegAfian": "Risus Quisque Foundation",
    "Suscriptor": "Maecenas LLC",
    "vigdesde": "09-25-20",
    "vighasta": "06-03-21",
    "estado": "rutrum",
    "Nuevo": "false",
    "Usuario": "Jameson",
    "Poliza": "H6Z 7P4"
  },
  {
    "factura": 11,
    "serie": 19,
    "exp": 2222,
    "Fe_registro": "02-04-20",
    "Domicilio": "Apartado núm.: 159, 1496 Leo, Carretera",
    "Moneda": 1,
    "Ramo": "Suspendisse tristique neque",
    "Indole": "Interdum Enim LLC",
    "Negocio": "Malesuada Company",
    "Cedente": "Nisi Sem Industries",
    "AsegAfian": "Netus Et Malesuada Company",
    "Suscriptor": "Pharetra Ut Consulting",
    "vigdesde": "07-05-20",
    "vighasta": "04-01-21",
    "estado": "libero",
    "Nuevo": "false",
    "Usuario": "Odysseus",
    "Poliza": "D1S 0L5"
  },
  {
    "factura": 12,
    "serie": 10,
    "exp": 2256,
    "Fe_registro": "04-15-20",
    "Domicilio": "933-7045 Facilisis Avda.",
    "Moneda": 5,
    "Ramo": "eros nec tellus.",
    "Indole": "Nunc Mauris Corporation",
    "Negocio": "Elementum Industries",
    "Cedente": "Convallis Erat Eget Industries",
    "AsegAfian": "Ipsum PC",
    "Suscriptor": "In Foundation",
    "vigdesde": "01-04-20",
    "vighasta": "05-17-22",
    "estado": "enim",
    "Nuevo": "true",
    "Usuario": "Addison",
    "Poliza": "J6G 8O6"
  },
  {
    "factura": 13,
    "serie": 14,
    "exp": 2254,
    "Fe_registro": "08-09-20",
    "Domicilio": "3271 Quisque C/",
    "Moneda": 2,
    "Ramo": "eu",
    "Indole": "Quam A Inc.",
    "Negocio": "Nibh Dolor Associates",
    "Cedente": "Nec Luctus Consulting",
    "AsegAfian": "Sapien PC",
    "Suscriptor": "Diam Nunc Limited",
    "vigdesde": "12-21-20",
    "vighasta": "01-09-22",
    "estado": "Integer",
    "Nuevo": "false",
    "Usuario": "Kyle",
    "Poliza": "F9G 8Q4"
  },
  {
    "factura": 14,
    "serie": 13,
    "exp": 2387,
    "Fe_registro": "08-29-20",
    "Domicilio": "Apartado núm.: 788, 624 Cras C.",
    "Moneda": 2,
    "Ramo": "et, rutrum",
    "Indole": "Sociis Natoque PC",
    "Negocio": "In Faucibus Consulting",
    "Cedente": "Mauris Aliquam Incorporated",
    "AsegAfian": "Volutpat Ornare Facilisis Limited",
    "Suscriptor": "Elit PC",
    "vigdesde": "05-13-20",
    "vighasta": "11-04-21",
    "estado": "sapien",
    "Nuevo": "false",
    "Usuario": "Damian",
    "Poliza": "S1A 7S9"
  },
  {
    "factura": 15,
    "serie": 13,
    "exp": 2327,
    "Fe_registro": "06-16-20",
    "Domicilio": "176-3886 Quam. Ctra.",
    "Moneda": 5,
    "Ramo": "Vestibulum accumsan neque",
    "Indole": "Semper Rutrum Fusce Company",
    "Negocio": "Nibh Incorporated",
    "Cedente": "Mattis Associates",
    "AsegAfian": "Libero Morbi PC",
    "Suscriptor": "Pellentesque Habitant Company",
    "vigdesde": "03-04-20",
    "vighasta": "07-01-22",
    "estado": "ac",
    "Nuevo": "false",
    "Usuario": "Francis",
    "Poliza": "S7X 4G9"
  },
  {
    "factura": 16,
    "serie": 17,
    "exp": 2289,
    "Fe_registro": "09-07-21",
    "Domicilio": "1525 Sed C.",
    "Moneda": 7,
    "Ramo": "vitae",
    "Indole": "Vestibulum Neque Sed Limited",
    "Negocio": "Facilisis Magna Tellus LLC",
    "Cedente": "Fringilla Est Foundation",
    "AsegAfian": "Sed Orci Lobortis Institute",
    "Suscriptor": "Mollis Lectus LLP",
    "vigdesde": "11-18-20",
    "vighasta": "12-18-22",
    "estado": "et,",
    "Nuevo": "false",
    "Usuario": "Mufutau",
    "Poliza": "Y8I 9T4"
  },
  {
    "factura": 17,
    "serie": 17,
    "exp": 2342,
    "Fe_registro": "03-29-20",
    "Domicilio": "Apdo.:502-2756 Placerat, Ctra.",
    "Moneda": 7,
    "Ramo": "id, erat.",
    "Indole": "Nonummy Ultricies PC",
    "Negocio": "Varius Corp.",
    "Cedente": "Quisque Varius Ltd",
    "AsegAfian": "Eget Company",
    "Suscriptor": "Tellus LLC",
    "vigdesde": "03-23-20",
    "vighasta": "11-21-21",
    "estado": "Mauris",
    "Nuevo": "true",
    "Usuario": "Burke",
    "Poliza": "N1L 0S8"
  },
  {
    "factura": 18,
    "serie": 19,
    "exp": 2240,
    "Fe_registro": "09-11-21",
    "Domicilio": "3128 Pellentesque Ctra.",
    "Moneda": 3,
    "Ramo": "Fusce aliquam,",
    "Indole": "Ante Vivamus Non Foundation",
    "Negocio": "Mauris Company",
    "Cedente": "Ut Corp.",
    "AsegAfian": "Elit Company",
    "Suscriptor": "Phasellus Nulla Integer Consulting",
    "vigdesde": "02-13-20",
    "vighasta": "11-19-21",
    "estado": "consectetuer",
    "Nuevo": "false",
    "Usuario": "Amal",
    "Poliza": "P8A 9H4"
  },
  {
    "factura": 19,
    "serie": 15,
    "exp": 2335,
    "Fe_registro": "11-16-20",
    "Domicilio": "Apdo.:904-7309 Commodo Carretera",
    "Moneda": 4,
    "Ramo": "turpis non enim.",
    "Indole": "In Dolor Fusce Incorporated",
    "Negocio": "Vitae Posuere At Limited",
    "Cedente": "Leo Morbi LLC",
    "AsegAfian": "Duis Corp.",
    "Suscriptor": "Eu Inc.",
    "vigdesde": "07-02-20",
    "vighasta": "09-07-22",
    "estado": "mi",
    "Nuevo": "false",
    "Usuario": "Lane",
    "Poliza": "J4G 1U4"
  },
  {
    "factura": 20,
    "serie": 14,
    "exp": 2299,
    "Fe_registro": "12-21-21",
    "Domicilio": "Apdo.:175-9300 Orci ",
    "Moneda": 4,
    "Ramo": "eget",
    "Indole": "Nulla Ltd",
    "Negocio": "Enim PC",
    "Cedente": "Eu Industries",
    "AsegAfian": "Tellus Imperdiet Non PC",
    "Suscriptor": "Fusce Mi Lorem LLC",
    "vigdesde": "08-28-20",
    "vighasta": "03-28-22",
    "estado": "ultrices.",
    "Nuevo": "false",
    "Usuario": "Wallace",
    "Poliza": "T4U 9T6"
  },
  {
    "factura": 21,
    "serie": 15,
    "exp": 2281,
    "Fe_registro": "08-14-20",
    "Domicilio": "Apartado núm.: 681, 8144 Molestie C/",
    "Moneda": 7,
    "Ramo": "dui lectus",
    "Indole": "Nulla Interdum Curabitur Consulting",
    "Negocio": "Enim LLC",
    "Cedente": "Ac PC",
    "AsegAfian": "Donec Corporation",
    "Suscriptor": "Hymenaeos Mauris Ut Incorporated",
    "vigdesde": "08-01-20",
    "vighasta": "02-04-22",
    "estado": "sem",
    "Nuevo": "true",
    "Usuario": "Micah",
    "Poliza": "J7E 9K3"
  },
  {
    "factura": 22,
    "serie": 14,
    "exp": 2313,
    "Fe_registro": "11-16-21",
    "Domicilio": "Apdo.:149-8774 Aliquam ",
    "Moneda": 6,
    "Ramo": "metus. In nec",
    "Indole": "Arcu Ac Foundation",
    "Negocio": "Arcu Nunc Foundation",
    "Cedente": "Amet Nulla PC",
    "AsegAfian": "Amet Diam Eu Foundation",
    "Suscriptor": "Consequat Purus Consulting",
    "vigdesde": "01-10-20",
    "vighasta": "07-12-22",
    "estado": "Ut",
    "Nuevo": "true",
    "Usuario": "Edan",
    "Poliza": "D0Q 5D6"
  },
  {
    "factura": 23,
    "serie": 14,
    "exp": 2394,
    "Fe_registro": "12-29-20",
    "Domicilio": "Apdo.:604-4943 Gravida Avenida",
    "Moneda": 1,
    "Ramo": "non",
    "Indole": "Lacus Corp.",
    "Negocio": "Dapibus Id Industries",
    "Cedente": "Sollicitudin Orci Incorporated",
    "AsegAfian": "Ligula Aliquam LLC",
    "Suscriptor": "Aliquet Libero Institute",
    "vigdesde": "10-11-20",
    "vighasta": "05-25-21",
    "estado": "Sed",
    "Nuevo": "false",
    "Usuario": "Acton",
    "Poliza": "H4V 9B2"
  },
  {
    "factura": 24,
    "serie": 11,
    "exp": 2293,
    "Fe_registro": "01-12-20",
    "Domicilio": "200-3399 Laoreet, C/",
    "Moneda": 1,
    "Ramo": "facilisis facilisis,",
    "Indole": "Diam Nunc PC",
    "Negocio": "Curae; Associates",
    "Cedente": "Phasellus Fermentum Company",
    "AsegAfian": "Scelerisque Sed Associates",
    "Suscriptor": "Nibh LLC",
    "vigdesde": "08-20-20",
    "vighasta": "08-31-21",
    "estado": "hendrerit",
    "Nuevo": "false",
    "Usuario": "Jesse",
    "Poliza": "G9F 1I1"
  },
  {
    "factura": 25,
    "serie": 12,
    "exp": 2204,
    "Fe_registro": "03-06-20",
    "Domicilio": "112-1414 Habitant Carretera",
    "Moneda": 6,
    "Ramo": "vestibulum, neque",
    "Indole": "Mollis Non Cursus Incorporated",
    "Negocio": "Vestibulum Limited",
    "Cedente": "Ornare Sagittis Felis PC",
    "AsegAfian": "Felis Donec Limited",
    "Suscriptor": "Aliquet Libero Integer Incorporated",
    "vigdesde": "02-07-20",
    "vighasta": "09-11-21",
    "estado": "velit",
    "Nuevo": "true",
    "Usuario": "Armand",
    "Poliza": "Z1H 1Y4"
  },
  {
    "factura": 26,
    "serie": 12,
    "exp": 2302,
    "Fe_registro": "09-03-20",
    "Domicilio": "Apartado núm.: 520, 735 Mollis Calle",
    "Moneda": 7,
    "Ramo": "Duis risus odio,",
    "Indole": "Ac Corporation",
    "Negocio": "Lobortis Associates",
    "Cedente": "Nunc Mauris Industries",
    "AsegAfian": "Gravida Sit Amet Incorporated",
    "Suscriptor": "Lacinia Orci Company",
    "vigdesde": "12-09-20",
    "vighasta": "10-24-22",
    "estado": "Ut",
    "Nuevo": "false",
    "Usuario": "Slade",
    "Poliza": "B4O 3G9"
  },
  {
    "factura": 27,
    "serie": 16,
    "exp": 2274,
    "Fe_registro": "01-28-20",
    "Domicilio": "136-6733 Hendrerit Avda.",
    "Moneda": 2,
    "Ramo": "et risus.",
    "Indole": "Vel Sapien Foundation",
    "Negocio": "Donec Fringilla Foundation",
    "Cedente": "Eu Ltd",
    "AsegAfian": "Pellentesque Eget Associates",
    "Suscriptor": "Eget Ltd",
    "vigdesde": "12-05-20",
    "vighasta": "07-25-21",
    "estado": "quis,",
    "Nuevo": "false",
    "Usuario": "Jakeem",
    "Poliza": "X5H 4E3"
  },
  {
    "factura": 28,
    "serie": 20,
    "exp": 2255,
    "Fe_registro": "05-17-21",
    "Domicilio": "Apdo.:848-3369 Sed Carretera",
    "Moneda": 2,
    "Ramo": "sed sem",
    "Indole": "Nascetur Ridiculus Mus Inc.",
    "Negocio": "Ipsum Suspendisse Non Consulting",
    "Cedente": "Nulla Consulting",
    "AsegAfian": "Eget Dictum Foundation",
    "Suscriptor": "In Corporation",
    "vigdesde": "12-18-20",
    "vighasta": "02-28-21",
    "estado": "dolor.",
    "Nuevo": "false",
    "Usuario": "Kenyon",
    "Poliza": "W0X 0W6"
  },
  {
    "factura": 29,
    "serie": 11,
    "exp": 2256,
    "Fe_registro": "02-11-20",
    "Domicilio": "651-2644 Commodo Avda.",
    "Moneda": 3,
    "Ramo": "purus,",
    "Indole": "Arcu PC",
    "Negocio": "Vulputate Posuere LLC",
    "Cedente": "Aliquam Erat Consulting",
    "AsegAfian": "Dui Ltd",
    "Suscriptor": "Velit Ltd",
    "vigdesde": "06-03-20",
    "vighasta": "06-24-22",
    "estado": "nec,",
    "Nuevo": "true",
    "Usuario": "Nathan",
    "Poliza": "T4K 5S6"
  },
  {
    "factura": 30,
    "serie": 10,
    "exp": 2379,
    "Fe_registro": "07-05-20",
    "Domicilio": "Apdo.:122-9973 Urna Ctra.",
    "Moneda": 2,
    "Ramo": "ultricies sem magna",
    "Indole": "Porttitor Interdum Foundation",
    "Negocio": "Etiam Ligula Tortor LLP",
    "Cedente": "Vitae Foundation",
    "AsegAfian": "Nunc Sollicitudin LLP",
    "Suscriptor": "Eget Laoreet Industries",
    "vigdesde": "04-30-20",
    "vighasta": "05-15-21",
    "estado": "leo.",
    "Nuevo": "true",
    "Usuario": "Aladdin",
    "Poliza": "B6F 5G4"
  },
  {
    "factura": 31,
    "serie": 15,
    "exp": 2309,
    "Fe_registro": "10-16-21",
    "Domicilio": "9651 Sagittis. Carretera",
    "Moneda": 3,
    "Ramo": "commodo",
    "Indole": "Dictum Cursus Company",
    "Negocio": "Orci Luctus Et Corp.",
    "Cedente": "Nunc In At Industries",
    "AsegAfian": "Varius Ultrices Corp.",
    "Suscriptor": "Hendrerit Limited",
    "vigdesde": "03-22-20",
    "vighasta": "10-29-21",
    "estado": "quam",
    "Nuevo": "true",
    "Usuario": "Griffith",
    "Poliza": "W1R 5V1"
  },
  {
    "factura": 32,
    "serie": 18,
    "exp": 2281,
    "Fe_registro": "11-26-21",
    "Domicilio": "Apartado núm.: 509, 4051 Tellus C.",
    "Moneda": 6,
    "Ramo": "auctor quis,",
    "Indole": "Rutrum Justo Praesent Corporation",
    "Negocio": "Eget Volutpat Company",
    "Cedente": "Pellentesque Habitant Morbi Company",
    "AsegAfian": "Dictum Company",
    "Suscriptor": "Tempus Mauris Consulting",
    "vigdesde": "01-11-20",
    "vighasta": "03-19-21",
    "estado": "feugiat",
    "Nuevo": "true",
    "Usuario": "Dolan",
    "Poliza": "B0W 8Y8"
  },
  {
    "factura": 33,
    "serie": 15,
    "exp": 2276,
    "Fe_registro": "04-26-20",
    "Domicilio": "Apartado núm.: 731, 1673 Lectus. Avenida",
    "Moneda": 2,
    "Ramo": "sollicitudin",
    "Indole": "Et Rutrum Non Ltd",
    "Negocio": "Aliquet Limited",
    "Cedente": "Vitae Corporation",
    "AsegAfian": "Arcu Imperdiet Associates",
    "Suscriptor": "Non PC",
    "vigdesde": "12-07-20",
    "vighasta": "05-28-22",
    "estado": "Nulla",
    "Nuevo": "true",
    "Usuario": "Brody",
    "Poliza": "B5W 8F4"
  },
  {
    "factura": 34,
    "serie": 13,
    "exp": 2292,
    "Fe_registro": "10-31-21",
    "Domicilio": "562-7342 Accumsan Avda.",
    "Moneda": 2,
    "Ramo": "arcu.",
    "Indole": "Natoque Inc.",
    "Negocio": "Aliquam Auctor Ltd",
    "Cedente": "Vivamus Euismod Institute",
    "AsegAfian": "Neque Tellus Imperdiet Industries",
    "Suscriptor": "Vitae Aliquet Nec LLP",
    "vigdesde": "08-23-20",
    "vighasta": "03-03-22",
    "estado": "tempor",
    "Nuevo": "true",
    "Usuario": "Hoyt",
    "Poliza": "U8W 2G5"
  },
  {
    "factura": 35,
    "serie": 16,
    "exp": 2290,
    "Fe_registro": "08-23-21",
    "Domicilio": "Apartado núm.: 260, 5176 Vestibulum, Av.",
    "Moneda": 3,
    "Ramo": "mauris. Integer",
    "Indole": "Accumsan Incorporated",
    "Negocio": "Aliquam Nec Enim Industries",
    "Cedente": "Cras Eget Nisi Company",
    "AsegAfian": "Morbi Tristique Institute",
    "Suscriptor": "Pede LLP",
    "vigdesde": "07-06-20",
    "vighasta": "03-09-22",
    "estado": "ligula.",
    "Nuevo": "false",
    "Usuario": "Nathaniel",
    "Poliza": "U8Q 6Z3"
  },
  {
    "factura": 36,
    "serie": 18,
    "exp": 2323,
    "Fe_registro": "09-12-20",
    "Domicilio": "Apartado núm.: 580, 8279 Augue ",
    "Moneda": 3,
    "Ramo": "malesuada fames ac",
    "Indole": "Tellus Suspendisse Corp.",
    "Negocio": "Fringilla Corporation",
    "Cedente": "Fringilla Donec PC",
    "AsegAfian": "Vulputate Consulting",
    "Suscriptor": "Luctus LLC",
    "vigdesde": "10-25-20",
    "vighasta": "04-04-22",
    "estado": "consectetuer,",
    "Nuevo": "true",
    "Usuario": "Armand",
    "Poliza": "A7M 8U0"
  },
  {
    "factura": 37,
    "serie": 15,
    "exp": 2365,
    "Fe_registro": "06-07-20",
    "Domicilio": "Apdo.:407-3452 Elementum ",
    "Moneda": 2,
    "Ramo": "fringilla",
    "Indole": "Eget Nisi Dictum Associates",
    "Negocio": "Nulla Aliquet Foundation",
    "Cedente": "Ac Metus Industries",
    "AsegAfian": "Mollis LLC",
    "Suscriptor": "Tempor Augue Ac PC",
    "vigdesde": "05-01-20",
    "vighasta": "12-11-21",
    "estado": "Integer",
    "Nuevo": "true",
    "Usuario": "Mufutau",
    "Poliza": "V9I 8O6"
  },
  {
    "factura": 38,
    "serie": 14,
    "exp": 2268,
    "Fe_registro": "05-13-20",
    "Domicilio": "Apdo.:279-6465 Ut Carretera",
    "Moneda": 7,
    "Ramo": "Pellentesque",
    "Indole": "Diam LLP",
    "Negocio": "Sed Consulting",
    "Cedente": "Sollicitudin Adipiscing Ligula Limited",
    "AsegAfian": "Suspendisse Dui Incorporated",
    "Suscriptor": "Dui Nec PC",
    "vigdesde": "04-28-20",
    "vighasta": "03-24-21",
    "estado": "orci",
    "Nuevo": "true",
    "Usuario": "Eaton",
    "Poliza": "T3U 0J3"
  },
  {
    "factura": 39,
    "serie": 10,
    "exp": 2246,
    "Fe_registro": "07-17-21",
    "Domicilio": "Apartado núm.: 520, 9368 Consequat Av.",
    "Moneda": 3,
    "Ramo": "pharetra. Nam",
    "Indole": "Turpis Vitae Industries",
    "Negocio": "Lectus Rutrum Consulting",
    "Cedente": "Ante Associates",
    "AsegAfian": "Amet Consectetuer Adipiscing Industries",
    "Suscriptor": "Eu Eleifend Institute",
    "vigdesde": "04-29-20",
    "vighasta": "03-13-21",
    "estado": "malesuada",
    "Nuevo": "false",
    "Usuario": "Zachary",
    "Poliza": "Y7H 3T7"
  },
  {
    "factura": 40,
    "serie": 10,
    "exp": 2362,
    "Fe_registro": "08-29-20",
    "Domicilio": "Apartado núm.: 523, 329 Sed Av.",
    "Moneda": 6,
    "Ramo": "commodo at, libero.",
    "Indole": "Enim Mi Incorporated",
    "Negocio": "Eget Varius Ultrices Company",
    "Cedente": "Nulla At Sem Incorporated",
    "AsegAfian": "Ante Lectus Corp.",
    "Suscriptor": "Quam Corp.",
    "vigdesde": "03-04-20",
    "vighasta": "06-19-21",
    "estado": "Lorem",
    "Nuevo": "false",
    "Usuario": "Phelan",
    "Poliza": "T7Y 8F0"
  },
  {
    "factura": 41,
    "serie": 12,
    "exp": 2280,
    "Fe_registro": "06-18-21",
    "Domicilio": "907-2401 Non, Avenida",
    "Moneda": 6,
    "Ramo": "non massa non",
    "Indole": "Sed Pede Corporation",
    "Negocio": "Et Nunc Quisque Limited",
    "Cedente": "Vitae Diam Proin Industries",
    "AsegAfian": "Risus Donec Corporation",
    "Suscriptor": "Ipsum Foundation",
    "vigdesde": "07-31-20",
    "vighasta": "02-13-22",
    "estado": "sodales.",
    "Nuevo": "true",
    "Usuario": "Akeem",
    "Poliza": "Z2L 0J3"
  },
  {
    "factura": 42,
    "serie": 19,
    "exp": 2287,
    "Fe_registro": "03-17-20",
    "Domicilio": "948-9328 Ac, C/",
    "Moneda": 5,
    "Ramo": "id,",
    "Indole": "In Consequat Industries",
    "Negocio": "Luctus Ipsum Ltd",
    "Cedente": "Proin Ltd",
    "AsegAfian": "Dolor Company",
    "Suscriptor": "Parturient Montes Corporation",
    "vigdesde": "09-19-20",
    "vighasta": "05-05-21",
    "estado": "erat",
    "Nuevo": "true",
    "Usuario": "Clark",
    "Poliza": "H2I 3J0"
  },
  {
    "factura": 43,
    "serie": 17,
    "exp": 2301,
    "Fe_registro": "07-22-21",
    "Domicilio": "Apartado núm.: 222, 2124 Leo. ",
    "Moneda": 5,
    "Ramo": "iaculis",
    "Indole": "Magna Praesent Interdum Corporation",
    "Negocio": "Tincidunt Nibh Phasellus LLP",
    "Cedente": "Lectus Sit Amet Industries",
    "AsegAfian": "Eu Inc.",
    "Suscriptor": "Phasellus At Augue Consulting",
    "vigdesde": "08-21-20",
    "vighasta": "05-05-22",
    "estado": "orci,",
    "Nuevo": "true",
    "Usuario": "Gavin",
    "Poliza": "D9N 1V5"
  },
  {
    "factura": 44,
    "serie": 14,
    "exp": 2368,
    "Fe_registro": "05-23-21",
    "Domicilio": "874-4626 Eget Calle",
    "Moneda": 1,
    "Ramo": "nec enim.",
    "Indole": "Sit Amet Risus Institute",
    "Negocio": "Diam Sed Diam Associates",
    "Cedente": "At Consulting",
    "AsegAfian": "Elit Elit Industries",
    "Suscriptor": "Mollis Duis Foundation",
    "vigdesde": "11-11-20",
    "vighasta": "07-05-22",
    "estado": "porttitor",
    "Nuevo": "false",
    "Usuario": "Gage",
    "Poliza": "O8O 1N8"
  },
  {
    "factura": 45,
    "serie": 19,
    "exp": 2313,
    "Fe_registro": "08-07-20",
    "Domicilio": "340-9981 In Avenida",
    "Moneda": 7,
    "Ramo": "diam. Duis",
    "Indole": "Tortor Integer Foundation",
    "Negocio": "Ante Maecenas Mi Inc.",
    "Cedente": "Ut Sagittis Inc.",
    "AsegAfian": "Eu Eros Nam Consulting",
    "Suscriptor": "Quis Foundation",
    "vigdesde": "07-26-20",
    "vighasta": "02-02-22",
    "estado": "dolor.",
    "Nuevo": "true",
    "Usuario": "Caesar",
    "Poliza": "L1K 5X2"
  },
  {
    "factura": 46,
    "serie": 12,
    "exp": 2356,
    "Fe_registro": "01-06-21",
    "Domicilio": "932-6329 In Av.",
    "Moneda": 5,
    "Ramo": "Aenean euismod",
    "Indole": "Vel Faucibus Id Ltd",
    "Negocio": "Ante Dictum Inc.",
    "Cedente": "Elit A Limited",
    "AsegAfian": "Cursus In Hendrerit Corporation",
    "Suscriptor": "Elit Ltd",
    "vigdesde": "10-13-20",
    "vighasta": "02-19-21",
    "estado": "porttitor",
    "Nuevo": "false",
    "Usuario": "Stephen",
    "Poliza": "L0G 1X2"
  },
  {
    "factura": 47,
    "serie": 10,
    "exp": 2380,
    "Fe_registro": "02-21-21",
    "Domicilio": "Apdo.:428-7544 Augue C/",
    "Moneda": 6,
    "Ramo": "gravida sit",
    "Indole": "Sit Ltd",
    "Negocio": "Vel Faucibus Id Corp.",
    "Cedente": "Ullamcorper Duis Ltd",
    "AsegAfian": "Lacinia Orci Consectetuer Ltd",
    "Suscriptor": "Ante Ipsum Limited",
    "vigdesde": "06-19-20",
    "vighasta": "07-03-22",
    "estado": "nec",
    "Nuevo": "true",
    "Usuario": "Elton",
    "Poliza": "G5Y 6I3"
  },
  {
    "factura": 48,
    "serie": 19,
    "exp": 2390,
    "Fe_registro": "07-23-21",
    "Domicilio": "Apartado núm.: 417, 9469 Tincidunt C.",
    "Moneda": 1,
    "Ramo": "Aliquam",
    "Indole": "Adipiscing Fringilla Porttitor Inc.",
    "Negocio": "Aliquam Adipiscing Corporation",
    "Cedente": "Aliquam Vulputate Ullamcorper Inc.",
    "AsegAfian": "Curae; Donec Tincidunt LLC",
    "Suscriptor": "Nisi Cum Sociis Inc.",
    "vigdesde": "11-23-20",
    "vighasta": "12-18-22",
    "estado": "malesuada",
    "Nuevo": "true",
    "Usuario": "Nicholas",
    "Poliza": "U1N 8A4"
  },
  {
    "factura": 49,
    "serie": 16,
    "exp": 2400,
    "Fe_registro": "04-25-21",
    "Domicilio": "706-9035 Vehicula C.",
    "Moneda": 7,
    "Ramo": "nisi",
    "Indole": "Phasellus At Augue LLC",
    "Negocio": "Penatibus Et LLC",
    "Cedente": "Sem Semper Corporation",
    "AsegAfian": "Vestibulum Company",
    "Suscriptor": "Felis LLP",
    "vigdesde": "11-04-20",
    "vighasta": "09-15-22",
    "estado": "Donec",
    "Nuevo": "true",
    "Usuario": "Jesse",
    "Poliza": "W6X 4U5"
  },
  {
    "factura": 50,
    "serie": 10,
    "exp": 2399,
    "Fe_registro": "01-27-21",
    "Domicilio": "Apdo.:899-7080 Accumsan Carretera",
    "Moneda": 2,
    "Ramo": "sed, hendrerit",
    "Indole": "Ac Consulting",
    "Negocio": "Pellentesque Ultricies Inc.",
    "Cedente": "At Industries",
    "AsegAfian": "Gravida Inc.",
    "Suscriptor": "Commodo Ipsum Suspendisse Inc.",
    "vigdesde": "07-14-20",
    "vighasta": "02-13-22",
    "estado": "sed",
    "Nuevo": "false",
    "Usuario": "Ali",
    "Poliza": "A3T 4O7"
  },
  {
    "factura": 51,
    "serie": 15,
    "exp": 2263,
    "Fe_registro": "06-13-20",
    "Domicilio": "Apdo.:635-2396 Cubilia Calle",
    "Moneda": 2,
    "Ramo": "Aenean",
    "Indole": "Aenean Gravida Nunc Inc.",
    "Negocio": "Amet Incorporated",
    "Cedente": "Nam Foundation",
    "AsegAfian": "Sed Inc.",
    "Suscriptor": "Ligula Tortor LLC",
    "vigdesde": "06-14-20",
    "vighasta": "09-13-22",
    "estado": "lorem",
    "Nuevo": "true",
    "Usuario": "Ross",
    "Poliza": "I2D 6F6"
  },
  {
    "factura": 52,
    "serie": 12,
    "exp": 2398,
    "Fe_registro": "11-21-20",
    "Domicilio": "Apdo.:195-9390 Dolor Avda.",
    "Moneda": 4,
    "Ramo": "est mauris,",
    "Indole": "At Libero Morbi Industries",
    "Negocio": "Nulla Cras Eu Foundation",
    "Cedente": "Praesent Eu Nulla Institute",
    "AsegAfian": "Neque Vitae Associates",
    "Suscriptor": "Cursus Purus LLP",
    "vigdesde": "01-21-20",
    "vighasta": "02-09-22",
    "estado": "rhoncus.",
    "Nuevo": "true",
    "Usuario": "Abdul",
    "Poliza": "H6I 2G8"
  },
  {
    "factura": 53,
    "serie": 16,
    "exp": 2236,
    "Fe_registro": "08-29-20",
    "Domicilio": "Apartado núm.: 767, 5251 Pede. Carretera",
    "Moneda": 6,
    "Ramo": "eget laoreet",
    "Indole": "Ullamcorper Incorporated",
    "Negocio": "Turpis Inc.",
    "Cedente": "Lacinia Mattis Integer Limited",
    "AsegAfian": "Et Ultrices Posuere Associates",
    "Suscriptor": "Id Incorporated",
    "vigdesde": "07-01-20",
    "vighasta": "10-20-22",
    "estado": "dolor",
    "Nuevo": "false",
    "Usuario": "Hakeem",
    "Poliza": "Q9H 4L9"
  },
  {
    "factura": 54,
    "serie": 18,
    "exp": 2234,
    "Fe_registro": "03-16-20",
    "Domicilio": "870-2447 Cras Avda.",
    "Moneda": 7,
    "Ramo": "egestas",
    "Indole": "Facilisis Vitae PC",
    "Negocio": "Egestas Rhoncus LLC",
    "Cedente": "Eu Enim Etiam Consulting",
    "AsegAfian": "Eget Massa Company",
    "Suscriptor": "Vel Quam Dignissim Institute",
    "vigdesde": "06-13-20",
    "vighasta": "09-03-21",
    "estado": "ante.",
    "Nuevo": "false",
    "Usuario": "Kaseem",
    "Poliza": "T3X 6D6"
  },
  {
    "factura": 55,
    "serie": 17,
    "exp": 2392,
    "Fe_registro": "11-01-21",
    "Domicilio": "542-7826 Proin Carretera",
    "Moneda": 5,
    "Ramo": "mollis.",
    "Indole": "Euismod Est Arcu Ltd",
    "Negocio": "Sed Dictum LLP",
    "Cedente": "Quis Corp.",
    "AsegAfian": "Justo Praesent Industries",
    "Suscriptor": "Vestibulum Consulting",
    "vigdesde": "03-23-20",
    "vighasta": "05-12-21",
    "estado": "Suspendisse",
    "Nuevo": "false",
    "Usuario": "Silas",
    "Poliza": "R4A 2V1"
  },
  {
    "factura": 56,
    "serie": 14,
    "exp": 2393,
    "Fe_registro": "03-02-20",
    "Domicilio": "180-9114 Magnis C.",
    "Moneda": 3,
    "Ramo": "auctor.",
    "Indole": "Morbi Neque Tellus Incorporated",
    "Negocio": "Lobortis Incorporated",
    "Cedente": "Suspendisse Aliquet Molestie Company",
    "AsegAfian": "Tempus Lorem Fringilla LLC",
    "Suscriptor": "Velit Pellentesque Ultricies Corporation",
    "vigdesde": "10-09-20",
    "vighasta": "08-13-22",
    "estado": "metus.",
    "Nuevo": "true",
    "Usuario": "Abbot",
    "Poliza": "L8Z 4V0"
  },
  {
    "factura": 57,
    "serie": 12,
    "exp": 2205,
    "Fe_registro": "08-22-21",
    "Domicilio": "3159 Eu Avenida",
    "Moneda": 1,
    "Ramo": "lorem semper auctor.",
    "Indole": "Vel Institute",
    "Negocio": "Nunc Incorporated",
    "Cedente": "Lacus Ut Nec Foundation",
    "AsegAfian": "Nascetur Ridiculus Mus Limited",
    "Suscriptor": "Urna Incorporated",
    "vigdesde": "04-22-20",
    "vighasta": "01-05-22",
    "estado": "Fusce",
    "Nuevo": "false",
    "Usuario": "Craig",
    "Poliza": "M8U 6B8"
  },
  {
    "factura": 58,
    "serie": 13,
    "exp": 2368,
    "Fe_registro": "05-26-20",
    "Domicilio": "134-5116 Mauris. Avda.",
    "Moneda": 7,
    "Ramo": "Maecenas malesuada",
    "Indole": "Mauris Company",
    "Negocio": "Placerat Orci Industries",
    "Cedente": "Mauris Vel Turpis Ltd",
    "AsegAfian": "Felis Company",
    "Suscriptor": "Augue Eu Tellus LLP",
    "vigdesde": "03-09-20",
    "vighasta": "04-24-22",
    "estado": "turpis",
    "Nuevo": "true",
    "Usuario": "Jonas",
    "Poliza": "X5L 5W7"
  },
  {
    "factura": 59,
    "serie": 18,
    "exp": 2396,
    "Fe_registro": "04-22-20",
    "Domicilio": "813-6895 Placerat C/",
    "Moneda": 6,
    "Ramo": "dolor dapibus",
    "Indole": "Praesent Limited",
    "Negocio": "Aenean Euismod Industries",
    "Cedente": "Morbi Sit Institute",
    "AsegAfian": "Eu LLP",
    "Suscriptor": "Semper Corporation",
    "vigdesde": "03-31-20",
    "vighasta": "03-14-21",
    "estado": "pharetra",
    "Nuevo": "false",
    "Usuario": "Hector",
    "Poliza": "N0I 3A4"
  },
  {
    "factura": 60,
    "serie": 16,
    "exp": 2322,
    "Fe_registro": "09-21-21",
    "Domicilio": "Apartado núm.: 545, 6746 Taciti C/",
    "Moneda": 3,
    "Ramo": "sagittis placerat. Cras",
    "Indole": "Molestie Sodales PC",
    "Negocio": "Faucibus Incorporated",
    "Cedente": "Faucibus Id Associates",
    "AsegAfian": "Adipiscing Non Luctus PC",
    "Suscriptor": "Amet Nulla Donec Inc.",
    "vigdesde": "04-27-20",
    "vighasta": "08-19-21",
    "estado": "risus",
    "Nuevo": "false",
    "Usuario": "Josiah",
    "Poliza": "K0T 9H9"
  },
  {
    "factura": 61,
    "serie": 15,
    "exp": 2322,
    "Fe_registro": "04-16-21",
    "Domicilio": "1398 A Avenida",
    "Moneda": 4,
    "Ramo": "ligula. Nullam enim.",
    "Indole": "Congue Corp.",
    "Negocio": "Arcu Imperdiet Ullamcorper Consulting",
    "Cedente": "Semper Et Lacinia Ltd",
    "AsegAfian": "Etiam Company",
    "Suscriptor": "Eget Volutpat Ornare Corporation",
    "vigdesde": "02-06-20",
    "vighasta": "09-14-22",
    "estado": "Cras",
    "Nuevo": "false",
    "Usuario": "Adrian",
    "Poliza": "I4J 7T9"
  },
  {
    "factura": 62,
    "serie": 10,
    "exp": 2233,
    "Fe_registro": "08-15-20",
    "Domicilio": "Apartado núm.: 536, 6516 Ac C.",
    "Moneda": 1,
    "Ramo": "mi",
    "Indole": "Suspendisse Dui Fusce Industries",
    "Negocio": "Fermentum Foundation",
    "Cedente": "Nulla Incorporated",
    "AsegAfian": "Gravida Limited",
    "Suscriptor": "Sed LLC",
    "vigdesde": "08-12-20",
    "vighasta": "05-08-22",
    "estado": "non",
    "Nuevo": "false",
    "Usuario": "Lucian",
    "Poliza": "X9V 4B6"
  },
  {
    "factura": 63,
    "serie": 17,
    "exp": 2301,
    "Fe_registro": "07-15-21",
    "Domicilio": "Apartado núm.: 799, 8486 Nunc Avda.",
    "Moneda": 5,
    "Ramo": "montes, nascetur ridiculus",
    "Indole": "Nec Corp.",
    "Negocio": "Sapien Corp.",
    "Cedente": "Suspendisse Incorporated",
    "AsegAfian": "Ornare Sagittis Felis Ltd",
    "Suscriptor": "Suspendisse Sed Ltd",
    "vigdesde": "03-29-20",
    "vighasta": "08-11-22",
    "estado": "scelerisque",
    "Nuevo": "false",
    "Usuario": "Logan",
    "Poliza": "S7S 2O7"
  },
  {
    "factura": 64,
    "serie": 14,
    "exp": 2353,
    "Fe_registro": "05-04-20",
    "Domicilio": "5034 Ante Av.",
    "Moneda": 4,
    "Ramo": "libero at",
    "Indole": "Congue PC",
    "Negocio": "Cum Sociis Corporation",
    "Cedente": "Ligula Donec Industries",
    "AsegAfian": "In Associates",
    "Suscriptor": "Ac Corp.",
    "vigdesde": "06-22-20",
    "vighasta": "12-29-21",
    "estado": "hendrerit",
    "Nuevo": "false",
    "Usuario": "Hamish",
    "Poliza": "P5O 1J0"
  },
  {
    "factura": 65,
    "serie": 17,
    "exp": 2299,
    "Fe_registro": "07-17-20",
    "Domicilio": "Apartado núm.: 864, 4703 In C.",
    "Moneda": 5,
    "Ramo": "sapien imperdiet ornare.",
    "Indole": "Ante Associates",
    "Negocio": "Sapien Cursus In Corp.",
    "Cedente": "Urna Convallis Erat PC",
    "AsegAfian": "Primis Foundation",
    "Suscriptor": "Faucibus Morbi Incorporated",
    "vigdesde": "07-13-20",
    "vighasta": "04-30-21",
    "estado": "eu",
    "Nuevo": "false",
    "Usuario": "Marvin",
    "Poliza": "I8B 3Y9"
  },
  {
    "factura": 66,
    "serie": 20,
    "exp": 2213,
    "Fe_registro": "04-12-21",
    "Domicilio": "Apartado núm.: 528, 4183 A, C/",
    "Moneda": 5,
    "Ramo": "nunc. Quisque ornare",
    "Indole": "At Associates",
    "Negocio": "Gravida Mauris Company",
    "Cedente": "Aenean Eget PC",
    "AsegAfian": "Integer LLC",
    "Suscriptor": "Lorem Vehicula Ltd",
    "vigdesde": "03-06-20",
    "vighasta": "02-23-21",
    "estado": "augue",
    "Nuevo": "true",
    "Usuario": "Caleb",
    "Poliza": "P0W 4C5"
  },
  {
    "factura": 67,
    "serie": 19,
    "exp": 2360,
    "Fe_registro": "03-20-20",
    "Domicilio": "Apdo.:546-238 Cras Carretera",
    "Moneda": 2,
    "Ramo": "ante.",
    "Indole": "Libero Institute",
    "Negocio": "Placerat Augue Sed Industries",
    "Cedente": "Pharetra Felis Institute",
    "AsegAfian": "Augue Malesuada Malesuada Associates",
    "Suscriptor": "Dis Parturient Montes Incorporated",
    "vigdesde": "06-29-20",
    "vighasta": "10-25-22",
    "estado": "Mauris",
    "Nuevo": "false",
    "Usuario": "Curran",
    "Poliza": "S6C 8B9"
  },
  {
    "factura": 68,
    "serie": 11,
    "exp": 2373,
    "Fe_registro": "06-08-21",
    "Domicilio": "5579 Blandit C/",
    "Moneda": 2,
    "Ramo": "cursus purus. Nullam",
    "Indole": "Praesent Inc.",
    "Negocio": "Nisi Incorporated",
    "Cedente": "Egestas Blandit LLP",
    "AsegAfian": "Ante Nunc Limited",
    "Suscriptor": "Enim Sed Nulla Corp.",
    "vigdesde": "05-06-20",
    "vighasta": "12-30-21",
    "estado": "libero",
    "Nuevo": "false",
    "Usuario": "Felix",
    "Poliza": "T5L 1W8"
  },
  {
    "factura": 69,
    "serie": 16,
    "exp": 2320,
    "Fe_registro": "05-21-21",
    "Domicilio": "439-7924 Elit C/",
    "Moneda": 1,
    "Ramo": "nibh vulputate",
    "Indole": "Facilisis Magna Foundation",
    "Negocio": "Nunc Risus Varius Corporation",
    "Cedente": "Eu Foundation",
    "AsegAfian": "Integer Id Magna Corp.",
    "Suscriptor": "Suspendisse Sed Company",
    "vigdesde": "11-13-20",
    "vighasta": "07-29-21",
    "estado": "quam.",
    "Nuevo": "true",
    "Usuario": "Benjamin",
    "Poliza": "U0M 9P4"
  },
  {
    "factura": 70,
    "serie": 19,
    "exp": 2274,
    "Fe_registro": "03-24-21",
    "Domicilio": "Apdo.:391-1749 Nascetur Avda.",
    "Moneda": 1,
    "Ramo": "sit",
    "Indole": "Mollis Dui In Consulting",
    "Negocio": "Morbi Vehicula Pellentesque Inc.",
    "Cedente": "Et Pede Associates",
    "AsegAfian": "Amet Consectetuer Adipiscing Industries",
    "Suscriptor": "Ipsum Suspendisse Non Limited",
    "vigdesde": "05-26-20",
    "vighasta": "12-16-22",
    "estado": "sit",
    "Nuevo": "false",
    "Usuario": "Uriel",
    "Poliza": "M0T 0T3"
  },
  {
    "factura": 71,
    "serie": 17,
    "exp": 2346,
    "Fe_registro": "08-03-20",
    "Domicilio": "143-8118 Dolor, Av.",
    "Moneda": 4,
    "Ramo": "felis, adipiscing fringilla,",
    "Indole": "Nunc Inc.",
    "Negocio": "Dui Company",
    "Cedente": "Proin LLP",
    "AsegAfian": "Mi Associates",
    "Suscriptor": "Fermentum Vel Mauris Inc.",
    "vigdesde": "01-01-20",
    "vighasta": "11-04-22",
    "estado": "Cras",
    "Nuevo": "false",
    "Usuario": "Josiah",
    "Poliza": "Y2S 8I7"
  },
  {
    "factura": 72,
    "serie": 14,
    "exp": 2228,
    "Fe_registro": "01-30-20",
    "Domicilio": "3194 Risus. Avda.",
    "Moneda": 6,
    "Ramo": "arcu",
    "Indole": "Cras Incorporated",
    "Negocio": "Odio Nam Interdum Corporation",
    "Cedente": "At Pede Corporation",
    "AsegAfian": "Malesuada Malesuada Integer Associates",
    "Suscriptor": "Risus Nulla Industries",
    "vigdesde": "06-14-20",
    "vighasta": "11-29-22",
    "estado": "enim",
    "Nuevo": "true",
    "Usuario": "Steven",
    "Poliza": "K5D 0V5"
  },
  {
    "factura": 73,
    "serie": 11,
    "exp": 2280,
    "Fe_registro": "12-13-20",
    "Domicilio": "8248 Posuere Calle",
    "Moneda": 6,
    "Ramo": "at, egestas",
    "Indole": "Consequat Foundation",
    "Negocio": "Sapien Cursus LLC",
    "Cedente": "Velit Aliquam Associates",
    "AsegAfian": "Maecenas Mi Ltd",
    "Suscriptor": "Egestas Company",
    "vigdesde": "01-27-20",
    "vighasta": "06-27-21",
    "estado": "semper",
    "Nuevo": "false",
    "Usuario": "Tobias",
    "Poliza": "W2X 0Q6"
  },
  {
    "factura": 74,
    "serie": 18,
    "exp": 2327,
    "Fe_registro": "09-12-20",
    "Domicilio": "Apartado núm.: 590, 4805 Tincidunt, Carretera",
    "Moneda": 3,
    "Ramo": "est mauris,",
    "Indole": "Suspendisse Ac LLP",
    "Negocio": "Velit Eu Consulting",
    "Cedente": "Nulla In Inc.",
    "AsegAfian": "Cursus Corp.",
    "Suscriptor": "Elit Pretium Company",
    "vigdesde": "08-18-20",
    "vighasta": "01-14-22",
    "estado": "orci",
    "Nuevo": "false",
    "Usuario": "Colby",
    "Poliza": "B1I 5Y7"
  },
  {
    "factura": 75,
    "serie": 12,
    "exp": 2223,
    "Fe_registro": "07-19-21",
    "Domicilio": "Apartado núm.: 797, 1790 Elit, Av.",
    "Moneda": 2,
    "Ramo": "elementum",
    "Indole": "Sagittis Duis Consulting",
    "Negocio": "Felis Purus Ac Associates",
    "Cedente": "Scelerisque Lorem Ipsum Institute",
    "AsegAfian": "Nulla Vulputate PC",
    "Suscriptor": "Aliquet Corporation",
    "vigdesde": "10-20-20",
    "vighasta": "03-23-22",
    "estado": "ultrices.",
    "Nuevo": "false",
    "Usuario": "Timothy",
    "Poliza": "F7L 7P5"
  },
  {
    "factura": 76,
    "serie": 13,
    "exp": 2316,
    "Fe_registro": "12-27-20",
    "Domicilio": "Apartado núm.: 413, 994 Erat C/",
    "Moneda": 2,
    "Ramo": "amet",
    "Indole": "In Corp.",
    "Negocio": "Nulla At Sem LLP",
    "Cedente": "Dui Nec Tempus Associates",
    "AsegAfian": "Nulla Ltd",
    "Suscriptor": "Mi Felis Adipiscing Inc.",
    "vigdesde": "07-24-20",
    "vighasta": "03-02-21",
    "estado": "dolor",
    "Nuevo": "true",
    "Usuario": "Alden",
    "Poliza": "M4U 8T9"
  },
  {
    "factura": 77,
    "serie": 17,
    "exp": 2291,
    "Fe_registro": "11-30-20",
    "Domicilio": "Apdo.:353-7989 Tellus C/",
    "Moneda": 5,
    "Ramo": "Sed eu eros.",
    "Indole": "Ante Associates",
    "Negocio": "Donec Feugiat PC",
    "Cedente": "Magnis Dis Parturient Ltd",
    "AsegAfian": "Sociis Natoque Penatibus LLC",
    "Suscriptor": "Pretium Neque Incorporated",
    "vigdesde": "03-29-20",
    "vighasta": "07-14-22",
    "estado": "lorem",
    "Nuevo": "true",
    "Usuario": "Slade",
    "Poliza": "T6O 9S3"
  },
  {
    "factura": 78,
    "serie": 16,
    "exp": 2224,
    "Fe_registro": "06-27-20",
    "Domicilio": "155-3376 Eget Avda.",
    "Moneda": 1,
    "Ramo": "consequat auctor, nunc",
    "Indole": "Proin Nisl Corporation",
    "Negocio": "Arcu Associates",
    "Cedente": "Nibh Donec Incorporated",
    "AsegAfian": "Suspendisse Commodo Tincidunt Limited",
    "Suscriptor": "Ac Mattis Velit Corp.",
    "vigdesde": "04-13-20",
    "vighasta": "10-02-22",
    "estado": "risus.",
    "Nuevo": "true",
    "Usuario": "Baxter",
    "Poliza": "X4E 3R5"
  },
  {
    "factura": 79,
    "serie": 12,
    "exp": 2215,
    "Fe_registro": "12-30-21",
    "Domicilio": "Apdo.:631-723 Feugiat Av.",
    "Moneda": 1,
    "Ramo": "nisi. Cum",
    "Indole": "Nam Ac Institute",
    "Negocio": "Aliquam Enim Nec PC",
    "Cedente": "Non Sapien Molestie LLC",
    "AsegAfian": "Risus Quisque Libero Corp.",
    "Suscriptor": "Egestas PC",
    "vigdesde": "11-02-20",
    "vighasta": "01-04-22",
    "estado": "vel",
    "Nuevo": "true",
    "Usuario": "Eaton",
    "Poliza": "B0P 4L7"
  },
  {
    "factura": 80,
    "serie": 20,
    "exp": 2293,
    "Fe_registro": "04-14-20",
    "Domicilio": "Apartado núm.: 903, 4924 Neque Avda.",
    "Moneda": 3,
    "Ramo": "Donec tincidunt. Donec",
    "Indole": "Integer Corporation",
    "Negocio": "Sit Incorporated",
    "Cedente": "Eleifend Industries",
    "AsegAfian": "Penatibus Incorporated",
    "Suscriptor": "Ridiculus Mus Institute",
    "vigdesde": "03-15-20",
    "vighasta": "12-22-21",
    "estado": "dolor",
    "Nuevo": "true",
    "Usuario": "Wing",
    "Poliza": "U8A 8X7"
  },
  {
    "factura": 81,
    "serie": 14,
    "exp": 2273,
    "Fe_registro": "05-20-21",
    "Domicilio": "572-9429 Vivamus Av.",
    "Moneda": 5,
    "Ramo": "ornare",
    "Indole": "At Iaculis Quis Institute",
    "Negocio": "Scelerisque Dui Consulting",
    "Cedente": "Tempor Lorem Industries",
    "AsegAfian": "Turpis In Condimentum Limited",
    "Suscriptor": "Euismod Ac Fermentum Consulting",
    "vigdesde": "10-04-20",
    "vighasta": "09-29-22",
    "estado": "Nunc",
    "Nuevo": "true",
    "Usuario": "Lawrence",
    "Poliza": "L1H 0L5"
  },
  {
    "factura": 82,
    "serie": 18,
    "exp": 2267,
    "Fe_registro": "03-03-21",
    "Domicilio": "Apartado núm.: 887, 9340 Ultricies Avda.",
    "Moneda": 3,
    "Ramo": "porta elit, a",
    "Indole": "Congue Institute",
    "Negocio": "Nunc Sed Consulting",
    "Cedente": "Non Company",
    "AsegAfian": "Mauris A Nunc Consulting",
    "Suscriptor": "Est Mauris Rhoncus LLP",
    "vigdesde": "11-28-20",
    "vighasta": "02-12-21",
    "estado": "id,",
    "Nuevo": "false",
    "Usuario": "Orlando",
    "Poliza": "T2M 3U4"
  },
  {
    "factura": 83,
    "serie": 15,
    "exp": 2387,
    "Fe_registro": "04-06-21",
    "Domicilio": "Apartado núm.: 346, 1336 Enim ",
    "Moneda": 6,
    "Ramo": "sit amet orci.",
    "Indole": "Sit Amet LLC",
    "Negocio": "Aliquam Enim Nec Incorporated",
    "Cedente": "Varius Nam Porttitor Limited",
    "AsegAfian": "Auctor Consulting",
    "Suscriptor": "Nibh Corporation",
    "vigdesde": "02-10-20",
    "vighasta": "12-04-22",
    "estado": "sem",
    "Nuevo": "false",
    "Usuario": "Clarke",
    "Poliza": "P1J 4D7"
  },
  {
    "factura": 84,
    "serie": 17,
    "exp": 2351,
    "Fe_registro": "07-16-21",
    "Domicilio": "552-9179 Habitant ",
    "Moneda": 5,
    "Ramo": "pede, malesuada vel,",
    "Indole": "Ultricies Dignissim Incorporated",
    "Negocio": "Quisque Varius Nam LLP",
    "Cedente": "Porttitor Associates",
    "AsegAfian": "Congue Elit Sed Corp.",
    "Suscriptor": "Nulla Aliquet Associates",
    "vigdesde": "08-08-20",
    "vighasta": "02-11-21",
    "estado": "diam",
    "Nuevo": "true",
    "Usuario": "Keith",
    "Poliza": "J5B 9Z0"
  },
  {
    "factura": 85,
    "serie": 13,
    "exp": 2217,
    "Fe_registro": "11-05-20",
    "Domicilio": "Apartado núm.: 841, 944 Feugiat Ctra.",
    "Moneda": 7,
    "Ramo": "porttitor interdum.",
    "Indole": "Magna Corp.",
    "Negocio": "Nec Corp.",
    "Cedente": "Ad Litora Torquent Consulting",
    "AsegAfian": "Mi Felis Adipiscing Inc.",
    "Suscriptor": "Cras Convallis PC",
    "vigdesde": "07-04-20",
    "vighasta": "10-07-22",
    "estado": "aliquet",
    "Nuevo": "false",
    "Usuario": "Blaze",
    "Poliza": "T1Z 7P0"
  },
  {
    "factura": 86,
    "serie": 17,
    "exp": 2348,
    "Fe_registro": "01-11-21",
    "Domicilio": "Apdo.:609-7987 Magna. Ctra.",
    "Moneda": 5,
    "Ramo": "non lorem vitae",
    "Indole": "Aliquam Vulputate Ullamcorper Consulting",
    "Negocio": "Mauris Sagittis Placerat LLP",
    "Cedente": "Et Ultrices Posuere Corp.",
    "AsegAfian": "Elit Corp.",
    "Suscriptor": "Pellentesque Ut Foundation",
    "vigdesde": "01-30-20",
    "vighasta": "01-12-22",
    "estado": "Donec",
    "Nuevo": "true",
    "Usuario": "Laith",
    "Poliza": "H9H 0U7"
  },
  {
    "factura": 87,
    "serie": 19,
    "exp": 2259,
    "Fe_registro": "06-12-20",
    "Domicilio": "Apdo.:875-6921 Malesuada Av.",
    "Moneda": 5,
    "Ramo": "nec",
    "Indole": "Etiam Company",
    "Negocio": "Tincidunt Orci Quis Associates",
    "Cedente": "Gravida Aliquam Consulting",
    "AsegAfian": "Enim Sed Nulla Corporation",
    "Suscriptor": "Ipsum PC",
    "vigdesde": "09-10-20",
    "vighasta": "01-27-22",
    "estado": "penatibus",
    "Nuevo": "true",
    "Usuario": "Ignatius",
    "Poliza": "C2D 7L3"
  },
  {
    "factura": 88,
    "serie": 20,
    "exp": 2357,
    "Fe_registro": "06-01-20",
    "Domicilio": "884-7237 Augue Ctra.",
    "Moneda": 2,
    "Ramo": "magnis",
    "Indole": "Eget Massa Associates",
    "Negocio": "Sed Company",
    "Cedente": "Tincidunt Corp.",
    "AsegAfian": "Ridiculus Mus Consulting",
    "Suscriptor": "Blandit Nam Associates",
    "vigdesde": "06-23-20",
    "vighasta": "09-24-22",
    "estado": "purus",
    "Nuevo": "true",
    "Usuario": "Neville",
    "Poliza": "J0V 7F3"
  },
  {
    "factura": 89,
    "serie": 12,
    "exp": 2347,
    "Fe_registro": "06-08-20",
    "Domicilio": "756-8990 Donec Calle",
    "Moneda": 2,
    "Ramo": "nulla",
    "Indole": "Proin Vel Nisl Corp.",
    "Negocio": "Consectetuer Adipiscing Associates",
    "Cedente": "Nonummy Ultricies Ornare Ltd",
    "AsegAfian": "Eget Metus Eu Company",
    "Suscriptor": "Eleifend Egestas Sed Institute",
    "vigdesde": "07-02-20",
    "vighasta": "05-24-21",
    "estado": "nunc,",
    "Nuevo": "false",
    "Usuario": "Murphy",
    "Poliza": "M6M 6R2"
  },
  {
    "factura": 90,
    "serie": 13,
    "exp": 2377,
    "Fe_registro": "04-30-20",
    "Domicilio": "Apdo.:282-9449 Vitae, Av.",
    "Moneda": 5,
    "Ramo": "non dui",
    "Indole": "Eu Associates",
    "Negocio": "Luctus Associates",
    "Cedente": "Duis Consulting",
    "AsegAfian": "At Libero Morbi Consulting",
    "Suscriptor": "Aliquet Sem LLC",
    "vigdesde": "12-18-20",
    "vighasta": "05-14-21",
    "estado": "tempor",
    "Nuevo": "true",
    "Usuario": "Berk",
    "Poliza": "C1I 9C3"
  },
  {
    "factura": 91,
    "serie": 10,
    "exp": 2286,
    "Fe_registro": "02-18-20",
    "Domicilio": "772-9154 Odio, Avenida",
    "Moneda": 1,
    "Ramo": "nec,",
    "Indole": "Nam Ligula Elit Inc.",
    "Negocio": "Orci Ut Incorporated",
    "Cedente": "Tempus PC",
    "AsegAfian": "Amet Consectetuer Company",
    "Suscriptor": "Nunc Est Mollis Incorporated",
    "vigdesde": "10-23-20",
    "vighasta": "05-15-21",
    "estado": "non",
    "Nuevo": "true",
    "Usuario": "Kennedy",
    "Poliza": "N2Y 9C0"
  },
  {
    "factura": 92,
    "serie": 10,
    "exp": 2317,
    "Fe_registro": "07-24-21",
    "Domicilio": "5873 Suspendisse ",
    "Moneda": 5,
    "Ramo": "tincidunt,",
    "Indole": "A Ultricies Adipiscing Company",
    "Negocio": "Ridiculus Mus Proin LLP",
    "Cedente": "Sapien Gravida LLP",
    "AsegAfian": "Ultrices Incorporated",
    "Suscriptor": "Sapien Cras Incorporated",
    "vigdesde": "04-20-20",
    "vighasta": "09-09-21",
    "estado": "eget",
    "Nuevo": "false",
    "Usuario": "Amal",
    "Poliza": "G7F 1Y2"
  },
  {
    "factura": 93,
    "serie": 10,
    "exp": 2229,
    "Fe_registro": "11-05-21",
    "Domicilio": "Apdo.:317-2328 Commodo C/",
    "Moneda": 4,
    "Ramo": "Etiam",
    "Indole": "Aliquet Lobortis Inc.",
    "Negocio": "Hymenaeos Corp.",
    "Cedente": "Metus Vitae Velit Ltd",
    "AsegAfian": "Vestibulum LLC",
    "Suscriptor": "Ornare Fusce Foundation",
    "vigdesde": "02-16-20",
    "vighasta": "07-16-21",
    "estado": "Pellentesque",
    "Nuevo": "true",
    "Usuario": "Cade",
    "Poliza": "V1G 0J4"
  },
  {
    "factura": 94,
    "serie": 10,
    "exp": 2267,
    "Fe_registro": "11-29-21",
    "Domicilio": "Apartado núm.: 186, 2153 Cursus C/",
    "Moneda": 3,
    "Ramo": "odio semper cursus.",
    "Indole": "Sed Neque Incorporated",
    "Negocio": "Faucibus Ut Ltd",
    "Cedente": "Consectetuer Cursus Et Ltd",
    "AsegAfian": "Ac Tellus PC",
    "Suscriptor": "Convallis Limited",
    "vigdesde": "03-17-20",
    "vighasta": "04-04-22",
    "estado": "sapien.",
    "Nuevo": "true",
    "Usuario": "Lewis",
    "Poliza": "G8C 7W8"
  },
  {
    "factura": 95,
    "serie": 11,
    "exp": 2286,
    "Fe_registro": "10-29-20",
    "Domicilio": "194-4561 Nunc Avenida",
    "Moneda": 1,
    "Ramo": "vulputate, risus",
    "Indole": "Non Sollicitudin A Company",
    "Negocio": "Proin Mi Aliquam Consulting",
    "Cedente": "Sed Institute",
    "AsegAfian": "Praesent Luctus Consulting",
    "Suscriptor": "Ac Consulting",
    "vigdesde": "08-20-20",
    "vighasta": "12-07-22",
    "estado": "aliquam",
    "Nuevo": "false",
    "Usuario": "Fulton",
    "Poliza": "B6P 1J4"
  },
  {
    "factura": 96,
    "serie": 19,
    "exp": 2374,
    "Fe_registro": "11-01-20",
    "Domicilio": "Apartado núm.: 656, 8467 Litora Carretera",
    "Moneda": 5,
    "Ramo": "lectus convallis est,",
    "Indole": "Amet Ltd",
    "Negocio": "Nec LLC",
    "Cedente": "Nibh Enim Institute",
    "AsegAfian": "Consectetuer Rhoncus Nullam Associates",
    "Suscriptor": "Est Corp.",
    "vigdesde": "08-10-20",
    "vighasta": "07-06-21",
    "estado": "Nullam",
    "Nuevo": "true",
    "Usuario": "Cade",
    "Poliza": "K8V 9Z4"
  },
  {
    "factura": 97,
    "serie": 14,
    "exp": 2227,
    "Fe_registro": "11-07-21",
    "Domicilio": "Apartado núm.: 800, 3178 Hymenaeos. Av.",
    "Moneda": 4,
    "Ramo": "vulputate",
    "Indole": "Tristique Pharetra PC",
    "Negocio": "Consectetuer Adipiscing Elit Ltd",
    "Cedente": "Consectetuer Euismod Ltd",
    "AsegAfian": "Vulputate Velit Incorporated",
    "Suscriptor": "Tristique Aliquet Phasellus Corp.",
    "vigdesde": "04-05-20",
    "vighasta": "07-26-21",
    "estado": "felis.",
    "Nuevo": "false",
    "Usuario": "Amos",
    "Poliza": "J5B 2V9"
  },
  {
    "factura": 98,
    "serie": 12,
    "exp": 2340,
    "Fe_registro": "05-02-21",
    "Domicilio": "Apartado núm.: 390, 3797 Lectus Calle",
    "Moneda": 4,
    "Ramo": "dictum eu, eleifend",
    "Indole": "Eu Metus In Industries",
    "Negocio": "Sed Ltd",
    "Cedente": "Mi Incorporated",
    "AsegAfian": "Lacus Vestibulum Incorporated",
    "Suscriptor": "Nulla LLC",
    "vigdesde": "05-07-20",
    "vighasta": "05-19-22",
    "estado": "non,",
    "Nuevo": "false",
    "Usuario": "Norman",
    "Poliza": "Y9B 7I2"
  },
  {
    "factura": 99,
    "serie": 10,
    "exp": 2375,
    "Fe_registro": "10-18-20",
    "Domicilio": "Apdo.:950-8260 Sem C/",
    "Moneda": 4,
    "Ramo": "dolor.",
    "Indole": "Luctus LLP",
    "Negocio": "Non Limited",
    "Cedente": "Semper Nam LLC",
    "AsegAfian": "Eu Consulting",
    "Suscriptor": "Non Lorem Vitae PC",
    "vigdesde": "05-14-20",
    "vighasta": "07-21-21",
    "estado": "diam",
    "Nuevo": "true",
    "Usuario": "Porter",
    "Poliza": "B7Q 7F8"
  },
  {
    "factura": 100,
    "serie": 19,
    "exp": 2254,
    "Fe_registro": "10-16-21",
    "Domicilio": "Apartado núm.: 282, 6461 A, ",
    "Moneda": 3,
    "Ramo": "turpis. In condimentum.",
    "Indole": "Faucibus Orci Luctus Limited",
    "Negocio": "Suscipit Est Ac Company",
    "Cedente": "Sed Corporation",
    "AsegAfian": "Nunc Mauris Corp.",
    "Suscriptor": "Eget Corp.",
    "vigdesde": "10-13-20",
    "vighasta": "01-23-21",
    "estado": "ac",
    "Nuevo": "true",
    "Usuario": "Philip",
    "Poliza": "B3S 6V6"
  }
]

export default registro4;