const registro1 =[
  {
    "factura": 1,
    "serie": 20,
    "exp": 2274,
    "Fe_registro": "12-25-21",
    "Domicilio": "Apdo.:328-2535 Malesuada ",
    "Moneda": 7,
    "Ramo": "lorem,",
    "Indole": "Enim Nec Limited",
    "Negocio": "Aliquam Adipiscing Lacus Ltd",
    "Cedente": "Scelerisque Limited",
    "AsegAfian": "Suspendisse Commodo Tincidunt Corp.",
    "Suscriptor": "Integer Aliquam Institute",
    "vigdesde": "01-09-20",
    "vighasta": "01-09-21",
    "estado": "dictum",
    "Nuevo": "true",
    "Usuario": "Tiger",
    "Poliza": "X1D 8S8"
  },
  {
    "factura": 2,
    "serie": 14,
    "exp": 2210,
    "Fe_registro": "07-30-20",
    "Domicilio": "450-3503 Duis Ctra.",
    "Moneda": 3,
    "Ramo": "Phasellus ornare.",
    "Indole": "Sit Amet PC",
    "Negocio": "Arcu Vestibulum Ut LLC",
    "Cedente": "Sem Molestie Sodales Consulting",
    "AsegAfian": "Et Ltd",
    "Suscriptor": "Sociis Natoque Penatibus Ltd",
    "vigdesde": "02-27-20",
    "vighasta": "03-28-21",
    "estado": "libero",
    "Nuevo": "false",
    "Usuario": "Barrett",
    "Poliza": "F7H 1B8"
  },
  {
    "factura": 3,
    "serie": 15,
    "exp": 2344,
    "Fe_registro": "05-03-20",
    "Domicilio": "Apartado núm.: 269, 1895 Libero Av.",
    "Moneda": 7,
    "Ramo": "interdum",
    "Indole": "Sed Pede LLP",
    "Negocio": "Et Magnis Industries",
    "Cedente": "Dolor Donec Fringilla Corporation",
    "AsegAfian": "At Risus Nunc Associates",
    "Suscriptor": "Luctus Ipsum LLC",
    "vigdesde": "11-15-20",
    "vighasta": "01-12-21",
    "estado": "tincidunt.",
    "Nuevo": "true",
    "Usuario": "Guy",
    "Poliza": "X5B 2A4"
  },
  {
    "factura": 4,
    "serie": 13,
    "exp": 2202,
    "Fe_registro": "10-18-20",
    "Domicilio": "Apartado núm.: 729, 3427 Risus. ",
    "Moneda": 6,
    "Ramo": "lacinia. Sed",
    "Indole": "Risus Quisque Libero Corp.",
    "Negocio": "Tincidunt Foundation",
    "Cedente": "Venenatis A Magna Incorporated",
    "AsegAfian": "Ligula Donec Foundation",
    "Suscriptor": "Eleifend Cras Corporation",
    "vigdesde": "11-01-20",
    "vighasta": "09-27-21",
    "estado": "augue",
    "Nuevo": "false",
    "Usuario": "Zephania",
    "Poliza": "P8J 9H9"
  },
  {
    "factura": 5,
    "serie": 16,
    "exp": 2254,
    "Fe_registro": "03-27-20",
    "Domicilio": "3317 Luctus Carretera",
    "Moneda": 5,
    "Ramo": "Nullam scelerisque",
    "Indole": "In LLP",
    "Negocio": "Neque Associates",
    "Cedente": "Enim Etiam Incorporated",
    "AsegAfian": "Nunc Sit Foundation",
    "Suscriptor": "Nulla Limited",
    "vigdesde": "05-18-20",
    "vighasta": "06-10-22",
    "estado": "imperdiet",
    "Nuevo": "false",
    "Usuario": "Otto",
    "Poliza": "E9M 2U8"
  },
  {
    "factura": 6,
    "serie": 17,
    "exp": 2332,
    "Fe_registro": "04-04-20",
    "Domicilio": "Apdo.:486-9163 A Avda.",
    "Moneda": 3,
    "Ramo": "nunc interdum",
    "Indole": "Nec Diam Corporation",
    "Negocio": "Fusce Aliquet Magna Corporation",
    "Cedente": "Sed Foundation",
    "AsegAfian": "Amet Faucibus Ut Limited",
    "Suscriptor": "Eleifend Associates",
    "vigdesde": "04-23-20",
    "vighasta": "05-20-21",
    "estado": "erat,",
    "Nuevo": "false",
    "Usuario": "Vincent",
    "Poliza": "X9X 3A2"
  },
  {
    "factura": 7,
    "serie": 13,
    "exp": 2209,
    "Fe_registro": "10-08-21",
    "Domicilio": "Apartado núm.: 944, 3522 Eu Avenida",
    "Moneda": 2,
    "Ramo": "vulputate velit",
    "Indole": "Orci Lacus Foundation",
    "Negocio": "Quam Quis Diam Inc.",
    "Cedente": "Non Ante LLP",
    "AsegAfian": "Tortor Nunc Commodo Industries",
    "Suscriptor": "Ipsum Non Foundation",
    "vigdesde": "07-10-20",
    "vighasta": "01-22-21",
    "estado": "hendrerit",
    "Nuevo": "false",
    "Usuario": "Silas",
    "Poliza": "S4D 7G9"
  },
  {
    "factura": 8,
    "serie": 11,
    "exp": 2320,
    "Fe_registro": "11-19-21",
    "Domicilio": "Apartado núm.: 629, 7178 Leo. C/",
    "Moneda": 6,
    "Ramo": "magnis",
    "Indole": "Leo Company",
    "Negocio": "Non LLC",
    "Cedente": "Per Inceptos Hymenaeos Corporation",
    "AsegAfian": "Enim Suspendisse Aliquet Inc.",
    "Suscriptor": "Ipsum Phasellus Company",
    "vigdesde": "05-12-20",
    "vighasta": "10-07-21",
    "estado": "magna",
    "Nuevo": "true",
    "Usuario": "Hashim",
    "Poliza": "C4P 6X2"
  },
  {
    "factura": 9,
    "serie": 12,
    "exp": 2208,
    "Fe_registro": "08-13-20",
    "Domicilio": "Apdo.:805-4047 Auctor, ",
    "Moneda": 2,
    "Ramo": "sagittis",
    "Indole": "Proin Nisl Sem Associates",
    "Negocio": "Ornare Company",
    "Cedente": "Ultricies Ornare Consulting",
    "AsegAfian": "Accumsan Neque Company",
    "Suscriptor": "Vitae Erat Consulting",
    "vigdesde": "02-16-20",
    "vighasta": "01-06-22",
    "estado": "cursus",
    "Nuevo": "true",
    "Usuario": "Len",
    "Poliza": "D6W 5X7"
  },
  {
    "factura": 10,
    "serie": 13,
    "exp": 2273,
    "Fe_registro": "07-31-20",
    "Domicilio": "713-2898 A, Calle",
    "Moneda": 5,
    "Ramo": "eget, dictum",
    "Indole": "Lacus Varius Associates",
    "Negocio": "Pharetra Ut Pharetra Consulting",
    "Cedente": "Et Risus Ltd",
    "AsegAfian": "Leo Elementum Institute",
    "Suscriptor": "Risus Varius Ltd",
    "vigdesde": "06-02-20",
    "vighasta": "06-15-21",
    "estado": "malesuada",
    "Nuevo": "false",
    "Usuario": "Cain",
    "Poliza": "R8Z 7R5"
  },
  {
    "factura": 11,
    "serie": 19,
    "exp": 2266,
    "Fe_registro": "04-17-20",
    "Domicilio": "940-7882 Tellus. ",
    "Moneda": 6,
    "Ramo": "et ipsum",
    "Indole": "Nisl Sem Consequat LLP",
    "Negocio": "Turpis Aliquam Institute",
    "Cedente": "Ipsum Curabitur Company",
    "AsegAfian": "Sit Amet Consectetuer Inc.",
    "Suscriptor": "Mauris Suspendisse Limited",
    "vigdesde": "04-14-20",
    "vighasta": "01-16-21",
    "estado": "Duis",
    "Nuevo": "true",
    "Usuario": "Emery",
    "Poliza": "A5X 6C3"
  },
  {
    "factura": 12,
    "serie": 20,
    "exp": 2238,
    "Fe_registro": "10-20-21",
    "Domicilio": "2484 Natoque Carretera",
    "Moneda": 1,
    "Ramo": "Mauris vestibulum, neque",
    "Indole": "Vivamus Company",
    "Negocio": "Eleifend Inc.",
    "Cedente": "Nibh Corp.",
    "AsegAfian": "Phasellus Elit Pede Institute",
    "Suscriptor": "Turpis Vitae Limited",
    "vigdesde": "02-18-20",
    "vighasta": "06-23-21",
    "estado": "malesuada",
    "Nuevo": "false",
    "Usuario": "Cooper",
    "Poliza": "D6R 4Z5"
  },
  {
    "factura": 13,
    "serie": 15,
    "exp": 2212,
    "Fe_registro": "06-19-21",
    "Domicilio": "Apartado núm.: 340, 2069 Eget Avda.",
    "Moneda": 4,
    "Ramo": "mattis velit justo",
    "Indole": "Ridiculus Mus Corp.",
    "Negocio": "Tempor Arcu Consulting",
    "Cedente": "Cras Incorporated",
    "AsegAfian": "Amet Metus Aliquam Ltd",
    "Suscriptor": "Amet Risus Inc.",
    "vigdesde": "10-05-20",
    "vighasta": "05-27-21",
    "estado": "cursus",
    "Nuevo": "true",
    "Usuario": "Kuame",
    "Poliza": "E8H 9Y9"
  },
  {
    "factura": 14,
    "serie": 16,
    "exp": 2337,
    "Fe_registro": "07-05-20",
    "Domicilio": "Apartado núm.: 374, 4835 Convallis ",
    "Moneda": 3,
    "Ramo": "ultrices posuere cubilia",
    "Indole": "Hendrerit Donec Porttitor Ltd",
    "Negocio": "Luctus Et Ultrices Foundation",
    "Cedente": "Rhoncus Company",
    "AsegAfian": "Maecenas Inc.",
    "Suscriptor": "Aliquam Rutrum Lorem LLP",
    "vigdesde": "12-04-20",
    "vighasta": "10-11-22",
    "estado": "Vivamus",
    "Nuevo": "false",
    "Usuario": "Curran",
    "Poliza": "U4I 5K8"
  },
  {
    "factura": 15,
    "serie": 19,
    "exp": 2333,
    "Fe_registro": "12-17-21",
    "Domicilio": "1406 Pellentesque Av.",
    "Moneda": 1,
    "Ramo": "tortor. Nunc commodo",
    "Indole": "In Molestie Tortor Associates",
    "Negocio": "Vel Sapien Imperdiet PC",
    "Cedente": "At Libero Morbi PC",
    "AsegAfian": "At LLP",
    "Suscriptor": "Ultrices Posuere Cubilia Institute",
    "vigdesde": "05-06-20",
    "vighasta": "05-08-22",
    "estado": "et",
    "Nuevo": "false",
    "Usuario": "Lionel",
    "Poliza": "Q1C 0U0"
  },
  {
    "factura": 16,
    "serie": 14,
    "exp": 2317,
    "Fe_registro": "12-04-21",
    "Domicilio": "827-8039 Interdum. Ctra.",
    "Moneda": 2,
    "Ramo": "eleifend",
    "Indole": "Tellus LLC",
    "Negocio": "Quam Quis Diam Company",
    "Cedente": "In Felis Inc.",
    "AsegAfian": "Cras Interdum Limited",
    "Suscriptor": "Etiam Gravida Limited",
    "vigdesde": "03-09-20",
    "vighasta": "01-21-21",
    "estado": "eu",
    "Nuevo": "true",
    "Usuario": "Hedley",
    "Poliza": "A5N 9J4"
  },
  {
    "factura": 17,
    "serie": 14,
    "exp": 2341,
    "Fe_registro": "07-13-20",
    "Domicilio": "Apdo.:227-5642 Elit. Avenida",
    "Moneda": 3,
    "Ramo": "parturient",
    "Indole": "Aliquam Adipiscing LLC",
    "Negocio": "Quam Institute",
    "Cedente": "Lorem Sit Amet Consulting",
    "AsegAfian": "Eu Enim Industries",
    "Suscriptor": "Mi LLC",
    "vigdesde": "05-20-20",
    "vighasta": "06-28-21",
    "estado": "facilisis",
    "Nuevo": "false",
    "Usuario": "Dillon",
    "Poliza": "F3V 2C5"
  },
  {
    "factura": 18,
    "serie": 12,
    "exp": 2304,
    "Fe_registro": "04-03-20",
    "Domicilio": "Apartado núm.: 820, 2526 Dignissim. Av.",
    "Moneda": 4,
    "Ramo": "eu,",
    "Indole": "Nibh Dolor Nonummy Incorporated",
    "Negocio": "Tellus Eu Inc.",
    "Cedente": "Ante LLC",
    "AsegAfian": "Mi Pede Associates",
    "Suscriptor": "Et Magnis Dis Associates",
    "vigdesde": "05-28-20",
    "vighasta": "01-28-22",
    "estado": "ullamcorper",
    "Nuevo": "true",
    "Usuario": "Demetrius",
    "Poliza": "U0U 4K8"
  },
  {
    "factura": 19,
    "serie": 11,
    "exp": 2262,
    "Fe_registro": "06-21-20",
    "Domicilio": "Apdo.:137-9918 Mi Ctra.",
    "Moneda": 3,
    "Ramo": "interdum. Nunc",
    "Indole": "Id Incorporated",
    "Negocio": "Lobortis Tellus Company",
    "Cedente": "Sed LLP",
    "AsegAfian": "Libero Est Congue Ltd",
    "Suscriptor": "Non Enim LLP",
    "vigdesde": "09-03-20",
    "vighasta": "01-26-21",
    "estado": "odio",
    "Nuevo": "false",
    "Usuario": "Magee",
    "Poliza": "Z9E 3T1"
  },
  {
    "factura": 20,
    "serie": 12,
    "exp": 2391,
    "Fe_registro": "10-02-21",
    "Domicilio": "9136 Mollis C/",
    "Moneda": 6,
    "Ramo": "facilisi.",
    "Indole": "Suspendisse Inc.",
    "Negocio": "At Augue Id Ltd",
    "Cedente": "Turpis Nulla Aliquet LLP",
    "AsegAfian": "Mus Inc.",
    "Suscriptor": "Lacus Nulla Tincidunt Inc.",
    "vigdesde": "08-04-20",
    "vighasta": "01-05-22",
    "estado": "suscipit,",
    "Nuevo": "true",
    "Usuario": "Colt",
    "Poliza": "T3Z 5D9"
  },
  {
    "factura": 21,
    "serie": 12,
    "exp": 2266,
    "Fe_registro": "04-10-20",
    "Domicilio": "381-5835 Adipiscing Ctra.",
    "Moneda": 4,
    "Ramo": "nec ligula consectetuer",
    "Indole": "Lacinia Vitae Consulting",
    "Negocio": "Non Consulting",
    "Cedente": "Nec Incorporated",
    "AsegAfian": "Leo Elementum Sem Consulting",
    "Suscriptor": "Integer Aliquam Adipiscing Inc.",
    "vigdesde": "08-18-20",
    "vighasta": "09-30-21",
    "estado": "risus",
    "Nuevo": "false",
    "Usuario": "Channing",
    "Poliza": "S2Y 1O1"
  },
  {
    "factura": 22,
    "serie": 20,
    "exp": 2334,
    "Fe_registro": "12-15-21",
    "Domicilio": "6806 Dis C/",
    "Moneda": 4,
    "Ramo": "Nam tempor",
    "Indole": "Rutrum Lorem Consulting",
    "Negocio": "Pharetra Nam Associates",
    "Cedente": "At Iaculis Quis Associates",
    "AsegAfian": "Auctor Velit Eget Inc.",
    "Suscriptor": "Commodo Hendrerit Associates",
    "vigdesde": "09-09-20",
    "vighasta": "06-25-22",
    "estado": "arcu.",
    "Nuevo": "true",
    "Usuario": "Gage",
    "Poliza": "B9G 0N5"
  },
  {
    "factura": 23,
    "serie": 17,
    "exp": 2356,
    "Fe_registro": "03-01-21",
    "Domicilio": "Apdo.:628-1787 Leo. Ctra.",
    "Moneda": 4,
    "Ramo": "et, euismod et,",
    "Indole": "Quisque Incorporated",
    "Negocio": "Luctus Et Ultrices Limited",
    "Cedente": "Aenean Massa Integer Industries",
    "AsegAfian": "Eu Institute",
    "Suscriptor": "In Limited",
    "vigdesde": "12-06-20",
    "vighasta": "05-09-22",
    "estado": "Cras",
    "Nuevo": "true",
    "Usuario": "Perry",
    "Poliza": "K9I 8B1"
  },
  {
    "factura": 24,
    "serie": 15,
    "exp": 2256,
    "Fe_registro": "12-22-21",
    "Domicilio": "3318 Vel Avenida",
    "Moneda": 4,
    "Ramo": "mauris a nunc.",
    "Indole": "Mauris Nulla Ltd",
    "Negocio": "Egestas PC",
    "Cedente": "Integer Mollis Integer Corp.",
    "AsegAfian": "Ac Risus Morbi Company",
    "Suscriptor": "Ridiculus Mus Corporation",
    "vigdesde": "03-01-20",
    "vighasta": "04-29-22",
    "estado": "eu,",
    "Nuevo": "true",
    "Usuario": "Craig",
    "Poliza": "A5M 0D0"
  },
  {
    "factura": 25,
    "serie": 14,
    "exp": 2362,
    "Fe_registro": "10-20-21",
    "Domicilio": "4081 Elit Avda.",
    "Moneda": 7,
    "Ramo": "parturient",
    "Indole": "Nec Tempus Scelerisque Limited",
    "Negocio": "Tristique Associates",
    "Cedente": "Ac PC",
    "AsegAfian": "Et Pede Nunc Company",
    "Suscriptor": "Aliquet Molestie Consulting",
    "vigdesde": "05-25-20",
    "vighasta": "11-28-22",
    "estado": "vehicula",
    "Nuevo": "false",
    "Usuario": "Kelly",
    "Poliza": "K5Z 1O7"
  },
  {
    "factura": 26,
    "serie": 10,
    "exp": 2240,
    "Fe_registro": "08-30-21",
    "Domicilio": "Apartado núm.: 254, 5568 Donec Avenida",
    "Moneda": 1,
    "Ramo": "Aenean gravida nunc",
    "Indole": "Ante Corp.",
    "Negocio": "Egestas LLP",
    "Cedente": "Dignissim Tempor PC",
    "AsegAfian": "Est Mauris Eu LLP",
    "Suscriptor": "Nam Porttitor PC",
    "vigdesde": "07-09-20",
    "vighasta": "02-21-22",
    "estado": "in",
    "Nuevo": "false",
    "Usuario": "Nigel",
    "Poliza": "H6K 1B8"
  },
  {
    "factura": 27,
    "serie": 11,
    "exp": 2285,
    "Fe_registro": "09-26-20",
    "Domicilio": "Apartado núm.: 772, 9376 Ornare Carretera",
    "Moneda": 1,
    "Ramo": "Suspendisse",
    "Indole": "Turpis Consulting",
    "Negocio": "Libero Donec Consectetuer Incorporated",
    "Cedente": "At Arcu Vestibulum Foundation",
    "AsegAfian": "Mollis Nec LLC",
    "Suscriptor": "Donec At Arcu Industries",
    "vigdesde": "06-24-20",
    "vighasta": "12-16-22",
    "estado": "Mauris",
    "Nuevo": "true",
    "Usuario": "Blaze",
    "Poliza": "I5C 5M6"
  },
  {
    "factura": 28,
    "serie": 12,
    "exp": 2256,
    "Fe_registro": "05-27-21",
    "Domicilio": "Apartado núm.: 822, 1245 Nam C/",
    "Moneda": 1,
    "Ramo": "odio a purus.",
    "Indole": "Ligula Aenean Corporation",
    "Negocio": "Dolor Quisque Inc.",
    "Cedente": "Morbi Tristique Senectus LLP",
    "AsegAfian": "Metus Aenean Sed Consulting",
    "Suscriptor": "Dapibus Gravida Company",
    "vigdesde": "08-25-20",
    "vighasta": "03-26-21",
    "estado": "Sed",
    "Nuevo": "false",
    "Usuario": "Camden",
    "Poliza": "Q4A 1K8"
  },
  {
    "factura": 29,
    "serie": 12,
    "exp": 2257,
    "Fe_registro": "03-21-21",
    "Domicilio": "121-5630 Convallis ",
    "Moneda": 7,
    "Ramo": "eu metus. In",
    "Indole": "Tincidunt Consulting",
    "Negocio": "Etiam Foundation",
    "Cedente": "Justo Proin Non Corp.",
    "AsegAfian": "Dui Associates",
    "Suscriptor": "Cursus Et Eros Company",
    "vigdesde": "05-17-20",
    "vighasta": "01-14-21",
    "estado": "lorem,",
    "Nuevo": "false",
    "Usuario": "Jermaine",
    "Poliza": "I2K 2Q0"
  },
  {
    "factura": 30,
    "serie": 17,
    "exp": 2287,
    "Fe_registro": "07-28-21",
    "Domicilio": "Apdo.:459-4008 Quisque Carretera",
    "Moneda": 6,
    "Ramo": "quis",
    "Indole": "Nulla PC",
    "Negocio": "Neque Ltd",
    "Cedente": "Nec Leo Corporation",
    "AsegAfian": "Sociis Natoque Incorporated",
    "Suscriptor": "Imperdiet PC",
    "vigdesde": "08-07-20",
    "vighasta": "02-02-22",
    "estado": "mi",
    "Nuevo": "false",
    "Usuario": "Mark",
    "Poliza": "G8C 5N3"
  },
  {
    "factura": 31,
    "serie": 13,
    "exp": 2280,
    "Fe_registro": "02-18-20",
    "Domicilio": "4340 Eu Avenida",
    "Moneda": 3,
    "Ramo": "Integer tincidunt",
    "Indole": "Amet Diam Incorporated",
    "Negocio": "Sed Inc.",
    "Cedente": "Mauris Vel Foundation",
    "AsegAfian": "Et Inc.",
    "Suscriptor": "Diam Eu Corporation",
    "vigdesde": "09-20-20",
    "vighasta": "03-05-21",
    "estado": "est",
    "Nuevo": "false",
    "Usuario": "Hayden",
    "Poliza": "U3L 3N6"
  },
  {
    "factura": 32,
    "serie": 17,
    "exp": 2223,
    "Fe_registro": "03-23-21",
    "Domicilio": "424-190 Tristique Av.",
    "Moneda": 4,
    "Ramo": "dui lectus",
    "Indole": "Purus LLP",
    "Negocio": "Fames Industries",
    "Cedente": "Ac Mattis Corporation",
    "AsegAfian": "At Nisi Associates",
    "Suscriptor": "Pellentesque Ut Ipsum Inc.",
    "vigdesde": "03-06-20",
    "vighasta": "03-29-21",
    "estado": "nisl.",
    "Nuevo": "false",
    "Usuario": "Dalton",
    "Poliza": "M0T 7W3"
  },
  {
    "factura": 33,
    "serie": 14,
    "exp": 2261,
    "Fe_registro": "09-12-20",
    "Domicilio": "8744 Nec C.",
    "Moneda": 2,
    "Ramo": "Duis mi",
    "Indole": "Morbi Neque Inc.",
    "Negocio": "Integer Tincidunt LLC",
    "Cedente": "Nam Interdum Enim Consulting",
    "AsegAfian": "Ut Foundation",
    "Suscriptor": "Volutpat Institute",
    "vigdesde": "05-17-20",
    "vighasta": "08-19-22",
    "estado": "fringilla,",
    "Nuevo": "true",
    "Usuario": "Benedict",
    "Poliza": "I7L 7C7"
  },
  {
    "factura": 34,
    "serie": 15,
    "exp": 2323,
    "Fe_registro": "11-04-20",
    "Domicilio": "101-1123 Quisque C.",
    "Moneda": 2,
    "Ramo": "purus",
    "Indole": "Arcu Iaculis Enim LLP",
    "Negocio": "Ut Sem Ltd",
    "Cedente": "Ornare Elit Elit Company",
    "AsegAfian": "Praesent Luctus Foundation",
    "Suscriptor": "Diam Vel Arcu LLC",
    "vigdesde": "08-26-20",
    "vighasta": "11-09-21",
    "estado": "vel,",
    "Nuevo": "false",
    "Usuario": "Lev",
    "Poliza": "R1I 9C6"
  },
  {
    "factura": 35,
    "serie": 16,
    "exp": 2333,
    "Fe_registro": "01-07-21",
    "Domicilio": "918-3088 Lobortis Av.",
    "Moneda": 7,
    "Ramo": "tincidunt pede",
    "Indole": "Dis Parturient Montes Ltd",
    "Negocio": "Non Hendrerit Id Institute",
    "Cedente": "Non Dui Ltd",
    "AsegAfian": "Metus Eu Erat Corp.",
    "Suscriptor": "Ante Ipsum Institute",
    "vigdesde": "05-22-20",
    "vighasta": "06-29-21",
    "estado": "odio.",
    "Nuevo": "true",
    "Usuario": "Hunter",
    "Poliza": "A3V 7K3"
  },
  {
    "factura": 36,
    "serie": 17,
    "exp": 2220,
    "Fe_registro": "08-13-21",
    "Domicilio": "Apdo.:956-4357 Donec Carretera",
    "Moneda": 5,
    "Ramo": "auctor. Mauris",
    "Indole": "Hendrerit Donec Foundation",
    "Negocio": "Dui Quis Institute",
    "Cedente": "Elit Pede Malesuada Company",
    "AsegAfian": "Diam Pellentesque Habitant Inc.",
    "Suscriptor": "Elit Etiam Laoreet Foundation",
    "vigdesde": "03-27-20",
    "vighasta": "10-12-21",
    "estado": "quam",
    "Nuevo": "true",
    "Usuario": "Dale",
    "Poliza": "N2X 3A9"
  },
  {
    "factura": 37,
    "serie": 16,
    "exp": 2366,
    "Fe_registro": "05-28-20",
    "Domicilio": "Apartado núm.: 926, 8511 Imperdiet, Calle",
    "Moneda": 2,
    "Ramo": "vulputate dui, nec",
    "Indole": "Pulvinar Arcu Et Foundation",
    "Negocio": "Facilisis Magna Tellus Consulting",
    "Cedente": "Lacus Industries",
    "AsegAfian": "Mollis Nec Cursus Incorporated",
    "Suscriptor": "Donec Foundation",
    "vigdesde": "06-11-20",
    "vighasta": "05-18-21",
    "estado": "lorem,",
    "Nuevo": "true",
    "Usuario": "Arthur",
    "Poliza": "J1C 2N3"
  },
  {
    "factura": 38,
    "serie": 18,
    "exp": 2338,
    "Fe_registro": "06-06-21",
    "Domicilio": "278-3164 Accumsan ",
    "Moneda": 6,
    "Ramo": "tristique aliquet. Phasellus",
    "Indole": "Tellus Justo Industries",
    "Negocio": "Pharetra Nam Industries",
    "Cedente": "Eget Venenatis LLP",
    "AsegAfian": "Duis Risus Odio Institute",
    "Suscriptor": "Nunc Sed Corporation",
    "vigdesde": "09-23-20",
    "vighasta": "05-29-22",
    "estado": "lorem",
    "Nuevo": "false",
    "Usuario": "Paki",
    "Poliza": "U1X 8S4"
  },
  {
    "factura": 39,
    "serie": 10,
    "exp": 2217,
    "Fe_registro": "02-02-21",
    "Domicilio": "Apartado núm.: 537, 1956 Nec, Ctra.",
    "Moneda": 1,
    "Ramo": "sapien.",
    "Indole": "Donec Luctus Aliquet Company",
    "Negocio": "Aliquet Diam Sed Institute",
    "Cedente": "Praesent Corporation",
    "AsegAfian": "Diam Proin Dolor Associates",
    "Suscriptor": "Penatibus Et Magnis Inc.",
    "vigdesde": "11-07-20",
    "vighasta": "12-19-22",
    "estado": "elit",
    "Nuevo": "false",
    "Usuario": "Richard",
    "Poliza": "G7R 2N8"
  },
  {
    "factura": 40,
    "serie": 10,
    "exp": 2293,
    "Fe_registro": "12-22-20",
    "Domicilio": "3130 Proin Avda.",
    "Moneda": 7,
    "Ramo": "vulputate, posuere vulputate,",
    "Indole": "Etiam PC",
    "Negocio": "Malesuada Fames Ac Industries",
    "Cedente": "Egestas Urna LLC",
    "AsegAfian": "Est Mollis Limited",
    "Suscriptor": "Nulla LLP",
    "vigdesde": "08-04-20",
    "vighasta": "12-30-21",
    "estado": "elit",
    "Nuevo": "false",
    "Usuario": "Sebastian",
    "Poliza": "S8B 0Q3"
  },
  {
    "factura": 41,
    "serie": 15,
    "exp": 2215,
    "Fe_registro": "01-22-20",
    "Domicilio": "Apdo.:243-1858 Et, Avda.",
    "Moneda": 7,
    "Ramo": "a nunc.",
    "Indole": "Tincidunt Tempus Risus Inc.",
    "Negocio": "Pellentesque A Limited",
    "Cedente": "Erat Sed Nunc Consulting",
    "AsegAfian": "Vel Faucibus Associates",
    "Suscriptor": "Diam Corporation",
    "vigdesde": "12-09-20",
    "vighasta": "04-17-21",
    "estado": "Fusce",
    "Nuevo": "false",
    "Usuario": "Jamal",
    "Poliza": "J0A 0G0"
  },
  {
    "factura": 42,
    "serie": 17,
    "exp": 2332,
    "Fe_registro": "01-01-20",
    "Domicilio": "917-7963 Enim Av.",
    "Moneda": 6,
    "Ramo": "facilisi. Sed neque.",
    "Indole": "Gravida Praesent Industries",
    "Negocio": "Fusce Mollis Duis Corp.",
    "Cedente": "A LLC",
    "AsegAfian": "Nullam Incorporated",
    "Suscriptor": "Torquent Per Incorporated",
    "vigdesde": "04-03-20",
    "vighasta": "07-05-21",
    "estado": "et,",
    "Nuevo": "false",
    "Usuario": "Blaze",
    "Poliza": "E8R 8R3"
  },
  {
    "factura": 43,
    "serie": 18,
    "exp": 2302,
    "Fe_registro": "12-16-21",
    "Domicilio": "Apartado núm.: 159, 5325 Dictum C.",
    "Moneda": 4,
    "Ramo": "diam. Proin",
    "Indole": "Nonummy Foundation",
    "Negocio": "Tortor Nunc Incorporated",
    "Cedente": "Dui In Institute",
    "AsegAfian": "Eu Consulting",
    "Suscriptor": "Metus Ltd",
    "vigdesde": "06-29-20",
    "vighasta": "10-27-21",
    "estado": "nisi",
    "Nuevo": "false",
    "Usuario": "Kennan",
    "Poliza": "G8I 3B8"
  },
  {
    "factura": 44,
    "serie": 13,
    "exp": 2299,
    "Fe_registro": "05-07-21",
    "Domicilio": "Apartado núm.: 784, 9608 Cras Carretera",
    "Moneda": 6,
    "Ramo": "ligula consectetuer",
    "Indole": "Nec Limited",
    "Negocio": "Tristique Consulting",
    "Cedente": "Sed Eu LLC",
    "AsegAfian": "Nunc Sed PC",
    "Suscriptor": "Arcu Curabitur Ut Corporation",
    "vigdesde": "12-12-20",
    "vighasta": "10-21-21",
    "estado": "hendrerit",
    "Nuevo": "true",
    "Usuario": "Bradley",
    "Poliza": "W2O 9N0"
  },
  {
    "factura": 45,
    "serie": 20,
    "exp": 2248,
    "Fe_registro": "04-21-21",
    "Domicilio": "352-4746 Eu Ctra.",
    "Moneda": 4,
    "Ramo": "libero",
    "Indole": "Tempus Foundation",
    "Negocio": "Nisi LLP",
    "Cedente": "Netus Et Malesuada Corp.",
    "AsegAfian": "Vehicula Aliquet Industries",
    "Suscriptor": "Curae; Donec Company",
    "vigdesde": "09-17-20",
    "vighasta": "04-12-21",
    "estado": "et,",
    "Nuevo": "false",
    "Usuario": "Baxter",
    "Poliza": "O6W 2U4"
  },
  {
    "factura": 46,
    "serie": 14,
    "exp": 2377,
    "Fe_registro": "03-11-20",
    "Domicilio": "Apartado núm.: 336, 6796 Metus ",
    "Moneda": 7,
    "Ramo": "fringilla",
    "Indole": "Iaculis Quis PC",
    "Negocio": "Diam Pellentesque LLP",
    "Cedente": "Ridiculus Mus Consulting",
    "AsegAfian": "Mauris Eu Limited",
    "Suscriptor": "Egestas Company",
    "vigdesde": "03-27-20",
    "vighasta": "10-04-21",
    "estado": "Proin",
    "Nuevo": "true",
    "Usuario": "Talon",
    "Poliza": "Q6O 0Q0"
  },
  {
    "factura": 47,
    "serie": 19,
    "exp": 2226,
    "Fe_registro": "07-17-20",
    "Domicilio": "Apdo.:513-7386 Sem Av.",
    "Moneda": 5,
    "Ramo": "Aliquam tincidunt,",
    "Indole": "Et Nunc Incorporated",
    "Negocio": "In Industries",
    "Cedente": "Natoque Company",
    "AsegAfian": "Sem Eget Ltd",
    "Suscriptor": "Parturient Montes Nascetur Company",
    "vigdesde": "07-31-20",
    "vighasta": "07-26-22",
    "estado": "ridiculus",
    "Nuevo": "false",
    "Usuario": "Isaiah",
    "Poliza": "E4U 0K6"
  },
  {
    "factura": 48,
    "serie": 20,
    "exp": 2248,
    "Fe_registro": "05-12-20",
    "Domicilio": "377 Ut Avenida",
    "Moneda": 3,
    "Ramo": "massa. Quisque porttitor",
    "Indole": "Donec At Inc.",
    "Negocio": "Id Blandit At Company",
    "Cedente": "Faucibus Orci Luctus Incorporated",
    "AsegAfian": "Mi Foundation",
    "Suscriptor": "Suscipit Corp.",
    "vigdesde": "03-31-20",
    "vighasta": "08-13-22",
    "estado": "tincidunt,",
    "Nuevo": "true",
    "Usuario": "Bruce",
    "Poliza": "Z7C 5K4"
  },
  {
    "factura": 49,
    "serie": 18,
    "exp": 2278,
    "Fe_registro": "03-04-20",
    "Domicilio": "Apdo.:255-462 Risus. Avenida",
    "Moneda": 1,
    "Ramo": "Cras dolor dolor,",
    "Indole": "Nunc Mauris Foundation",
    "Negocio": "Dui Quis Foundation",
    "Cedente": "Tortor Integer Aliquam Corporation",
    "AsegAfian": "Semper Tellus Id Associates",
    "Suscriptor": "Metus Associates",
    "vigdesde": "05-17-20",
    "vighasta": "11-16-21",
    "estado": "sem",
    "Nuevo": "false",
    "Usuario": "Alvin",
    "Poliza": "D1T 9Q6"
  },
  {
    "factura": 50,
    "serie": 15,
    "exp": 2261,
    "Fe_registro": "08-17-20",
    "Domicilio": "Apartado núm.: 700, 2536 Etiam Avda.",
    "Moneda": 2,
    "Ramo": "orci",
    "Indole": "Auctor Odio Limited",
    "Negocio": "Enim Diam LLC",
    "Cedente": "Primis Company",
    "AsegAfian": "Mi Fringilla Associates",
    "Suscriptor": "Mi Tempor Lorem Consulting",
    "vigdesde": "05-08-20",
    "vighasta": "10-17-21",
    "estado": "amet,",
    "Nuevo": "true",
    "Usuario": "Bruce",
    "Poliza": "O2H 2E6"
  },
  {
    "factura": 51,
    "serie": 20,
    "exp": 2342,
    "Fe_registro": "10-05-21",
    "Domicilio": "Apdo.:871-2354 Fringilla ",
    "Moneda": 6,
    "Ramo": "lacus,",
    "Indole": "Penatibus Et Inc.",
    "Negocio": "Sagittis Felis Donec Foundation",
    "Cedente": "Magna A Corp.",
    "AsegAfian": "Donec Fringilla LLC",
    "Suscriptor": "Dolor Quisque Tincidunt Ltd",
    "vigdesde": "02-22-20",
    "vighasta": "10-02-22",
    "estado": "risus,",
    "Nuevo": "true",
    "Usuario": "Kenneth",
    "Poliza": "M9C 1Z7"
  },
  {
    "factura": 52,
    "serie": 15,
    "exp": 2327,
    "Fe_registro": "09-04-20",
    "Domicilio": "3364 Elit. Avda.",
    "Moneda": 1,
    "Ramo": "Morbi",
    "Indole": "Ornare Sagittis Felis Institute",
    "Negocio": "Curabitur PC",
    "Cedente": "Tellus Corp.",
    "AsegAfian": "Scelerisque Dui Suspendisse PC",
    "Suscriptor": "Nunc Lectus Pede Institute",
    "vigdesde": "10-18-20",
    "vighasta": "08-08-21",
    "estado": "leo.",
    "Nuevo": "true",
    "Usuario": "Peter",
    "Poliza": "B9P 8R0"
  },
  {
    "factura": 53,
    "serie": 17,
    "exp": 2204,
    "Fe_registro": "04-07-20",
    "Domicilio": "803-9840 Faucibus Calle",
    "Moneda": 4,
    "Ramo": "eu",
    "Indole": "Malesuada Incorporated",
    "Negocio": "Iaculis Lacus Corp.",
    "Cedente": "Vestibulum Ut LLC",
    "AsegAfian": "Nec Ligula Consectetuer LLP",
    "Suscriptor": "Dictum Foundation",
    "vigdesde": "07-15-20",
    "vighasta": "03-02-22",
    "estado": "ultrices.",
    "Nuevo": "false",
    "Usuario": "Jeremy",
    "Poliza": "W3N 5V6"
  },
  {
    "factura": 54,
    "serie": 19,
    "exp": 2226,
    "Fe_registro": "09-01-21",
    "Domicilio": "Apdo.:211-948 Tempor Ctra.",
    "Moneda": 2,
    "Ramo": "magna. Phasellus dolor",
    "Indole": "Aenean Ltd",
    "Negocio": "Tortor Incorporated",
    "Cedente": "Nulla Cras Eu Ltd",
    "AsegAfian": "Leo Cras Inc.",
    "Suscriptor": "A Sollicitudin Industries",
    "vigdesde": "01-04-20",
    "vighasta": "10-04-22",
    "estado": "non",
    "Nuevo": "true",
    "Usuario": "Salvador",
    "Poliza": "Q4B 2K7"
  },
  {
    "factura": 55,
    "serie": 19,
    "exp": 2266,
    "Fe_registro": "01-10-20",
    "Domicilio": "Apdo.:998-415 Porta Carretera",
    "Moneda": 6,
    "Ramo": "molestie dapibus ligula.",
    "Indole": "Vivamus Euismod Urna Ltd",
    "Negocio": "Facilisis Facilisis Magna Company",
    "Cedente": "Ultrices Vivamus Rhoncus Foundation",
    "AsegAfian": "Orci Lobortis Foundation",
    "Suscriptor": "Etiam Vestibulum Massa Consulting",
    "vigdesde": "06-03-20",
    "vighasta": "05-02-22",
    "estado": "diam",
    "Nuevo": "true",
    "Usuario": "Chester",
    "Poliza": "S2X 3M9"
  },
  {
    "factura": 56,
    "serie": 12,
    "exp": 2205,
    "Fe_registro": "02-21-20",
    "Domicilio": "281-5648 Primis Calle",
    "Moneda": 7,
    "Ramo": "venenatis lacus.",
    "Indole": "Consectetuer LLP",
    "Negocio": "Neque Company",
    "Cedente": "Non Massa Non LLP",
    "AsegAfian": "Quam Curabitur Vel Associates",
    "Suscriptor": "Elit Pretium LLP",
    "vigdesde": "07-14-20",
    "vighasta": "11-10-22",
    "estado": "malesuada",
    "Nuevo": "false",
    "Usuario": "Hasad",
    "Poliza": "W3F 8S0"
  },
  {
    "factura": 57,
    "serie": 17,
    "exp": 2275,
    "Fe_registro": "06-02-20",
    "Domicilio": "338-7931 Imperdiet Ctra.",
    "Moneda": 4,
    "Ramo": "lacus.",
    "Indole": "Blandit Enim Limited",
    "Negocio": "Dictum Proin Corp.",
    "Cedente": "Etiam Associates",
    "AsegAfian": "Consequat Associates",
    "Suscriptor": "Dictum Industries",
    "vigdesde": "12-11-20",
    "vighasta": "01-05-22",
    "estado": "dolor,",
    "Nuevo": "false",
    "Usuario": "Cairo",
    "Poliza": "W0Z 4D7"
  },
  {
    "factura": 58,
    "serie": 17,
    "exp": 2276,
    "Fe_registro": "02-09-20",
    "Domicilio": "Apartado núm.: 141, 5740 At, Carretera",
    "Moneda": 1,
    "Ramo": "nibh.",
    "Indole": "Posuere Corporation",
    "Negocio": "Nec Cursus A Associates",
    "Cedente": "Et Ultrices Posuere LLP",
    "AsegAfian": "Mauris Inc.",
    "Suscriptor": "Nunc Mauris Ltd",
    "vigdesde": "05-14-20",
    "vighasta": "04-19-22",
    "estado": "amet",
    "Nuevo": "false",
    "Usuario": "Beck",
    "Poliza": "U5Y 2R2"
  },
  {
    "factura": 59,
    "serie": 14,
    "exp": 2318,
    "Fe_registro": "12-26-21",
    "Domicilio": "1956 Donec Avda.",
    "Moneda": 4,
    "Ramo": "posuere at, velit.",
    "Indole": "Diam Nunc Corp.",
    "Negocio": "Faucibus Associates",
    "Cedente": "Est Congue A Institute",
    "AsegAfian": "Eu Ultrices PC",
    "Suscriptor": "Diam Ltd",
    "vigdesde": "06-10-20",
    "vighasta": "02-25-22",
    "estado": "tincidunt",
    "Nuevo": "true",
    "Usuario": "Baxter",
    "Poliza": "Z1T 2X7"
  },
  {
    "factura": 60,
    "serie": 18,
    "exp": 2299,
    "Fe_registro": "11-24-20",
    "Domicilio": "4890 Nec C.",
    "Moneda": 2,
    "Ramo": "luctus",
    "Indole": "Consectetuer Cursus Institute",
    "Negocio": "Integer Associates",
    "Cedente": "Nunc PC",
    "AsegAfian": "Et Netus Et Ltd",
    "Suscriptor": "Phasellus Dolor Elit Institute",
    "vigdesde": "05-26-20",
    "vighasta": "11-22-22",
    "estado": "eu",
    "Nuevo": "false",
    "Usuario": "Reese",
    "Poliza": "Z4Z 6A3"
  },
  {
    "factura": 61,
    "serie": 10,
    "exp": 2282,
    "Fe_registro": "01-16-21",
    "Domicilio": "Apdo.:678-5399 Non ",
    "Moneda": 2,
    "Ramo": "felis. Donec",
    "Indole": "Ut Molestie In LLC",
    "Negocio": "A Neque Nullam Consulting",
    "Cedente": "Nec Associates",
    "AsegAfian": "Consequat Nec Mollis Consulting",
    "Suscriptor": "Nam PC",
    "vigdesde": "08-18-20",
    "vighasta": "09-13-21",
    "estado": "fermentum",
    "Nuevo": "false",
    "Usuario": "Moses",
    "Poliza": "K1I 2Y7"
  },
  {
    "factura": 62,
    "serie": 14,
    "exp": 2251,
    "Fe_registro": "06-15-20",
    "Domicilio": "846-6518 Magna. Avda.",
    "Moneda": 1,
    "Ramo": "nec, eleifend non,",
    "Indole": "Lectus Nullam Corporation",
    "Negocio": "Sed Dictum Limited",
    "Cedente": "Orci Adipiscing PC",
    "AsegAfian": "Non Corporation",
    "Suscriptor": "Vulputate Ullamcorper Industries",
    "vigdesde": "04-07-20",
    "vighasta": "04-17-21",
    "estado": "adipiscing",
    "Nuevo": "true",
    "Usuario": "Vladimir",
    "Poliza": "G3B 3I7"
  },
  {
    "factura": 63,
    "serie": 19,
    "exp": 2279,
    "Fe_registro": "03-22-20",
    "Domicilio": "Apdo.:287-2098 Libero. Av.",
    "Moneda": 2,
    "Ramo": "natoque penatibus et",
    "Indole": "Aliquet Metus Incorporated",
    "Negocio": "Nibh Enim Gravida Company",
    "Cedente": "Pede Suspendisse Dui Inc.",
    "AsegAfian": "Sed Malesuada Corp.",
    "Suscriptor": "Quis Pede LLC",
    "vigdesde": "01-23-20",
    "vighasta": "04-26-21",
    "estado": "semper.",
    "Nuevo": "false",
    "Usuario": "Knox",
    "Poliza": "X4C 4B6"
  },
  {
    "factura": 64,
    "serie": 15,
    "exp": 2215,
    "Fe_registro": "05-05-20",
    "Domicilio": "Apdo.:952-8492 Eleifend Carretera",
    "Moneda": 2,
    "Ramo": "Duis dignissim tempor",
    "Indole": "Aliquet LLP",
    "Negocio": "Eleifend Vitae Erat Associates",
    "Cedente": "Id Nunc Associates",
    "AsegAfian": "Dolor Donec Consulting",
    "Suscriptor": "Faucibus Lectus Ltd",
    "vigdesde": "11-15-20",
    "vighasta": "01-12-22",
    "estado": "elit.",
    "Nuevo": "true",
    "Usuario": "Yardley",
    "Poliza": "E6X 6K0"
  },
  {
    "factura": 65,
    "serie": 15,
    "exp": 2347,
    "Fe_registro": "05-16-20",
    "Domicilio": "868-7023 Cum Avda.",
    "Moneda": 7,
    "Ramo": "et magnis dis",
    "Indole": "Felis Ullamcorper Corporation",
    "Negocio": "Lorem Tristique Corp.",
    "Cedente": "Arcu Vivamus PC",
    "AsegAfian": "Rutrum Justo Corp.",
    "Suscriptor": "Dolor Egestas Associates",
    "vigdesde": "11-25-20",
    "vighasta": "11-05-21",
    "estado": "Nam",
    "Nuevo": "false",
    "Usuario": "Yasir",
    "Poliza": "E4J 9J2"
  },
  {
    "factura": 66,
    "serie": 19,
    "exp": 2386,
    "Fe_registro": "01-02-20",
    "Domicilio": "6545 Scelerisque Av.",
    "Moneda": 2,
    "Ramo": "leo. Cras vehicula",
    "Indole": "In Sodales Corp.",
    "Negocio": "Viverra Donec Tempus Inc.",
    "Cedente": "Suscipit Nonummy Fusce Limited",
    "AsegAfian": "Phasellus Vitae Institute",
    "Suscriptor": "Curabitur Ut Odio Corporation",
    "vigdesde": "08-02-20",
    "vighasta": "10-06-22",
    "estado": "varius.",
    "Nuevo": "false",
    "Usuario": "Joseph",
    "Poliza": "Z6N 3T9"
  },
  {
    "factura": 67,
    "serie": 17,
    "exp": 2307,
    "Fe_registro": "09-28-20",
    "Domicilio": "Apdo.:200-6802 Penatibus Ctra.",
    "Moneda": 7,
    "Ramo": "mauris, rhoncus id,",
    "Indole": "Ut Nisi A Company",
    "Negocio": "At Pede Cras Company",
    "Cedente": "Cras Foundation",
    "AsegAfian": "Ligula Elit Company",
    "Suscriptor": "Urna Incorporated",
    "vigdesde": "01-06-20",
    "vighasta": "10-27-22",
    "estado": "id",
    "Nuevo": "false",
    "Usuario": "Akeem",
    "Poliza": "S2S 6Q4"
  },
  {
    "factura": 68,
    "serie": 11,
    "exp": 2337,
    "Fe_registro": "10-23-21",
    "Domicilio": "9719 Morbi Ctra.",
    "Moneda": 5,
    "Ramo": "magnis dis parturient",
    "Indole": "Arcu Aliquam Consulting",
    "Negocio": "In Dolor Fusce Associates",
    "Cedente": "Aenean Inc.",
    "AsegAfian": "Mi Felis Adipiscing Inc.",
    "Suscriptor": "Magna Corp.",
    "vigdesde": "10-19-20",
    "vighasta": "03-21-22",
    "estado": "elit",
    "Nuevo": "false",
    "Usuario": "Merritt",
    "Poliza": "S1F 8Z0"
  },
  {
    "factura": 69,
    "serie": 13,
    "exp": 2318,
    "Fe_registro": "02-22-20",
    "Domicilio": "7928 Donec Av.",
    "Moneda": 1,
    "Ramo": "lobortis, nisi nibh",
    "Indole": "Et Ipsum Associates",
    "Negocio": "Eu Company",
    "Cedente": "Integer Inc.",
    "AsegAfian": "Aenean Massa Integer LLC",
    "Suscriptor": "Augue Limited",
    "vigdesde": "09-24-20",
    "vighasta": "08-03-21",
    "estado": "lobortis,",
    "Nuevo": "true",
    "Usuario": "Neville",
    "Poliza": "B3L 8A4"
  },
  {
    "factura": 70,
    "serie": 11,
    "exp": 2335,
    "Fe_registro": "04-19-20",
    "Domicilio": "Apdo.:208-3937 Ut Av.",
    "Moneda": 5,
    "Ramo": "In tincidunt",
    "Indole": "Turpis Nec Associates",
    "Negocio": "Tincidunt Foundation",
    "Cedente": "Mauris Limited",
    "AsegAfian": "Vel Consulting",
    "Suscriptor": "Lacus Pede Sagittis Associates",
    "vigdesde": "10-22-20",
    "vighasta": "06-28-22",
    "estado": "cursus",
    "Nuevo": "false",
    "Usuario": "Carlos",
    "Poliza": "J0R 0D3"
  },
  {
    "factura": 71,
    "serie": 13,
    "exp": 2260,
    "Fe_registro": "06-26-20",
    "Domicilio": "Apartado núm.: 422, 2139 Faucibus Av.",
    "Moneda": 2,
    "Ramo": "metus",
    "Indole": "In Cursus Inc.",
    "Negocio": "Nec Urna Suscipit LLC",
    "Cedente": "Lectus Nullam LLC",
    "AsegAfian": "Felis Orci LLP",
    "Suscriptor": "Sit Amet Ante Corp.",
    "vigdesde": "02-05-20",
    "vighasta": "12-27-22",
    "estado": "In",
    "Nuevo": "true",
    "Usuario": "Rashad",
    "Poliza": "M0X 2E8"
  },
  {
    "factura": 72,
    "serie": 14,
    "exp": 2393,
    "Fe_registro": "03-21-21",
    "Domicilio": "762-6609 Est Ctra.",
    "Moneda": 2,
    "Ramo": "ornare",
    "Indole": "Nisi LLP",
    "Negocio": "Arcu Ltd",
    "Cedente": "Facilisis Inc.",
    "AsegAfian": "Quam Quis Industries",
    "Suscriptor": "Ligula Aliquam Erat Company",
    "vigdesde": "04-21-20",
    "vighasta": "04-15-21",
    "estado": "luctus.",
    "Nuevo": "true",
    "Usuario": "Flynn",
    "Poliza": "D5E 6V5"
  },
  {
    "factura": 73,
    "serie": 10,
    "exp": 2386,
    "Fe_registro": "08-26-21",
    "Domicilio": "6621 Consectetuer, C/",
    "Moneda": 6,
    "Ramo": "Donec consectetuer mauris",
    "Indole": "Risus Duis A Company",
    "Negocio": "Auctor Ullamcorper Nisl Institute",
    "Cedente": "Mauris Industries",
    "AsegAfian": "Eu Nibh Vulputate Ltd",
    "Suscriptor": "Nascetur Ridiculus LLC",
    "vigdesde": "10-27-20",
    "vighasta": "03-06-21",
    "estado": "semper,",
    "Nuevo": "true",
    "Usuario": "Andrew",
    "Poliza": "K7C 0Z5"
  },
  {
    "factura": 74,
    "serie": 15,
    "exp": 2219,
    "Fe_registro": "02-27-20",
    "Domicilio": "603-6549 Nunc C/",
    "Moneda": 1,
    "Ramo": "sit amet",
    "Indole": "Vitae Incorporated",
    "Negocio": "Netus Corporation",
    "Cedente": "Sed Limited",
    "AsegAfian": "Placerat Industries",
    "Suscriptor": "Risus Donec PC",
    "vigdesde": "08-25-20",
    "vighasta": "12-02-22",
    "estado": "urna",
    "Nuevo": "false",
    "Usuario": "Lewis",
    "Poliza": "Z6H 1Y4"
  },
  {
    "factura": 75,
    "serie": 13,
    "exp": 2244,
    "Fe_registro": "02-11-21",
    "Domicilio": "6935 Aenean Av.",
    "Moneda": 6,
    "Ramo": "urna convallis erat,",
    "Indole": "Pede Nonummy Ut Consulting",
    "Negocio": "Tellus Ltd",
    "Cedente": "Blandit At Nisi Inc.",
    "AsegAfian": "Id Corp.",
    "Suscriptor": "Feugiat Non Lobortis PC",
    "vigdesde": "06-27-20",
    "vighasta": "06-22-21",
    "estado": "risus.",
    "Nuevo": "true",
    "Usuario": "Howard",
    "Poliza": "J9E 0W6"
  },
  {
    "factura": 76,
    "serie": 10,
    "exp": 2240,
    "Fe_registro": "04-02-20",
    "Domicilio": "Apartado núm.: 924, 309 Vehicula C/",
    "Moneda": 4,
    "Ramo": "mauris elit,",
    "Indole": "Consectetuer Adipiscing Corporation",
    "Negocio": "Turpis Corporation",
    "Cedente": "Mauris LLP",
    "AsegAfian": "Eu Consulting",
    "Suscriptor": "Tempus Eu Ligula Associates",
    "vigdesde": "10-30-20",
    "vighasta": "07-06-22",
    "estado": "imperdiet",
    "Nuevo": "false",
    "Usuario": "Zeus",
    "Poliza": "B2P 8F4"
  },
  {
    "factura": 77,
    "serie": 14,
    "exp": 2264,
    "Fe_registro": "04-02-21",
    "Domicilio": "582-5975 Neque. Avda.",
    "Moneda": 5,
    "Ramo": "nulla",
    "Indole": "Vel Quam Dignissim Company",
    "Negocio": "Vel Inc.",
    "Cedente": "Velit Eu Sem Company",
    "AsegAfian": "Donec Porttitor Tellus Company",
    "Suscriptor": "Pharetra Ut Pharetra Company",
    "vigdesde": "04-01-20",
    "vighasta": "05-07-21",
    "estado": "felis.",
    "Nuevo": "true",
    "Usuario": "Vaughan",
    "Poliza": "F2J 1X7"
  },
  {
    "factura": 78,
    "serie": 19,
    "exp": 2326,
    "Fe_registro": "07-27-20",
    "Domicilio": "885-6099 Scelerisque Calle",
    "Moneda": 4,
    "Ramo": "Sed eget",
    "Indole": "Facilisis Lorem Incorporated",
    "Negocio": "Pharetra Nam Company",
    "Cedente": "Ultricies Ornare Elit Industries",
    "AsegAfian": "A Foundation",
    "Suscriptor": "Non LLP",
    "vigdesde": "06-23-20",
    "vighasta": "11-04-22",
    "estado": "a,",
    "Nuevo": "true",
    "Usuario": "Gray",
    "Poliza": "M3S 2A5"
  },
  {
    "factura": 79,
    "serie": 10,
    "exp": 2369,
    "Fe_registro": "08-14-20",
    "Domicilio": "Apdo.:238-8397 Ac Ctra.",
    "Moneda": 2,
    "Ramo": "egestas ligula.",
    "Indole": "Pede Corp.",
    "Negocio": "Mauris Inc.",
    "Cedente": "Pede Sagittis Augue Foundation",
    "AsegAfian": "Non Associates",
    "Suscriptor": "Non Limited",
    "vigdesde": "03-04-20",
    "vighasta": "11-22-22",
    "estado": "et",
    "Nuevo": "true",
    "Usuario": "Graham",
    "Poliza": "D3Y 2M1"
  },
  {
    "factura": 80,
    "serie": 10,
    "exp": 2255,
    "Fe_registro": "11-17-20",
    "Domicilio": "9514 Aliquet Carretera",
    "Moneda": 3,
    "Ramo": "aliquet libero.",
    "Indole": "Erat Etiam Vestibulum LLC",
    "Negocio": "Est Nunc Laoreet Institute",
    "Cedente": "Suspendisse Ltd",
    "AsegAfian": "Feugiat Lorem Ipsum PC",
    "Suscriptor": "Sed Corp.",
    "vigdesde": "01-17-20",
    "vighasta": "04-10-21",
    "estado": "et,",
    "Nuevo": "false",
    "Usuario": "Wang",
    "Poliza": "F2E 2G0"
  },
  {
    "factura": 81,
    "serie": 14,
    "exp": 2300,
    "Fe_registro": "08-10-20",
    "Domicilio": "Apartado núm.: 900, 4542 Eget C/",
    "Moneda": 4,
    "Ramo": "metus. Aliquam",
    "Indole": "Aliquet Lobortis Nisi Company",
    "Negocio": "Non Lobortis Quis LLP",
    "Cedente": "Molestie Arcu Sed Ltd",
    "AsegAfian": "Elit Inc.",
    "Suscriptor": "Cursus Luctus Ipsum Limited",
    "vigdesde": "10-09-20",
    "vighasta": "11-13-21",
    "estado": "iaculis",
    "Nuevo": "false",
    "Usuario": "Driscoll",
    "Poliza": "F3I 6W2"
  },
  {
    "factura": 82,
    "serie": 20,
    "exp": 2291,
    "Fe_registro": "06-05-21",
    "Domicilio": "Apdo.:103-295 Non, C.",
    "Moneda": 3,
    "Ramo": "lacus.",
    "Indole": "Ipsum Suspendisse Company",
    "Negocio": "Elementum Sem Vitae Institute",
    "Cedente": "Dictum Eleifend Inc.",
    "AsegAfian": "Ac Turpis LLC",
    "Suscriptor": "Diam Duis Foundation",
    "vigdesde": "02-13-20",
    "vighasta": "04-11-21",
    "estado": "fames",
    "Nuevo": "false",
    "Usuario": "Hakeem",
    "Poliza": "R0V 5G2"
  },
  {
    "factura": 83,
    "serie": 19,
    "exp": 2214,
    "Fe_registro": "05-14-20",
    "Domicilio": "Apartado núm.: 857, 2470 Et Calle",
    "Moneda": 7,
    "Ramo": "consectetuer",
    "Indole": "Lorem Ut Aliquam Corp.",
    "Negocio": "Imperdiet Associates",
    "Cedente": "Enim PC",
    "AsegAfian": "At Sem Molestie Inc.",
    "Suscriptor": "Eu Tempor Erat Industries",
    "vigdesde": "11-22-20",
    "vighasta": "04-11-21",
    "estado": "suscipit,",
    "Nuevo": "false",
    "Usuario": "Ashton",
    "Poliza": "T9W 7M5"
  },
  {
    "factura": 84,
    "serie": 17,
    "exp": 2331,
    "Fe_registro": "11-10-21",
    "Domicilio": "Apdo.:791-5734 Tortor Av.",
    "Moneda": 7,
    "Ramo": "enim. Mauris quis",
    "Indole": "Ut Tincidunt Vehicula Foundation",
    "Negocio": "Aliquam Eros PC",
    "Cedente": "Metus Corporation",
    "AsegAfian": "Integer Sem Industries",
    "Suscriptor": "Suspendisse Tristique Foundation",
    "vigdesde": "07-08-20",
    "vighasta": "04-19-22",
    "estado": "Mauris",
    "Nuevo": "false",
    "Usuario": "Ian",
    "Poliza": "P1P 5M5"
  },
  {
    "factura": 85,
    "serie": 11,
    "exp": 2289,
    "Fe_registro": "04-07-21",
    "Domicilio": "Apartado núm.: 728, 9225 Sollicitudin Calle",
    "Moneda": 3,
    "Ramo": "eleifend non, dapibus",
    "Indole": "Vel Nisl Associates",
    "Negocio": "Euismod Industries",
    "Cedente": "Fusce Aliquam Enim Limited",
    "AsegAfian": "Ante Lectus Convallis Corporation",
    "Suscriptor": "Ornare Egestas Ligula LLC",
    "vigdesde": "08-15-20",
    "vighasta": "11-05-22",
    "estado": "penatibus",
    "Nuevo": "true",
    "Usuario": "Allistair",
    "Poliza": "D9T 2P0"
  },
  {
    "factura": 86,
    "serie": 17,
    "exp": 2235,
    "Fe_registro": "12-23-20",
    "Domicilio": "7600 Eu, Ctra.",
    "Moneda": 1,
    "Ramo": "nisi. Mauris nulla.",
    "Indole": "Convallis LLP",
    "Negocio": "Viverra Maecenas PC",
    "Cedente": "Eu Eleifend Nec Consulting",
    "AsegAfian": "Ipsum Consulting",
    "Suscriptor": "Senectus Et Netus Corporation",
    "vigdesde": "03-25-20",
    "vighasta": "11-21-21",
    "estado": "nec,",
    "Nuevo": "false",
    "Usuario": "Preston",
    "Poliza": "Z0K 6W3"
  },
  {
    "factura": 87,
    "serie": 18,
    "exp": 2269,
    "Fe_registro": "01-27-21",
    "Domicilio": "9775 Luctus Avenida",
    "Moneda": 6,
    "Ramo": "risus. Quisque libero",
    "Indole": "Mauris Aliquam Consulting",
    "Negocio": "Ullamcorper Eu Euismod Inc.",
    "Cedente": "Lobortis Inc.",
    "AsegAfian": "Eu Metus Limited",
    "Suscriptor": "Dolor Egestas LLP",
    "vigdesde": "09-21-20",
    "vighasta": "04-06-22",
    "estado": "penatibus",
    "Nuevo": "false",
    "Usuario": "Abraham",
    "Poliza": "H3Y 6D0"
  },
  {
    "factura": 88,
    "serie": 14,
    "exp": 2239,
    "Fe_registro": "01-20-20",
    "Domicilio": "9460 Adipiscing Avda.",
    "Moneda": 3,
    "Ramo": "quis,",
    "Indole": "Et Pede Foundation",
    "Negocio": "Dolor Fusce Feugiat LLP",
    "Cedente": "Commodo PC",
    "AsegAfian": "Aenean Ltd",
    "Suscriptor": "Semper Nam Institute",
    "vigdesde": "06-12-20",
    "vighasta": "07-12-22",
    "estado": "Phasellus",
    "Nuevo": "false",
    "Usuario": "Eaton",
    "Poliza": "G1E 3H2"
  },
  {
    "factura": 89,
    "serie": 11,
    "exp": 2385,
    "Fe_registro": "10-17-20",
    "Domicilio": "748-7949 Auctor C.",
    "Moneda": 4,
    "Ramo": "non nisi. Aenean",
    "Indole": "Felis Adipiscing Fringilla Ltd",
    "Negocio": "Massa Foundation",
    "Cedente": "Suspendisse Aliquet Ltd",
    "AsegAfian": "Penatibus Et Foundation",
    "Suscriptor": "Cursus Nunc Mauris Corp.",
    "vigdesde": "05-24-20",
    "vighasta": "08-01-21",
    "estado": "Sed",
    "Nuevo": "false",
    "Usuario": "Xavier",
    "Poliza": "V5X 7V5"
  },
  {
    "factura": 90,
    "serie": 11,
    "exp": 2243,
    "Fe_registro": "02-18-21",
    "Domicilio": "151-3494 Aliquam Avenida",
    "Moneda": 6,
    "Ramo": "tellus",
    "Indole": "Leo Vivamus Nibh Associates",
    "Negocio": "Lacinia Ltd",
    "Cedente": "Nunc Risus Varius Associates",
    "AsegAfian": "Sed Facilisis Vitae Corp.",
    "Suscriptor": "Montes Corp.",
    "vigdesde": "11-18-20",
    "vighasta": "07-21-22",
    "estado": "imperdiet,",
    "Nuevo": "false",
    "Usuario": "Kevin",
    "Poliza": "V9L 0T0"
  },
  {
    "factura": 91,
    "serie": 19,
    "exp": 2394,
    "Fe_registro": "07-31-21",
    "Domicilio": "Apdo.:435-9177 Donec Carretera",
    "Moneda": 1,
    "Ramo": "molestie in, tempus",
    "Indole": "Faucibus PC",
    "Negocio": "Ultrices Iaculis Corporation",
    "Cedente": "Mi Felis Adipiscing Incorporated",
    "AsegAfian": "Nam Interdum Associates",
    "Suscriptor": "Nunc Sed Libero LLP",
    "vigdesde": "10-18-20",
    "vighasta": "07-31-22",
    "estado": "luctus",
    "Nuevo": "false",
    "Usuario": "August",
    "Poliza": "H1H 7R3"
  },
  {
    "factura": 92,
    "serie": 13,
    "exp": 2223,
    "Fe_registro": "11-26-20",
    "Domicilio": "239-361 Tempor, C/",
    "Moneda": 6,
    "Ramo": "cursus et, eros.",
    "Indole": "Eget Tincidunt Consulting",
    "Negocio": "Non Foundation",
    "Cedente": "Lacus PC",
    "AsegAfian": "Et LLC",
    "Suscriptor": "Pretium Aliquet Metus Company",
    "vigdesde": "03-11-20",
    "vighasta": "11-01-21",
    "estado": "rutrum",
    "Nuevo": "false",
    "Usuario": "Callum",
    "Poliza": "A5A 7Z9"
  },
  {
    "factura": 93,
    "serie": 13,
    "exp": 2350,
    "Fe_registro": "11-24-21",
    "Domicilio": "122-1372 Eu, C/",
    "Moneda": 1,
    "Ramo": "sem",
    "Indole": "Mollis Duis Inc.",
    "Negocio": "Fringilla LLP",
    "Cedente": "Blandit Enim Foundation",
    "AsegAfian": "Urna Justo Incorporated",
    "Suscriptor": "Proin Velit Sed Industries",
    "vigdesde": "12-08-20",
    "vighasta": "03-06-22",
    "estado": "auctor",
    "Nuevo": "false",
    "Usuario": "Keith",
    "Poliza": "O0K 3A2"
  },
  {
    "factura": 94,
    "serie": 20,
    "exp": 2210,
    "Fe_registro": "08-10-20",
    "Domicilio": "Apdo.:313-777 Lorem C/",
    "Moneda": 3,
    "Ramo": "leo, in",
    "Indole": "Et Nunc Quisque Incorporated",
    "Negocio": "Non Corp.",
    "Cedente": "Dolor LLC",
    "AsegAfian": "Mollis Company",
    "Suscriptor": "Ut Cursus LLC",
    "vigdesde": "01-23-20",
    "vighasta": "12-31-21",
    "estado": "interdum.",
    "Nuevo": "true",
    "Usuario": "Odysseus",
    "Poliza": "A3L 0U3"
  },
  {
    "factura": 95,
    "serie": 10,
    "exp": 2221,
    "Fe_registro": "03-09-21",
    "Domicilio": "Apartado núm.: 217, 9752 Tellus. Avenida",
    "Moneda": 1,
    "Ramo": "In faucibus. Morbi",
    "Indole": "Ornare Lectus Company",
    "Negocio": "Tempor Lorem Ltd",
    "Cedente": "Faucibus Limited",
    "AsegAfian": "Ut Semper Pretium Inc.",
    "Suscriptor": "Sagittis Company",
    "vigdesde": "05-12-20",
    "vighasta": "04-05-22",
    "estado": "urna.",
    "Nuevo": "false",
    "Usuario": "Salvador",
    "Poliza": "C8M 8Z4"
  },
  {
    "factura": 96,
    "serie": 11,
    "exp": 2303,
    "Fe_registro": "12-28-21",
    "Domicilio": "873-5552 Turpis. Avda.",
    "Moneda": 6,
    "Ramo": "dictum.",
    "Indole": "Ac Turpis Company",
    "Negocio": "Erat Industries",
    "Cedente": "Ipsum LLP",
    "AsegAfian": "Suscipit Nonummy Limited",
    "Suscriptor": "Gravida Incorporated",
    "vigdesde": "10-30-20",
    "vighasta": "02-10-22",
    "estado": "Suspendisse",
    "Nuevo": "true",
    "Usuario": "Hedley",
    "Poliza": "O2U 0M9"
  },
  {
    "factura": 97,
    "serie": 12,
    "exp": 2326,
    "Fe_registro": "09-23-21",
    "Domicilio": "499-3263 Vivamus C.",
    "Moneda": 3,
    "Ramo": "auctor velit.",
    "Indole": "Rutrum Magna Company",
    "Negocio": "Massa Lobortis Corp.",
    "Cedente": "Fames Ac Company",
    "AsegAfian": "Lorem Sit Ltd",
    "Suscriptor": "Cras Pellentesque Sed Institute",
    "vigdesde": "09-25-20",
    "vighasta": "10-27-22",
    "estado": "Nunc",
    "Nuevo": "true",
    "Usuario": "Garrison",
    "Poliza": "E3J 3S3"
  },
  {
    "factura": 98,
    "serie": 17,
    "exp": 2259,
    "Fe_registro": "04-02-21",
    "Domicilio": "144-9548 Lectus C/",
    "Moneda": 7,
    "Ramo": "eget",
    "Indole": "Vel Corporation",
    "Negocio": "Risus LLP",
    "Cedente": "Purus Gravida Sagittis LLP",
    "AsegAfian": "Consectetuer Institute",
    "Suscriptor": "Feugiat Tellus Industries",
    "vigdesde": "07-01-20",
    "vighasta": "03-06-21",
    "estado": "dolor",
    "Nuevo": "false",
    "Usuario": "Porter",
    "Poliza": "F7B 7H2"
  },
  {
    "factura": 99,
    "serie": 14,
    "exp": 2374,
    "Fe_registro": "07-23-21",
    "Domicilio": "589-6391 Eget Avenida",
    "Moneda": 1,
    "Ramo": "molestie dapibus ligula.",
    "Indole": "Fringilla LLC",
    "Negocio": "Nunc Pulvinar Arcu LLP",
    "Cedente": "Varius LLC",
    "AsegAfian": "Rhoncus Ltd",
    "Suscriptor": "Curabitur Consequat PC",
    "vigdesde": "05-01-20",
    "vighasta": "07-31-21",
    "estado": "lacus.",
    "Nuevo": "true",
    "Usuario": "Uriah",
    "Poliza": "B6B 4G4"
  },
  {
    "factura": 100,
    "serie": 17,
    "exp": 2358,
    "Fe_registro": "06-28-21",
    "Domicilio": "5972 Tellus Avda.",
    "Moneda": 3,
    "Ramo": "tincidunt",
    "Indole": "Proin Velit Company",
    "Negocio": "Suspendisse LLC",
    "Cedente": "Pharetra Nam Associates",
    "AsegAfian": "Mauris Molestie Company",
    "Suscriptor": "Tellus Eu Incorporated",
    "vigdesde": "06-13-20",
    "vighasta": "02-12-21",
    "estado": "accumsan",
    "Nuevo": "true",
    "Usuario": "Kenyon",
    "Poliza": "V6V 3P5"
  }
]

export default registro1;